<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateLawSchoolsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('law_schools', function (Blueprint $table) {
            $table->id();
            $table->string('name');
        });

        \Illuminate\Support\Facades\DB::table('law_schools')->insert([
            [ "name" => "Georgetown University"],
            [ "name" => "Harvard University"],
            [ "name" => "George Washington University"],
            [ "name" => "New York University"],
            [ "name" => "Fordham University"],
            [ "name" => "Columbia University"],
            [ "name" => "American University"],
            [ "name" => "Rutgers University"],
            [ "name" => "Mitchell Hamline School of Law"],
            [ "name" => "Western Michigan University"],
            [ "name" => "University of Miami"],
            [ "name" => "New York Law School"],
            [ "name" => "Brooklyn Law School"],
            [ "name" => "Suffolk University"],
            [ "name" => "Loyola Marymount University-Los Angeles"],
            [ "name" => "University of Michigan"],
            [ "name" => "Cardozo School of Law"],
            [ "name" => "University of California-Berkeley"],
            [ "name" => "University of Texas at Austin"],
            [ "name" => "University of California-Los Angeles"],
            [ "name" => "South Texas College of Law"],
            [ "name" => "John Marshall Law School"],
            [ "name" => "University of Virginia"],
            [ "name" => "University of California-Hastings"],
            [ "name" => "Stetson University"],
            [ "name" => "Emory University"],
            [ "name" => "Arizona State University"],
            [ "name" => "Southwestern Law School"],
            [ "name" => "Hofstra University"],
            [ "name" => "Indiana University - Indianapolis"],
            [ "name" => "Loyola University-Chicago"],
            [ "name" => "University of Florida"],
            [ "name" => "University of Denver"],
            [ "name" => "University of Pennsylvania"],
            [ "name" => "St. John's University"],
            [ "name" => "Northwestern University"],
            [ "name" => "Boston University"],
            [ "name" => "University of San Diego"],
            [ "name" => "St. Mary's University"],
            [ "name" => "Temple University"],
            [ "name" => "Boston College"],
            [ "name" => "Chicago-Kent College of Law-IIT"],
            [ "name" => "Washington University"],
            [ "name" => "Santa Clara University"],
            [ "name" => "New England Law | Boston"],
            [ "name" => "Southern Methodist University"],
            [ "name" => "Michigan State University"],
            [ "name" => "Duke University"],
            [ "name" => "Inter American University of Puerto Rico"],
            [ "name" => "University of Houston"],
            [ "name" => "California Western School of Law"],
            [ "name" => "Southern University"],
            [ "name" => "University of Baltimore"],
            [ "name" => "University of Minnesota"],
            [ "name" => "Georgia State University"],
            [ "name" => "Depaul University"],
            [ "name" => "University of Wisconsin"],
            [ "name" => "Seattle University"],
            [ "name" => "Barry University"],
            [ "name" => "Seton Hall University"],
            [ "name" => "University of Maryland"],
            [ "name" => "Pace University"],
            [ "name" => "University of South Carolina"],
            [ "name" => "Yale University"],
            [ "name" => "City University of New York"],
            [ "name" => "Nova Southeastern University"],
            [ "name" => "Tulane University"],
            [ "name" => "Syracuse University"],
            [ "name" => "University of Chicago"],
            [ "name" => "Charleston School of Law"],
            [ "name" => "Florida State University"],
            [ "name" => "Northeastern University"],
            [ "name" => "Cornell University"],
            [ "name" => "William and Mary Law School"],
            [ "name" => "University of North Carolina"],
            [ "name" => "University of Notre Dame"],
            [ "name" => "Widener University-Delaware"],
            [ "name" => "University of California-Davis"],
            [ "name" => "University of Detroit Mercy"],
            [ "name" => "University of Southern California"],
            [ "name" => "University of Georgia"],
            [ "name" => "Ohio State University"],
            [ "name" => "Texas Southern University"],
            [ "name" => "Marquette University"],
            [ "name" => "Louisiana State University"],
            [ "name" => "Stanford University"],
            [ "name" => "University of Puerto Rico"],
            [ "name" => "St. Thomas University (Florida)"],
            [ "name" => "Florida A&M University"],
            [ "name" => "Vanderbilt University"],
            [ "name" => "Saint Louis University"],
            [ "name" => "Lewis and Clark College"],
            [ "name" => "Wake Forest University"],
            [ "name" => "Villanova University"],
            [ "name" => "University of Colorado"],
            [ "name" => "University of California-Irvine"],
            [ "name" => "McGeorge School of Law"],
            [ "name" => "Loyola University-New Orleans"],
            [ "name" => "Indiana University - Bloomington"],
            [ "name" => "Touro College"],
            [ "name" => "University of Oklahoma"],
            [ "name" => "Campbell University"],
            [ "name" => "George Mason University"],
            [ "name" => "University of Washington"],
            [ "name" => "Pepperdine University"],
            [ "name" => "Golden Gate University"],
            [ "name" => "Albany Law School of Union University"],
            [ "name" => "Roger Williams University"],
            [ "name" => "Texas A&M University"],
            [ "name" => "University of Connecticut"],
            [ "name" => "Florida International University"],
            [ "name" => "Vermont Law School"],
            [ "name" => "Chapman University"],
            [ "name" => "Oklahoma City University"],
            [ "name" => "Duquesne University"],
            [ "name" => "Baylor University"],
            [ "name" => "University of St. Thomas (Minnesota)"],
            [ "name" => "Drexel University"],
            [ "name" => "University of Nevada - Las Vegas"],
            [ "name" => "University of Arkansas-Little Rock"],
            [ "name" => "Howard University"],
            [ "name" => "Samford University"],
            [ "name" => "Capital University"],
            [ "name" => "University of Iowa"],
            [ "name" => "University of Buffalo-SUNY"],
            [ "name" => "Wayne State University"],
            [ "name" => "University of Akron"],
            [ "name" => "University of Mississippi"],
            [ "name" => "University of Oregon"],
            [ "name" => "Texas Tech University"],
            [ "name" => "Cleveland State University"],
            [ "name" => "Case Western Reserve University"],
            [ "name" => "Washington and Lee University"],
            [ "name" => "University of San Francisco"],
            [ "name" => "Catholic University of America"],
            [ "name" => "University of Pittsburgh"],
            [ "name" => "University of Illinois"],
            [ "name" => "Northern Kentucky University"],
            [ "name" => "University of Nebraska"],
            [ "name" => "Quinnipiac University"],
            [ "name" => "University of Richmond"],
            [ "name" => "Mercer University"],
            [ "name" => "Pontifical Catholic University of P.R."],
            [ "name" => "Pennsylvania State University-Penn State Law"],
            [ "name" => "University of Alabama"],
            [ "name" => "University of Arizona"],
            [ "name" => "Elon University"],
            [ "name" => "Gonzaga University"],
            [ "name" => "UNT Dallas College Of Law"],
            [ "name" => "University of Missouri-Kansas City"],
            [ "name" => "University of Tennessee"],
            [ "name" => "North Carolina Central University"],
            [ "name" => "University of Cincinnati"],
            [ "name" => "University of Louisville"],
            [ "name" => "University of Kentucky"],
            [ "name" => "Willamette University"],
            [ "name" => "University of Memphis"],
            [ "name" => "University of Arkansas-Fayetteville"],
            [ "name" => "Mississippi College"],
            [ "name" => "Brigham Young University"],
            [ "name" => "Belmont University"],
            [ "name" => "University of Idaho"],
            [ "name" => "University of Hawaii"],
            [ "name" => "West Virginia University"],
            [ "name" => "Drake University"],
            [ "name" => "Widener Commonwealth"],
            [ "name" => "University of Kansas"],
            [ "name" => "Creighton University"],
            [ "name" => "University of New Mexico"],
            [ "name" => "University of Tulsa"],
            [ "name" => "Atlanta's John Marshall Law School"],
            [ "name" => "University of New Hampshire"],
            [ "name" => "Washburn University"],
            [ "name" => "University of Utah"],
            [ "name" => "University of La Verne"],
            [ "name" => "Western New England University"],
            [ "name" => "University of Massachusetts Dartmouth"],
            [ "name" => "Northern Illinois University"],
            [ "name" => "University of Toledo"],
            [ "name" => "Lincoln Memorial University"],
            [ "name" => "Regent University"],
            [ "name" => "University of Missouri"],
            [ "name" => "Ave Maria School of Law"],
            [ "name" => "Southern Illinois University-Carbondale"],
            [ "name" => "University of Maine"],
            [ "name" => "University of Dayton"],
            [ "name" => "District of Columbia"],
            [ "name" => "University of Montana"],
            [ "name" => "Western State College of Law"],
            [ "name" => "Pennsylvania State University-Dickinson School of Law"],
            [ "name" => "University of Wyoming"],
            [ "name" => "Thomas Jefferson School of Law"],
            [ "name" => "University of North Dakota"],
            [ "name" => "Liberty University"],
            [ "name" => "University of South Dakota"],
            [ "name" => "Concordia Law School"],
            [ "name" => "Florida Coastal School of Law"],
            [ "name" => "Faulkner University"],
            [ "name" => "Appalachian School of Law"],
            [ "name" => "Ohio Northern University"]
        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('law_schools');
    }
}
