<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->timestamps();
        });
        
        \Illuminate\Support\Facades\DB::table('countries')->insert(
            array(
                ["name" => "Afghanistan"],
                ["name" => "Albania"],
                ["name" => "Algeria"],
                ["name" => "American Samoa"],
                ["name" => "Andorra"],
                ["name" => "Angola"],
                ["name" => "Anguilla"],
                ["name" => "Antarctica"],
                ["name" => "Antigua and Barbuda"],
                ["name" => "Argentina"],
                ["name" => "Armenia"],
                ["name" => "Aruba"],
                ["name" => "Australia"],
                ["name" => "Austria"],
                ["name" => "Azerbaijan"],
                ["name" => "Bahamas"],
                ["name" => "Bahrain"],
                ["name" => "Bangladesh"],
                ["name" => "Barbados"],
                ["name" => "Belarus"],
                ["name" => "Belgium"],
                ["name" => "Belize"],
                ["name" => "Benin"],
                ["name" => "Bermuda"],
                ["name" => "Bhutan"],
                ["name" => "Bolivia"],
                ["name" => "Bosnia and Herzegovina"],
                ["name" => "Botswana"],
                ["name" => "Bouvet Island"],
                ["name" => "Brazil"],
                ["name" => "British Antarctic Territory"],
                ["name" => "British Indian Ocean Territory"],
                ["name" => "British Virgin Islands"],
                ["name" => "Brunei"],
                ["name" => "Bulgaria"],
                ["name" => "Burkina Faso"],
                ["name" => "Burundi"],
                ["name" => "Cambodia"],
                ["name" => "Cameroon"],
                ["name" => "Canada"],
                ["name" => "Canton and Enderbury Islands"],
                ["name" => "Cape Verde"],
                ["name" => "Cayman Islands"],
                ["name" => "Central African Republic"],
                ["name" => "Chad"],
                ["name" => "Chile"],
                ["name" => "China"],
                ["name" => "Christmas Island"],
                ["name" => "Cocos [Keeling] Islands"],
                ["name" => "Colombia"],
                ["name" => "Comoros"],
                ["name" => "Congo - Brazzaville"],
                ["name" => "Congo - Kinshasa"],
                ["name" => "Cook Islands"],
                ["name" => "Costa Rica"],
                ["name" => "Croatia"],
                ["name" => "Cuba"],
                ["name" => "Cyprus"],
                ["name" => "Czech Republic"],
                ["name" => "Côte d’Ivoire"],
                ["name" => "Denmark"],
                ["name" => "Djibouti"],
                ["name" => "Dominica"],
                ["name" => "Dominican Republic"],
                ["name" => "Dronning Maud Land"],
                ["name" => "East Germany"],
                ["name" => "Ecuador"],
                ["name" => "Egypt"],
                ["name" => "El Salvador"],
                ["name" => "Equatorial Guinea"],
                ["name" => "Eritrea"],
                ["name" => "Estonia"],
                ["name" => "Ethiopia"],
                ["name" => "Falkland Islands"],
                ["name" => "Faroe Islands"],
                ["name" => "Fiji"],
                ["name" => "Finland"],
                ["name" => "France"],
                ["name" => "French Guiana"],
                ["name" => "French Polynesia"],
                ["name" => "French Southern Territories"],
                ["name" => "French Southern and Antarctic Territories"],
                ["name" => "Gabon"],
                ["name" => "Gambia"],
                ["name" => "Georgia"],
                ["name" => "Germany"],
                ["name" => "Ghana"],
                ["name" => "Gibraltar"],
                ["name" => "Greece"],
                ["name" => "Greenland"],
                ["name" => "Grenada"],
                ["name" => "Guadeloupe"],
                ["name" => "Guam"],
                ["name" => "Guatemala"],
                ["name" => "Guernsey"],
                ["name" => "Guinea"],
                ["name" => "Guinea-Bissau"],
                ["name" => "Guyana"],
                ["name" => "Haiti"],
                ["name" => "Heard Island and McDonald Islands"],
                ["name" => "Honduras"],
                ["name" => "Hong Kong SAR China"],
                ["name" => "Hungary"],
                ["name" => "Iceland"],
                ["name" => "India"],
                ["name" => "Indonesia"],
                ["name" => "Iran"],
                ["name" => "Iraq"],
                ["name" => "Ireland"],
                ["name" => "Isle of Man"],
                ["name" => "Israel"],
                ["name" => "Italy"],
                ["name" => "Jamaica"],
                ["name" => "Japan"],
                ["name" => "Jersey"],
                ["name" => "Johnston Island"],
                ["name" => "Jordan"],
                ["name" => "Kazakhstan"],
                ["name" => "Kenya"],
                ["name" => "Kiribati"],
                ["name" => "Kuwait"],
                ["name" => "Kyrgyzstan"],
                ["name" => "Laos"],
                ["name" => "Latvia"],
                ["name" => "Lebanon"],
                ["name" => "Lesotho"],
                ["name" => "Liberia"],
                ["name" => "Libya"],
                ["name" => "Liechtenstein"],
                ["name" => "Lithuania"],
                ["name" => "Luxembourg"],
                ["name" => "Macau SAR China"],
                ["name" => "Macedonia"],
                ["name" => "Madagascar"],
                ["name" => "Malawi"],
                ["name" => "Malaysia"],
                ["name" => "Maldives"],
                ["name" => "Mali"],
                ["name" => "Malta"],
                ["name" => "Marshall Islands"],
                ["name" => "Martinique"],
                ["name" => "Mauritania"],
                ["name" => "Mauritius"],
                ["name" => "Mayotte"],
                ["name" => "Metropolitan France"],
                ["name" => "Mexico"],
                ["name" => "Micronesia"],
                ["name" => "Midway Islands"],
                ["name" => "Moldova"],
                ["name" => "Monaco"],
                ["name" => "Mongolia"],
                ["name" => "Montenegro"],
                ["name" => "Montserrat"],
                ["name" => "Morocco"],
                ["name" => "Mozambique"],
                ["name" => "Myanmar [Burma]"],
                ["name" => "Namibia"],
                ["name" => "Nauru"],
                ["name" => "Nepal"],
                ["name" => "Netherlands"],
                ["name" => "Netherlands Antilles"],
                ["name" => "Neutral Zone"],
                ["name" => "New Caledonia"],
                ["name" => "New Zealand"],
                ["name" => "Nicaragua"],
                ["name" => "Niger"],
                ["name" => "Nigeria"],
                ["name" => "Niue"],
                ["name" => "Norfolk Island"],
                ["name" => "North Korea"],
                ["name" => "North Vietnam"],
                ["name" => "Northern Mariana Islands"],
                ["name" => "Norway"],
                ["name" => "Oman"],
                ["name" => "Pacific Islands Trust Territory"],
                ["name" => "Pakistan"],
                ["name" => "Palau"],
                ["name" => "Palestinian Territories"],
                ["name" => "Panama"],
                ["name" => "Panama Canal Zone"],
                ["name" => "Papua New Guinea"],
                ["name" => "Paraguay"],
                ["name" => "People's Democratic Republic of Yemen"],
                ["name" => "Peru"],
                ["name" => "Philippines"],
                ["name" => "Pitcairn Islands"],
                ["name" => "Poland"],
                ["name" => "Portugal"],
                ["name" => "Puerto Rico"],
                ["name" => "Qatar"],
                ["name" => "Romania"],
                ["name" => "Russia"],
                ["name" => "Rwanda"],
                ["name" => "Réunion"],
                ["name" => "Saint Barthélemy"],
                ["name" => "Saint Helena"],
                ["name" => "Saint Kitts and Nevis"],
                ["name" => "Saint Lucia"],
                ["name" => "Saint Martin"],
                ["name" => "Saint Pierre and Miquelon"],
                ["name" => "Saint Vincent and the Grenadines"],
                ["name" => "Samoa"],
                ["name" => "San Marino"],
                ["name" => "Saudi Arabia"],
                ["name" => "Senegal"],
                ["name" => "Serbia"],
                ["name" => "Serbia and Montenegro"],
                ["name" => "Seychelles"],
                ["name" => "Sierra Leone"],
                ["name" => "Singapore"],
                ["name" => "Slovakia"],
                ["name" => "Slovenia"],
                ["name" => "Solomon Islands"],
                ["name" => "Somalia"],
                ["name" => "South Africa"],
                ["name" => "South Georgia and the South Sandwich Islands"],
                ["name" => "South Korea"],
                ["name" => "Spain"],
                ["name" => "Sri Lanka"],
                ["name" => "Sudan"],
                ["name" => "Suriname"],
                ["name" => "Svalbard and Jan Mayen"],
                ["name" => "Swaziland"],
                ["name" => "Sweden"],
                ["name" => "Switzerland"],
                ["name" => "Syria"],
                ["name" => "São Tomé and Príncipe"],
                ["name" => "Taiwan"],
                ["name" => "Tajikistan"],
                ["name" => "Tanzania"],
                ["name" => "Thailand"],
                ["name" => "Timor-Leste"],
                ["name" => "Togo"],
                ["name" => "Tokelau"],
                ["name" => "Tonga"],
                ["name" => "Trinidad and Tobago"],
                ["name" => "Tunisia"],
                ["name" => "Turkey"],
                ["name" => "Turkmenistan"],
                ["name" => "Turks and Caicos Islands"],
                ["name" => "Tuvalu"],
                ["name" => "U.S. Minor Outlying Islands"],
                ["name" => "U.S. Miscellaneous Pacific Islands"],
                ["name" => "U.S. Virgin Islands"],
                ["name" => "Uganda"],
                ["name" => "Ukraine"],
                ["name" => "Union of Soviet Socialist Republics"],
                ["name" => "United Arab Emirates"],
                ["name" => "United Kingdom"],
                ["name" => "United States"],
                ["name" => "Unknown or Invalid Region"],
                ["name" => "Uruguay"],
                ["name" => "Uzbekistan"],
                ["name" => "Vanuatu"],
                ["name" => "Vatican City"],
                ["name" => "Venezuela"],
                ["name" => "Vietnam"],
                ["name" => "Wake Island"],
                ["name" => "Wallis and Futuna"],
                ["name" => "Western Sahara"],
                ["name" => "Yemen"],
                ["name" => "Zambia"],
                ["name" => "Zimbabwe"],
                ["name" => "Aland Islands"],
            )
        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
