<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Support\Facades\Response;

class MailingListDownloadController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    public function downloadStudentLoanList()
    {
        // Users
        // TODO: Filter Users to just users of type borrowers
        // Consulting
        // TODO: MailChimp List

        // Name
        // Email
        // University - Match to Federal List

        $users             = User::all();
        $consulting_emails = [
            '0tina.shiu0@gmail.com',
            'a.klestadt@gmail.com',
            'aaron.shaiman@gmail.com',
            'aaron.wilson.higherlearning@gmail.com',
            'abartholomew1992@gmail.com',
            'abbey.myerson@gmail.com',
            'abdurakhmonov.sanjar@gmail.com',
            'abhijitsehgal@gmail.com',
            'abram.joey@gmail.com',
            'acc744@stern.nyu.edu',
            'acm562@stern.nyu.edu',
            'acwilson3@yahoo.com',
            'adame2082@gmail.com',
            'adamrabin930@gmail.com',
            'adanmanwabuo@yahoo.com',
            'adithi.raju@gmail.com',
            'aditi.3november@gmail.com',
            'aditij27@gmail.com',
            'adlay@wharton.upenn.edu',
            'adww89@gmail.com',
            'aepace.ap@gmail.com',
            'afabry2345@gmail.com',
            'agarwalshreya.k@gmail.com',
            'aidai.kozubekova@gmail.com',
            'aishani.bassi@kellogg.northwestern.edu',
            'ajinkyawalimbe@gmail.com',
            'akissilenko@gmail.com',
            'akshat70@gmail.com',
            'alana.j.magli@gmail.com',
            'alancbr@gmail.com',
            'alanhan@gmail.com',
            'alanman@berkeley.edu',
            'alecgmiller@gmail.com',
            'alejandrobarreda.s@gmail.com',
            'alessandra.j.slayton@gmail.com',
            'alex.zhang@kellogg.northwestern.edu',
            'alexanderhong1991@gmail.com',
            'alexandra.page@pfizer.com',
            'alexandrajfriedman@gmail.com',
            'alfonsomacias14@gmail.com',
            'alina.malinauskaite99@gmail.com',
            'allison.wilson@stern.nyu.edu',
            'allisonbroas@gmail.com',
            'am3ps@gmail.com',
            'amansingla09@gmail.com',
            'amedack@gmail.com',
            'ammar.javaid91@gmail.com',
            'amneribarr@gmail.com',
            'anastasiia@caviston.com',
            'andreanunezvargas@gmail.com',
            'andrew.foody@yale.edu',
            'andrew.haimes@gmail.com',
            'andrewdurke@gmail.com',
            'angela.nian.liu@gmail.com',
            'angela.wtchen@gmail.com',
            'angelana@alumni.upenn.edu',
            'angeliki.varelas@gmail.com',
            'angira.jhaveri@gmail.com',
            'anh.a.pham@gmail.com',
            'anjaliaggarwal@nyu.edu',
            'ann.mallick@gmail.com',
            'anna.halawa@yale.edu',
            'annbullock4@gmail.com',
            'anuj.sandeep.shah@gmail.com',
            'anumita.chakrabarti@gmail.com',
            'anupama.gumber@gmail.com',
            'aria_zhang@hotmail.com',
            'arj.kulshreshtha@yahoo.co.in',
            'arwoltz@gmail.com',
            'ash.hojat@gmail.com',
            'ashley.indira@gmail.com',
            'ashleyclark01@gmail.com',
            'ashlie.labranche@gmail.com',
            'ashlientyler@gmail.com',
            'ashwingvarghese@gmail.com',
            'asker4ik@gmail.com',
            'athena.jin.x@gmail.com',
            'audrey.ren@outlook.com',
            'avu2008@gmail.com',
            'aw2384@gmail.com',
            'ayush.khanna@outlook.com',
            'ayushi.shrivastava@yale.edu',
            'ayyubbokhari@gmail.com',
            'beaugresham@gmail.com',
            'beccaanic@gmail.com',
            'behrmank15@gmail.com',
            'benedict.sumah@gmail.com',
            'benjamin.spero@gmail.com',
            'bfriedman20@gsb.columbia.edu',
            'bharat.mantha@gmail.com',
            'bhavikagoyal2009@gmail.com',
            'bianca.paris@yahoo.com',
            'bishnu.k.panigrahi@gmail.com',
            'bkemm2@gmail.com',
            'bkraus38@gmail.com',
            'blackett@wharton.upenn.edu',
            'blaine.r.davis@gmail.com',
            'borde@unc.edu',
            'brake.gabe@gmail.com',
            'brandon.p.weil@gmail.com',
            'brewm27@gmail.com',
            'brian.tsien@gmail.com',
            'brogdonp@gmail.com',
            'bruce.song@kellogg.northwestern.edu',
            'brunna.bseabra@gmail.com',
            'bryandavis1231@gmail.com',
            'bwolff1124@gmail.com',
            'caitlin.stanton@gmail.com',
            'caitlinoconnell25@gmail.com',
            'camhoa.lieu@gmail.com',
            'carissa.sanchez@aya.yale.edu',
            'carol.cui@outlook.com',
            'caseyabmanning@gmail.com',
            'cassie.ryding@gmail.com',
            'cathy.j.cao@gmail.com',
            'cen27@duke.edu',
            'cgcora@163.com',
            'chaanukya25@gmail.com',
            'che.pooja@gmail.com',
            'chi2115@gmail.com',
            'chinguojie@gmail.com',
            'chris.joondeph@gmail.com',
            'chrisguo0531@gmail.com',
            'christinekeung@gmail.com',
            'christopher.kalpin@gmail.com',
            'christopher.r.skinner@gmail.com',
            'cihan.sahin@hotmail.fr',
            'cjwang06@gmail.com',
            'claireosterman@gmail.com',
            'clay.holk@gmail.com',
            'cliffxia@163.com',
            'clj781@gmail.com',
            'cmcilroy2013@gmail.com',
            'coamiller@gmail.com',
            'coneillstillman@gmail.com',
            'conradobterra@gmail.com',
            'craig.caroline10@gmail.com',
            'crazzano@alumni.nd.edu',
            'crystal.chalk07@gmail.com',
            'ctalfredlee@gmail.com',
            'cuikimb@gmail.com',
            'cwoojinpark@gmail.com',
            'cxh@wharton.upenn.edu',
            'cye@wellesley.edu',
            'czelikow@gmail.com',
            'dajuan.e.bennett@gmail.com',
            'danakim920@gmail.com',
            'danarabuvaeva@gmail.com',
            'daniela.chona@gmail.com',
            'danielapetu18@gmail.com',
            'daniellapihuska59@gmail.com',
            'danielweiner92@gmail.com',
            'daodao.vicky.zhang@gmail.com',
            'davidtrumantracy@gmail.com',
            'davquez07@gmail.com',
            'dbarcia@mba2020.hbs.edu',
            'dblagg20@gsb.columbia.edu',
            'demetriusdsouza@hotmail.com',
            'denasrose@gmail.com',
            'dep95@cornell.edu',
            'devalprateek23@gmail.com',
            'devin.m.gross@gmail.com',
            'dfallon3@gmail.com',
            'dhillonravi1983@gmail.com',
            'dhwanimehta22@gmail.com',
            'diegoparedesb@gmail.com',
            'dillonkang@gmail.com',
            'divijdamodhar@gmail.com',
            'dlomax@umich.edu',
            'dmitry.m.gurinsky@gmail.com',
            'dmonaghan15@gmail.com',
            'dolagunju1@gmail.com',
            'dorilevy@umich.edu',
            'dserpa.p@gmail.com',
            'dunlop.connor@gmail.com',
            'dwenzel07@gmail.com',
            'e.olamidebada@gmail.com',
            'eduardo.r@chicagobooth.edu',
            'ehuang39@gmail.comn',
            'ekabuye@umich.edu',
            'elainecodd@gmail.com',
            'eleanor.elbert@gmail.com',
            'eliz.l.briggs@gmail.com',
            'elizabeth.alison.stein@gmail.com',
            'elizabeth.davis.walker@gmail.com',
            'elizacdav@gmail.com',
            'ellismshawn@gmail.com',
            'emccaff11@gmail.com',
            'emilie.futterman@gmail.com',
            'emilioafifc@gmail.com',
            'emily.graffius@gmail.com',
            'emma.kwaa@gmail.com',
            'emma.wc.ho@gmail.com',
            'emmadulife@gmail.com',
            'emweems@gmail.com',
            'engebretson.teresa@gmail.com',
            'eric.bishop@kellogg.northwestern.edu',
            'erichouhsu@gmail.com',
            'ericykwon@gmail.com',
            'erin.shuba@gmail.com',
            'eshaanpuri@gmail.com',
            'eurico.queiroz@gmail.com',
            'eurico@umich.edu',
            'evan.wu54@gmail.com',
            'evantied@gmail.com',
            'ezraglenn@gmail.com',
            'fangyizhou2011@gmail.com',
            'farhana.hoss@gmail.com',
            'faye.wang@yale.edu',
            'fcrudele@gmail.com',
            'fdiazchirino20@gsb.columbia.edu',
            'fionaxycui@gmail.com',
            'franklyn.nnakwue@gmail.com',
            'friedland.jamie@gmail.com',
            'gabe.t.rosen@gmail.com',
            'gabrielle.clark.9@gmail.com',
            'gandhi.raina@gmail.com',
            'gaojin1991@yahoo.com',
            'garethpan@gmail.com',
            'gaur0608@gmail.com',
            'gautamsiddhartha14@gmail.com',
            'gbhatt@wharton.upenn.edu',
            'giang.h.nguyen1906@gmail.com',
            'gibby.graves@gmail.com',
            'giles.evans@gmail.com',
            'gina.borden@stern.nyu.edu',
            'gina.m.stella@gmail.com',
            'giovanni.cruz@yale.edu',
            'gkaefring@gmail.com',
            'gklissurski@gmail.com',
            'grant.zeller@gmail.com',
            'gretchenkrupp@gmail.com',
            'guleria_saurabh@yahoo.com',
            'gyw0307@gmail.com',
            'hadibeik@gmail.com',
            'hai.tiange@gmail.com',
            'hamdyyasmine@gmail.com',
            'hang.nmh@gmail.com',
            'hannah.l.ringel@gmail.com',
            'hanson.kj.zheng@gmail.com',
            'harish.chamarthy@kellogg.northwestern.edu',
            'harleenchawla3@gmail.com',
            'harrison.f.shih@gmail.com',
            'harvin13@gmail.com',
            'hazel.pike@kellogg.northwestern.edu',
            'hazelgun@gmail.com',
            'helena.stefanowicz@gmail.com',
            'hi@charlotteyang.com',
            'himanshus1991@gmail.com',
            'hongyi1@wharton.upenn.edu',
            'hr.schonwald@gmail.com',
            'hsinman88@gmail.com',
            'huang.ken.z@gmail.com',
            'hugosalinasl@gmail.com',
            'huihu@umich.edu',
            'hunterlew2@gmail.com',
            'hwang.minjeong@gmail.com',
            'i.adam@wustl.edu',
            'i.gonzalezdelmazo@gmail.com',
            'ienwere@wharton.upenn.edu',
            'il74@cornell.edu',
            'ila.choudhary@gmail.com',
            'imlouyun@gmail.com',
            'ingrid.keppe@gmail.com',
            'irabelo04@gmail.com',
            'irenekoo08@gmail.com',
            'iris-hehua@hotmail.com',
            'isabel.brodsky@gmail.com',
            'ishanishres@gmail.com',
            'isha_paul@berkeley.edu',
            'itang@mba2020.hbs.edu',
            'j.asher.begley@gmail.com',
            'j.libergott@gmail.com',
            'jackarmstrong2009@gmail.com',
            'jacob.fenske.tu20@tuck.dartmouth.edu',
            'james.e.henderson269@gmail.com',
            'james.j.adams@outlook.com',
            'janemlee01@gmail.com',
            'jarchiba@chicagobooth.edu',
            'jasminemann44@gmail.com',
            'jcarojas@gmail.com',
            'jchart92@gmail.com',
            'jcw352@cornell.edu',
            'jdcedeno329@gmail.com',
            'jdnixon8504@gmail.com',
            'jdonahu2@alumni.nd.edu',
            'jeffrey.boyar@gmail.com',
            'jena.goettisheim@gmail.com',
            'jenna.leahy1988@gmail.com',
            'jennifer.ma67@gmail.com',
            'jeremy.wano@gmail.com',
            'jerrisonli2@gmail.com',
            'jessicapollard8@gmail.com',
            'jessie.zhaoc@yahoo.com',
            'jh3719@stern.nyu.edu',
            'jillelanglas@gmail.com',
            'jisiguo16@gmail.com',
            'jkatiraei@gmail.com',
            'jmh595@cornell.edu',
            'jodirich@umich.edu',
            'joewithers@gmail.com',
            'johnsondavidben@gmail.com',
            'jordanrosales12@gmail.com',
            'joshuafact10@gmail.com',
            'jp.grant.iv@gmail.com',
            'jpanfel@gmail.com',
            'jquartner@chicagobooth.edu',
            'jrsbaseball5@gmail.com',
            'jslunde@wharton.upenn.edu',
            'juhyun822@gmail.com',
            'julianneungar@gmail.com',
            'june.zhang@kellogg.northwestern.edu',
            'juniorl@umich.edu',
            'jwjones091@gmail.com',
            'jwohlmuth@gmail.com',
            'kai.sheng17@gmail.com',
            'kaila.squires@gmail.com',
            'kailuo@live.com',
            'kaleighkilloran@gmail.com',
            'kapildevbansal@gmail.com',
            'karankatyal89@gmail.com',
            'karen.evans2010@gmail.com',
            'kari.yu.xinzhu@gmail.com',
            'karina.gerstenschlager@kellogg.northwestern.edu',
            'karthikk1188@gmail.com',
            'katharineveddy@gmail.com',
            'kathyyliao@gmail.com',
            'katiesuarez14@gmail.com',
            'katzor@gmail.com',
            'kay.j.kuang@outlook.com',
            'kayyali89@gmail.com',
            'kchanguab@gmail.com',
            'kcwh628@gmail.com',
            'keith.mulatya@gmail.com',
            'kellycw525@gmail.com',
            'kellylombard23@gmail.com',
            'kelsey.tsai@chicagobooth.edu',
            'kendraerskine@gmail.com',
            'kheahmad@gmail.com',
            'kholin.daniil@gmail.com',
            'khyi72@yahoo.com',
            'kirti.santosh.chandak@gmail.com',
            'kjgoldenberg@gmail.com',
            'kjoyce734@gmail.com',
            'klubega@stanford.edu',
            'knealon27@gmail.com',
            'kongamyel@gmail.com',
            'kris.masoor@gmail.com',
            'krishna.abhinav@gmail.com',
            'kristin_jiang@outlook.com',
            'krutika.sood@gmail.com',
            'ktura@mba2020.hbs.edu',
            'kush.verm@gmail.com',
            'lacolla.c@gmail.com',
            'lanceloangkote@yahoo.com',
            'laura.huichen@gmail.com',
            'lavanyanaidu.90@gmail.com',
            'lcairong@gmail.com',
            'lcarberry92@gmail.com',
            'ldbarth@gmail.com',
            'leahnaidorf@gmail.com',
            'leahyhoward@gmail.com',
            'lee.jason.08@gmail.com',
            'leekdeng@wharton.upenn.edu',
            'leeor.mushin@gmail.com',
            'leshaw2@gmail.com',
            'liliia.voitenko@outpost-club.com',
            'limaye.varun23@gmail.com',
            'linalicelynn@gmail.com',
            'lindahorner321@gmail.com',
            'lindsey217@gmail.com',
            'liushuaiqing@gmail.com',
            'liyilang21@gmail.com',
            'lizbeth.martinez@kellogg.northwestern.edu',
            'lizfonseca44@gmail.com',
            'lizwlavin@gmail.com',
            'lmeliani@mba2020.hbs.edu',
            'lnees@umich.edu',
            'lnrehaut@gmail.com',
            'lucile.cancre@gmail.com',
            'luiswilson225@gmail.com',
            'lulio@umich.edu',
            'm.patrick.tye@gmail.com',
            'mabhinav@wharton.upenn.edu',
            'maddy.han@yahoo.com',
            'madeline.y.vuong@gmail.com',
            'madhuri.k.madan@gmail.com',
            'mail.for.bmi@gmail.com',
            'maleangrubb@gmail.com',
            'malongjiao@gmail.com',
            'manaskulk@gmail.com',
            'mandy.yunying.yu@gmail.com',
            'manrajp@gmail.com',
            'mariam.topuria@kellogg.northwestern.edu',
            'marianne.poh@gmail.com',
            'marisjhmoon@gmail.com',
            'marissa.hamilton09@gmail.com',
            'marquardt.clara@gmail.com',
            'maryma89111@outlook.com',
            'mathewegold@gmail.com',
            'matthew.baseman@gmail.com',
            'matthew.sauers1@gmail.com',
            'matthewjrstevens@gmail.com',
            'max.a.napolitano@gmail.com',
            'mayaandersons@gmail.com',
            'mbcarter123@gmail.com',
            'mcc5405@gmail.com',
            'mcdaniel.halley@gmail.com',
            'meghanelizabethlyons@gmail.com',
            'mehtashashank91@gmail.com',
            'melodyzlam@gmail.com',
            'menair@deloitte.com',
            'menesh2002@gmail.com',
            'mengxing.fiona@gmail.com',
            'mespericueta11@gmail.com',
            'michael.a.neely@gmail.com',
            'michael.jw.son@gmail.com',
            'michael.thomas.hoban@gmail.com',
            'michaelmcquade11@gmail.com',
            'michaelsong01810@gmail.com',
            'michelle.f.ferber@gmail.com',
            'michelle.fasano4@gmail.com',
            'michelletew@gmail.com',
            'mike.zappala@yale.edu',
            'mikegmiller11@gmail.com',
            'mileshrp@gmail.com',
            'minhminh2010@gmail.com',
            'mithunkalaga@gmail.com',
            'miya.sharpe@yale.edu',
            'mjoselow@gmail.com',
            'mjpolelle@gmail.com',
            'mkaura@mac.com',
            'mlerner20@gsb.columbia.edu',
            'mmaenner20@gsb.columbia.edu',
            'mmakligh@gmail.com',
            'mmlamb@wharton.upenn.edu',
            'mnbane2@gmail.com',
            'mnhester@wharton.upenn.edu',
            'mnishant@live.unc.edu',
            'modolu@gmail.com',
            'mohanliang@gmail.com',
            'montes.alan@gmail.com',
            'moyay4@gmail.com',
            'mp989@cornell.edu',
            'mpatel93@gmail.com',
            'mptouchkina@gmail.com',
            'msestee@gmail.com',
            'mstolpinski@gmail.com',
            'mukeshsharma.cdg@gmail.com',
            'murchisonnatalie@gmail.com',
            'mutha.abhishek49@gmail.com',
            'mw.sin@hotmail.com',
            'nairbrandon@gmail.com',
            'nancy.hilliker@gmail.com',
            'narayani.gupta@wellesley.edu',
            'nas75@cornell.edu',
            'natalie.s.rose12@gmail.com',
            'nathanyohannes1@gmail.com',
            'natibarbosa1@gmail.com',
            'navya2392@gmail.com',
            'neelakantan.kailash@gmail.com',
            'nethra.venkatesh91@gmail.com',
            'newman.6.11@gmail.com',
            'nicholas.m.qiu@gmail.com',
            'nick.springmann@gmail.com',
            'nikhita.gupta@yale.edu',
            'nikita.mits@gmail.com',
            'niraliadesai@gmail.com',
            'nisha@berkeley.edu',
            'nitisha123@gmail.com',
            'nl450@stern.nyu.edu',
            'nmb455@stern.nyu.edu',
            'nmunoz@umich.edu',
            'nooraninida@gmail.com',
            'nthome@pennlaw.upenn.edu',
            'olivia.vonnieda@gmail.com',
            'ongbernard3@gmail.com',
            'orgeorgy@gmail.com',
            'oseghale.amies@gmail.com',
            'osi.momoh@gmail.com',
            'otaiwopeters@gmail.com',
            'pabloparis15@gmail.com',
            'pakanont.t@gmail.com',
            'pako.kbral@gmail.com',
            'pankhuri.sharma@kellogg.northwestern.edu',
            'paolalvfalco@gmail.com',
            'param.s.randhawa@gmail.com',
            'pateljitesh@gmail.com',
            'paul.nganguem@kellogg.northwestern.edu',
            'paulstramag@gmail.com',
            'payal.vachhani77@gmail.com',
            'payalmotwani@outlook.com',
            'pdevivo@chicagobooth.edu',
            'pdlphilip@gmail.com',
            'pearlsinghal@gmail.com',
            'petranovichr@gmail.com',
            'pfrailey@chicagobooth.edu',
            'phsadness@126.com',
            'piercesm76@gmail.com',
            'pmanojna@gmail.com',
            'pmeltser@chicagobooth.edu',
            'poddertanushree@gmail.com',
            'poju.adenariwo@gmail.com',
            'pooja.patel@kellogg.northwestern.edu',
            'poya.chang@gmail.com',
            'pprintz12@gmail.com',
            'prateek.jood@gmail.com',
            'prineeta.kulkarni@gmail.com',
            'priyanka.keserwani@gmail.com',
            'priyasha98@gmail.com',
            'prs5117@gmail.com',
            'ptbhargava@gmail.com',
            'pthakral3@gmail.com',
            'pushkarmuilay9@gmail.com',
            'q.yang91@gmail.com',
            'qaundinya.sahana@gmail.com',
            'qiaoyizh@gmail.com',
            'rachaelmt39@gmail.com',
            'rachel.joy.kim@gmail.com',
            'rachelnpetersen@gmail.com',
            'rafe.gandola@gmail.com',
            'rahul031092@gmail.com',
            'rahulgokhale17985@gmail.com',
            'rajatg@umich.edu',
            'rania.changhaoran@gmail.com',
            'ravipidi@gmail.com',
            'rbburroughs4@gmail.com',
            'rc.vessell@gmail.com',
            'rebeccamilian15@gmail.com',
            'reidsimmons@gmail.com',
            'rfukushima07sg@gmail.com',
            'rgh274@stern.nyu.edu',
            'rhianrogan@gmail.com',
            'riazul.x.islam@gmail.com',
            'rinchou@umich.edu',
            'risha.kaushal@gmail.com',
            'rmcinerney20@gmail.com',
            'rmoore92@wharton.upenn.edu',
            'rnakaar@wharton.upenn.edu',
            'roberra.aklilu@villanova.edu',
            'robert.chung.app@gmail.com',
            'robertncrampton@gmail.com',
            'rohan.hebbar91@gmail.com',
            'rohan.maini@kellogg.northwestern.edu',
            'rokitoa@gmail.com',
            'rolando.vega@yale.edu',
            'ronak.sh.parikh@gmail.com',
            'roshan.palli@gmail.com',
            'roshprakash@gmail.com',
            'roydlim@gmail.com',
            'rreagan3@gmail.com',
            'rterlixidou@gmail.com',
            'runqisong@aya.yale.edu',
            'rushilw@umich.edu',
            'ryanmeghan2@gmail.com',
            'ryanritchie7@gmail.com',
            'sabina.ashbaugh@gmail.com',
            'sabrina.houshanshan@hotmail.com',
            'sahana.qaundinya@duke.edu',
            'sahilbhatia.dtu@gmail.com',
            'sai.syd@gmail.com',
            'sak_2ac@yahoo.com',
            'sallyann.zhou@gmail.com',
            'samantha.harrington20@gmail.com',
            'samchibwowa@gmail.com',
            'samjmaxfield@gmail.com',
            'samuel.smith588@gmail.com',
            'samyakjaroli@gmail.com',
            'sarah.consagra@kellogg.northwestern.edu',
            'sarah.e.russell10@gmail.com',
            'sarah.wagner@hec.edu',
            'sarahsgermain@gmail.com',
            'saraxali@gmail.com',
            'saumya.sharma.tu20@tuck.dartmouth.edu',
            'saumyasharma.spice@gmail.com',
            'sbhaskaran@chicagobooth.edu',
            'schang@mba2020.hbs.edu',
            'scott.k.steever@gmail.com',
            'sd.singh@hpsa.in',
            'sean.madison@gmail.com',
            'seth.girsky@gmail.com',
            'sethwartak@gmail.com',
            'sfs5055@gmail.com',
            'sghosh9801@gmail.com',
            'shaibyalovedalal@gmail.com',
            'shannonrosenauer@gmail.com',
            'sharpk14@gmail.com',
            'shashwatmittal92@gmail.com',
            'shawnayavari@gmail.com',
            'shekhar.sumit@icloud.com',
            'shevy2041@gmail.com',
            'shivani.gupta12@gmail.com',
            'shuangzheng22@yahoo.com',
            'shuebsch@umich.edu',
            'shv5@duke.edu',
            'simonttiu@gmail.com',
            'singh.anju29@gmail.com',
            'siwol.chang@gmail.com',
            'sjessica@wustl.edu',
            'skrampa@gmail.com',
            'slampka@gmail.com',
            'smancini@chicagobooth.edu',
            'smocking21@gmail.com',
            'snehanagarajan@outlook.com',
            'snigdha.mim2014@gmail.com',
            'snyder.m.ryan@gmail.com',
            'soham.khanna@stern.nyu.edu',
            'sonaligosain1992@gmail.com',
            'sonya.h.dekhtyar@gmail.com',
            'soobia_haider@hotmail.com',
            'sophia.yeres@kellogg.northwestern.edu',
            'sophie.mysong@gmail.com',
            'souvik.b1225@gmail.com',
            'srademaker@svoco.com',
            'srosena0@chicagobooth.edu',
            'ssenge@gmail.com',
            'stanya787@gmail.com',
            'stepanian.george@gmail.com',
            'stephanie.y.yeh@gmail.com',
            'stephaniejonesyoung@gmail.com',
            'stephen.f.simon@gmail.com',
            'sugih.muliadi@gmail.com',
            'sukriti.aggarwal@kellogg.northwestern.edu',
            'sumabojedla@gmail.com',
            'surabhi.khanna9@gmail.com',
            'sushilshetty1000@gmail.com',
            'susieffan@gmail.com',
            'susieyjin@yahoo.com',
            'suvarchagupta1@gmail.com',
            'swagatb@umich.edu',
            'sz554@cornell.edu',
            'taiwo989@gmail.com',
            'talisha.l.rice@gmail.com',
            'tamar.nisbett@gmail.com',
            'tarikwalmsley@gmail.com',
            'tarini.sundar@kellogg.northwestern.edu',
            'tarunjoshi.91@gmail.com',
            'taylor@danielson.la',
            'tbaumgarten2913@gmail.com',
            'thakral.guneet@gmail.com',
            'thanghuu@gmail.com',
            'thomas.menzefricke@gmail.com',
            'tiaayele92@gmail.com',
            'tianpan1@163.com',
            'tiffaine.stephens@gmail.com',
            'timothy.purdie2@gmail.com',
            'tlim20@gsb.columbia.edu',
            'tlin20@wharton.upenn.edu',
            'tlwoods@wharton.upenn.edu',
            'tmanked@chicagobooth.edu',
            'tnikolouzos@gmail.com',
            'to225@cornell.edu',
            'toby.okonkwo@kellogg.northwestern.edu',
            'toggynunghe@gmail.com',
            'tomqlin06@gmail.com',
            'tony.ie@outlook.com',
            'tony.kim.9191@gmail.com',
            'tori.irons@gmail.com',
            'tova.adina@gmail.com',
            'trangml12@gmail.com',
            'triciary27@gmail.com',
            'vaishaali@hotmail.com',
            'victormakula@yahoo.co.uk',
            'vikram.sridhar1990@gmail.com',
            'vincentg.ho@mail.utoronto.ca',
            'vinitatal@gmail.com',
            'viraja@umich.edu',
            'virginiahuizhang@gmail.com',
            'vivek.ashok@columbia.edu',
            'vlu@wharton.upenn.edu',
            'voda2008@126.com',
            'vpung327@gmail.com',
            'vsparikh@gmail.com',
            'wechter.max@gmail.com',
            'wei-yin.lin@kellogg.northwestern.edu',
            'wei.daichen@gmail.com',
            'wesley.a.flanigan@gmail.com',
            'wfk212@stern.nyu.edu',
            'willeloeb@gmail.com',
            'wupeiqinp@outlook.com',
            'xiaomeng.yang@hulu.com',
            'xinglin@post.harvard.edu',
            'xinweimichaelxu@gmail.com',
            'y.serrato09@gmai.com',
            'y.zhou10@gmail.com',
            'yale.viny@gmail.com',
            'yanjunchen1021@gmail.com',
            'yaoxinliu1989@gmail.com',
            'yaping.pku@gmail.com',
            'yatesaj8@gmail.com',
            'yelei.angie.chen@gmail.com',
            'yiqin.jiang@gmail.com',
            'ylitviakova@gmail.com',
            'ymzh@umich.edu',
            'youfu.ideatalks@gmail.com',
            'yuan.feng.tu20@dartmouth.edu',
            'yulianaonopriyenko@gmail.com',
            'zacharyjbrenner@gmail.com',
            'zkoser@gmail.com',
            'zmustafa93@gmail.com',
        ];

        $university_swap_list = [
            ['{"id":109,"university":"Stanford University","dental":0,"law":1,"business":1,"engineering":1,"nursingma":0,"nursingdnp":0,"physicians_assistant":1,"medicine":1,"created_at":null,"updated_at":null}', 'STANFORD UNIVERSITY - GRAD SCH BUSINESS'],
            ['{"id":128,"university":"University of California - Berkeley","dental":0,"law":1,"business":1,"engineering":1,"nursingma":0,"nursingdnp":0,"physicians_assistant":0,"medicine":0,"created_at":null,"updated_at":null}', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['{"id":131,"university":"University of California - Los Angeles","dental":1,"law":0,"business":1,"engineering":1,"nursingma":1,"nursingdnp":0,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'UNIVERSITY OF CALIFORNIA (UCLA)'],
            ['{"id":138,"university":"University of Chicago","dental":0,"law":1,"business":1,"engineering":0,"nursingma":0,"nursingdnp":0,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'UNIVERSITY OF CHICAGO (THE)'],
            ['{"id":164,"university":"University of Michigan - Ann Arbor","dental":1,"law":1,"business":1,"engineering":1,"nursingma":1,"nursingdnp":1,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'UNIVERSITY OF MICHIGAN - ANN ARBOR'],
            ['{"id":17,"university":"Columbia University","dental":1,"law":1,"business":1,"engineering":1,"nursingma":1,"nursingdnp":1,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'COLUMBIA UNIVERSITY IN THE CITY OF NEW Y'],
            ['{"id":175,"university":"University of North Carolina - Chapel Hill","dental":1,"law":0,"business":1,"engineering":0,"nursingma":1,"nursingdnp":1,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'UNIVERSITY OF N C-CHAPEL HILL'],
            ['{"id":183,"university":"University of Pennsylvania","dental":1,"law":1,"business":1,"engineering":1,"nursingma":1,"nursingdnp":0,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'UNIVERSITY OF PENNSYLVANIA'],
            ['{"id":19,"university":"Cornell University","dental":0,"law":1,"business":1,"engineering":1,"nursingma":0,"nursingdnp":0,"physicians_assistant":1,"medicine":1,"created_at":null,"updated_at":null}', 'CORNELL UNIVERSITY'],
            ['{"id":194,"university":"University of Southern California","dental":1,"law":0,"business":1,"engineering":1,"nursingma":0,"nursingdnp":0,"physicians_assistant":1,"medicine":1,"created_at":null,"updated_at":null}', 'UNIVERSITY OF SOUTHERN CALIFORNIA'],
            ['{"id":204,"university":"University of Texas - Austin","dental":0,"law":0,"business":1,"engineering":1,"nursingma":1,"nursingdnp":0,"physicians_assistant":0,"medicine":0,"created_at":null,"updated_at":null}', 'UNIVERSITY OF TEXAS-AUSTIN'],
            ['{"id":22,"university":"Dartmouth College","dental":0,"law":0,"business":1,"engineering":1,"nursingma":0,"nursingdnp":0,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'DARTMOUTH COLLEGE'],
            ['{"id":25,"university":"Duke University","dental":0,"law":1,"business":1,"engineering":1,"nursingma":1,"nursingdnp":1,"physicians_assistant":1,"medicine":1,"created_at":null,"updated_at":null}', 'DUKE UNIVERSITY'],
            ['{"id":30,"university":"Emory University","dental":0,"law":0,"business":1,"engineering":0,"nursingma":1,"nursingdnp":1,"physicians_assistant":1,"medicine":1,"created_at":null,"updated_at":null}', 'EMORY UNIVERSITY'],
            ['{"id":38,"university":"Georgetown University","dental":0,"law":1,"business":1,"engineering":0,"nursingma":1,"nursingdnp":1,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'GEORGETOWN UNIV, SCH OF MEDICINE'],
            ['{"id":44,"university":"Harvard University","dental":1,"law":1,"business":1,"engineering":1,"nursingma":0,"nursingdnp":0,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'HARVARD BUSINESS SCHOOL'],
            ['{"id":62,"university":"Massachusetts Institute of Technology","dental":0,"law":0,"business":1,"engineering":1,"nursingma":0,"nursingdnp":0,"physicians_assistant":0,"medicine":0,"created_at":null,"updated_at":null}', 'MASSACHUSETTS INST OF TECHNOLOGY'],
            ['{"id":75,"university":"New York University","dental":1,"law":1,"business":1,"engineering":1,"nursingma":1,"nursingdnp":1,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'NEW YORK UNIVERSITY'],
            ['{"id":79,"university":"Northwestern University","dental":0,"law":1,"business":1,"engineering":1,"nursingma":0,"nursingdnp":0,"physicians_assistant":1,"medicine":1,"created_at":null,"updated_at":null}', 'NORTHWESTERN UNIV'],
            ['{"id":117,"university":"Thomas Jefferson University","dental":0,"law":0,"business":0,"engineering":0,"nursingma":0,"nursingdnp":1,"physicians_assistant":0,"medicine":1,"created_at":null,"updated_at":null}', 'Thomas Jefferson University'],
            ['{"id":2,"university":"Arizona State University","dental":0,"law":0,"business":1,"engineering":1,"nursingma":1,"nursingdnp":1,"physicians_assistant":0,"medicine":0,"created_at":null,"updated_at":null}', 'Arizona State University'],
            ['{"id":61,"university":"Marquette University","dental":1,"law":0,"business":0,"engineering":0,"nursingma":0,"nursingdnp":1,"physicians_assistant":0,"medicine":0,"created_at":null,"updated_at":null}', 'Marquette University'],

            ['University of Chicago', 'UNIVERSITY OF CHICAGO (THE)'],
            ['University of Pennsylvania', 'UNIVERSITY OF PENNSYLVANIA'],
            ['Duke University', 'DUKE UNIVERSITY'],
            ['Northwestern University', 'NORTHWESTERN UNIV'],
            ['Columbia University', 'COLUMBIA UNIVERSITY IN THE CITY OF NEW Y'],
            ['University of Michigan--Ann Arbor', 'UNIVERSITY OF MICHIGAN - ANN ARBOR'],
            ['University of Virginia', 'UNIVERSITY OF VIRGINIA - SFS'],
            ['Stanford University', 'STANFORD UNIVERSITY - GRAD SCH BUSINESS'],
            ['Dartmouth University', 'DARTMOUTH COLLEGE'],
            ['University of California--Berkeley', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['MIT', 'MASSACHUSETTS INST OF TECHNOLOGY'],
            ['University of California--Los Angeles', 'UNIVERSITY OF CALIFORNIA (UCLA)'],
            ['New York University', 'NEW YORK UNIVERSITY'],
            ['Cornell University', 'CORNELL UNIVERSITY'],
            ['Georgetown University', 'GEORGETOWN UNIV, SCH OF MEDICINE'],
            ['University of Michigan - Ann Arbor', 'UNIVERSITY OF MICHIGAN - ANN ARBOR'],
            ['University of California - Berkeley', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['Yale University', 'YALE UNIVERSITY'],
            ['University of Texas--Austin', 'UNIVERSITY OF TEXAS-AUSTIN'],
            ['Massachusetts Institute of Technology', 'MASSACHUSETTS INST OF TECHNOLOGY'],
            ['University of California - Los Angeles', 'UNIVERSITY OF CALIFORNIA (UCLA)'],
            ['University of Michigan', 'UNIVERSITY OF MICHIGAN - ANN ARBOR'],
            ['Dartmouth College', 'DARTMOUTH COLLEGE'],
            ['Rice University', 'RICE UNIVERSITY'],
            ['University of North Carolina--Chapel Hill', 'UNIVERSITY OF N C-CHAPEL HILL'],
            ['University of North Carolina - Chapel Hill', 'UNIVERSITY OF N C-CHAPEL HILL'],
            ['Washington University in St. Louis', 'WASHINGTON UNIVERSITY'],
            ['University of Washington', 'UNIVERSITY OF WASHINGTON'],
            ['Stanford GSB', 'STANFORD UNIVERSITY - GRAD SCH BUSINESS'],
            ['Emory University', 'EMORY UNIVERSITY'],
            ['NYU', 'NEW YORK UNIVERSITY'],
            ['Georgetown University', 'GEORGETOWN UNIVERSITY'],
            ['UT Austin', 'UNIVERSITY OF TEXAS-AUSTIN'],
            ['New York University', 'NEW YORK UNIVERSITY'],
            ['University of California--Los Angeles', 'UNIVERSITY OF CALIFORNIA (UCLA)'],
            ['University of Texas - Austin', 'UNIVERSITY OF TEXAS-AUSTIN'],
            ['Stanford', 'STANFORD UNIVERSITY - GRAD SCH BUSINESS'],
            ['HBS', 'HARVARD BUSINESS SCHOOL'],
            ['Georgetown University', 'GEORGETOWN UNIV, SCH OF MEDICINE'],
            ['Chicago Booth', 'UNIVERSITY OF CHICAGO (THE)'],
            ['Harvard University', 'HARVARD LAW SCHOOL'],
            ['Harvard University', 'HARVARD BUSINESS SCHOOL'],
            ['University of Southern California', 'UNIVERSITY OF SOUTHERN CALIFORNIA'],
            ['University of Virginia', 'UNIVERSITY OF VIRGINIA - SFS'],
            ['Booth', 'UNIVERSITY OF CHICAGO (THE)'],
            ['Ucla Anderson', 'UNIVERSITY OF CALIFORNIA (UCLA)'],
            ['MIT Sloan', 'MASSACHUSETTS INST OF TECHNOLOGY'],
            ['Massachusetts', 'MASSACHUSETTS INST OF TECHNOLOGY'],
            ['Boston University', 'BOSTON UNIVERSITY'],
            ['University of Pennsylvania', 'UNIVERSITY OF PENNSYLVANIA'],
            ['Washington University Saint Louis', 'WASHINGTON UNIVERSITY'],
            ['Berkeley Haas', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['Wharton', 'UNIVERSITY OF PENNSYLVANIA'],
            ['Meharry', 'MEHARRY MEDICAL COLLEGE'],
            ['Columbia University', 'COLUMBIA UNIVERSITY IN THE CITY OF NEW Y'],
            ['George Washington University', 'GEORGE WASHINGTON UNIV LAW SCHL'],
            ['Emory University', 'EMORY UNIVERSITY'],
            ['University of Chicago Booth School of Business', 'UNIVERSITY OF CHICAGO (THE)'],
            ['Haas', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['University of California--Berkeley', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['Meharry', 'MEHARRY MEDICAL COLLEGE'],
            ['Stanford Graduate School of Business', 'STANFORD UNIVERSITY - GRAD SCH BUSINESS'],
            ['Kellogg', 'NORTHWESTERN UNIV'],
            ['Duke Fuqua', 'DUKE UNIVERSITY'],
            ['Fordham University', 'FORDHAM UNIVERSITY'],
            ['University of Tennessee', 'UNIVERSITY OF TENNESSEE-KNOXVILLE'],
            ['UC Berkeley Haas', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['University of Chicago Booth', 'UNIVERSITY OF CHICAGO (THE)'],
            ['UCLA', 'UNIVERSITY OF CALIFORNIA (UCLA)'],
            ['MIT Sloan School of Management', 'MASSACHUSETTS INST OF TECHNOLOGY'],
            ['Indiana University', 'INDIANA UNIVERSITY-BLOOMINGTON'],
            ['University of Chicago', 'UNIVERSITY OF CHICAGO (THE)'],
            ['Vanderbilt University', 'VANDERBILT UNIVERSITY'],
            ['UC Berkeley Haas School of Business', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['Duke', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['Harvard University', 'HARVARD LAW SCHOOL'],
            ['Duke Fuqua School of Business', 'DUKE UNIVERSITY'],
            ['UChicago Booth', 'UNIVERSITY OF CHICAGO (THE)'],
            ['Kellogg School of Management', 'NORTHWESTERN UNIV'],
            ['Boston University', 'BOSTON UNIVERSITY'],
            ['Carnegie Mellon', 'CARNEGIE MELLON- TEPPER SCHOOL OF BUSINE'],
            ['Carnegie Mellon University', 'CARNEGIE MELLON- TEPPER SCHOOL OF BUSINE'],
            ['Duke University', 'DUKE UNIVERSITY'],
            ['University of Chicago - Booth School of Business', 'UNIVERSITY OF CHICAGO (THE)'],
            ['Fuqua', 'DUKE UNIVERSITY'],
            ['Harvard', 'HARVARD BUSINESS SCHOOL'],
            ['Haas School of Business at UC Berkeley', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['The University of Chicago Booth School of Business', 'UNIVERSITY OF CHICAGO (THE)'],
            ['Berkeley-Haas', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['Columbia Business School', 'COLUMBIA UNIVERSITY IN THE CITY OF NEW Y'],
            ['Darden', 'UNIVERSITY OF VIRGINIA - SFS'],
            ['UC Berkeley - Haas', 'UNIVERSITY OF CALIFORNIA, BERKELEY'],
            ['Northwestern University - Kellogg School of Management', 'NORTHWESTERN UNIV'],
            ['Duke - Fuqua', 'DUKE UNIVERSITY'],
            ['Northwestern Kellogg', 'NORTHWESTERN UNIV'],
            ['Kellogg - Northwestern', 'NORTHWESTERN UNIV'],
            ['refinance', ''],
        ];

        $headers = [
            'Cache-Control'       => 'must-revalidate, post-check=0, pre-check=0',
            'Content-type'        => 'text/csv',
            'Content-Disposition' => 'attachment; filename=inschool_data_' . date('FdY') . '.csv',
            'Expires'             => '0',
            'Pragma'              => 'no-cache',
        ];

        $columns = [
            'Name',
            'Email',
            'University',
        ];

        $export_data = [];

        foreach ($users as $borrower) {
            // Skip anything with test in the name
            if ((false !== strpos(strtolower($borrower->name), 'test'))) {
                continue;
            }

            if ((false !== strpos(strtolower($borrower->name), '5cc'))) {
                continue;
            }

            if ((false !== strpos(strtolower($borrower->name), '5cd'))) {
                continue;
            }

            // Swap out the University
            $university = $borrower->university;
            foreach ($university_swap_list as $swap_item) {
                if ($borrower->university == $swap_item[0]) {
                    $university = $swap_item[1];
                }
            }

            // Write the line to CSV File
            array_push($export_data, [
                ucwords($borrower->name ?? ''),
                strtolower($borrower->email) ?? '',
                $university ?? '',
            ]);
        }

        foreach ($consulting_emails as $borrower) {
            // Write the line to CSV File
            array_push($export_data, [
                '',
                strtolower($borrower) ?? '',
                '',
            ]);
        }

        // Create Duplicates for Harvard Law and Harvard Business
        foreach ($export_data as $row) {
            if ('HARVARD LAW SCHOOL' == $row[2]) {
                array_push($export_data, [
                    $row[0],
                    $row[1],
                    'HARVARD BUSINESS SCHOOL',
                ]);
            }

            if ('HARVARD BUSINESS SCHOOL' == $row[2]) {
                array_push($export_data, [
                    $row[0],
                    $row[1],
                    'HARVARD LAW SCHOOL',
                ]);
            }
        }

        $callback = function () use ($export_data, $columns) {
            $file = fopen('php://output', 'w');

            fputcsv($file, $columns);

            foreach ($export_data as $row) {
                fputcsv($file, $row);
            }

            // Close the file
            fclose($file);
        };

        // Return the response
        return Response::stream($callback, 200, $headers);
    }
}
