<?php

namespace App\Console\Commands;

use App\MailchimpAutomatedCampaignUser;
use App\MarketingEmailUnsubscribe;
use App\NegotiationGroup;
use App\UnsubscribeRequest;
use App\User;
use App\UserProfile;
use Carbon\Carbon;
use Illuminate\Console\Command;

class NgWelcomeEmails extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'ng:welcome-emails';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Send ng welcome emails';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        $alreadySentEmails = [
            "rdronamr@chicagobooth.edu",
            "wclevid@gmail.com",
            "david_elkin@chicagobooth.edu",
            "alejandro.johns@gmail.com",
            "maria.nikopoulos@gmail.com",
            "shahsro11@gmail.com",
            "nnennajemie@gmail.com",
            "michael.a.ray.tu22@tuck.dartmouth.edu",
            "shreya.sitaraman@gmail.com",
            "07jtravis24@gmail.com",
            "kristen.e.clifford@gmail.com",
            "charlotte213@live.com",
            "bfodouop@mba2021.hbs.edu",
            "mlherman@gmail.com",
            "sanchit.mulmuley@gmail.com",
            "kconnor1@alumni.nd.edu",
            "bafatmah@gmail.com",
            "mayashaposhnik@gmail.com",
            "zjzbacnik@gmail.com",
            "afarin.davari@gmail.com",
            "roseborough.jordan@gmail.com",
            "sskim1990@gmail.com",
            "jordan.baird10@gmail.com",
            "Amelmore87@gmail.com",
            "okonkwo.izunna@gmail.com",
            "jackie.lam@berkeley.edu",
            "mgwchen@gmail.com",
            "ipeteryoon@gmail.com",
            "cfrisch@mba2021.hbs.edu",
            "iris.y.shao@gmail.com",
            "jacqueline.wulfsohn@gmail.com",
            "kimberly_lam@berkeley.edu",
            "ckupersmith13@gmail.com",
            "michaelbeals4@gmail.com",
            "supreeti77@gmail.com",
            "jlin88@gmail.com",
            "amritr@umich.edu",
            "seanvaziri1@gmail.com",
            "tucker.remy@gmail.com",
            "paulcho409@gmail.com",
            "tfisher04@mac.com",
            "matthewputzulu@gmail.com",
            "kna1@uchicago.edu",
            "philip.n.krebs@gmail.com",
            "ryan.cumpston@gmail.com",
            "tohfe.beidas@gmail.com",
            "john.c.minich@gmail.com",
            "ross.t.butler@gmail.com",
            "mgodoy@wharton.upenn.edu",
            "jordanollee3@gmail.com",
            "zachsnow1990@gmail.com",
            "Asad.rafi2@gmail.com",
            "duarte41691@gmail.com",
            "john_maher@berkeley.edu",
            "samuel.han.2021@marshall.usc.edu",
            "khaled.alshawi@gmail.com",
            "mcalvano@stanford.edu",
            "asad.berani@kellogg.northwestern.edu",
            "plouffy@gmail.com",
            "sbion@wharton.upenn.edu",
            "jessenebres@gmail.com",
            "abhinav.naman@gmail.com",
            "akinori.takeyasu@gmail.com",
            "stacywnelson@gmail.com",
            "kurzman.ben@gmail.com",
            "cunninghamj21@darden.virginia.edu",
            "jennyscouller@gmail.com",
            "michaelhu@ricealumni.net",
            "angiecho95@gmail.com",
            "gifford.andrewp@gmail.com",
            "neche@wharton.upenn.edu",
            "jaygraham28@gmail.com",
            "charrington@mba.berkeley.edu",
            "jimmy.yang@berkeley.edu",
            "jonathan.caleb.bryant@gmail.com",
            "james.gruetzmacher@kellogg.northwestern.edu",
            "braxton.r.lethco@gmail.com",
            "sean@seanlipkin.com",
            "ashleyhsnow@gmail.com",
            "benwest2495@gmail.com",
            "Spencer.coffin.clt@gmail.com",
            "ghayur.minhaj@gmail.com",
            "hanhlinh.hotran@gmail.com",
            "ymu2@nd.edu",
            "jess.wu353@gmail.com",
            "ds2275@cornell.edu",
            "hoguer.sanchez@gmail.com",
            "mjayaret@gmail.com",
            "qianpan9@gmail.com",
            "pcrum3131@gmail.com",
            "mhakimdds@gmail.com",
            "justinmtimmons@gmail.com",
            "jpepelnj@alumni.nd.edu",
            "jack.lazebnik@gmail.com",
            "reena.shah234@gmail.com",
            "jlanzilla3@gmail.com",
            "james.f.maier@gmail.com",
            "Tony.graves@yale.edu",
            "devonsanford8@gmail.com",
            "rafael.tavarez@gmail.com",
            "Ssussex@mba2022.hbs.edu",
            "jessicayanok@gmail.com",
            "wdslovell@gmail.com",
            "rpavey@mba2022.hbs.edu",
            "max+clicks@leveredge.org",
            "nathanael.isai.nunez@gmail.com",
            "rf447@cornell.edu",
            "nramacha@chicagobooth.edu",
            "austinshore18@gmail.com",
            "patrick.rauh@gmail.com",
            "brianmc@umich.edu",
            "cody.storm@duke.edu",
            "BAlomary21@gsb.columbia.edu",
            "anthonyrdt@hotmail.com",
            "kis27@cornell.edu",
            "reed.megant@gmail.com",
            "cybaker@utexas.edu",
            "kennedy.sean88@gmail.com",
            "scottandrewbennett@gmail.com",
            "rforeman@mit.edu",
            "clopezlopez@mba2022.hbs.edu",
            "rodrigoveraco@gmail.com",
            "melissa.levy711@gmail.com",
            "alex.innocent@gmail.com",
            "kaltamiranotx@gmail.com",
            "tabitha.f.plummer@gmail.com",
            "adriankao@gmail.com",
            "rdutta716@Gmail.com",
            "delaneywing@gmail.com",
            "jbtravis91@gmail.com",
            "kyle.mccroskey@gmail.com",
            "Hady.abouj@gmail.com",
            "Clford369@gmail.com",
            "dpaik09@hotmail.com",
            "natebrockert@gmail.com",
            "jackiembirnbaum@gmail.com",
            "syed.zkhan12@gmail.com",
            "marcanthony121@gmail.com",
            "alexking902@yahoo.com",
            "courtney.mansukani@gmail.com",
            "vpahari@stanford.edu",
            "gramanuj@umich.edu",
            "ohanlonmatt@gmail.com",
            "dzhang952@gmail.com",
            "srustagi8837@gmail.com",
            "catriona.ayer@gmail.com",
            "nacampbell00@gmail.com",
            "jsweiner93@gmail.com",
            "wesvattadi@aol.com",
            "dylan.dorenfeld@gmail.com",
            "jenniferjiaqixu@gmail.com",
            "bryan.martin781@gmail.com",
            "meshach.cleary@gmail.com",
            "erin.ek.kelly@gmail.com",
            "blairboyce.10@gmail.com",
            "zeinah.adawi@gmail.com",
            "skoch@mba2022.hbs.edu",
            "segah@sloan.mit.edu",
            "wendallanthony@yahoo.com",
            "katzhang07@gmail.com",
            "moormapj@gmail.com",
            "saeedmehrabi@gmail.com",
            "bchideckel@gmail.com",
            "Robert.J.Gardner.TU21@Tuck.Dartmouth.EDU",
            "julienadig@gmail.com",
            "rmtsmith24@gmail.com",
            "phillipshogan@gmail.com",
            "jason.mailinglist@icloud.com",
            "dosorio629@gmail.com",
            "dianawong24@gmail.com",
            "avisoor14@gmail.com",
            "b.ashleyhill@gmail.com",
            "jaisonthomas1991@gmail.com",
            "dm454@cornell.edu",
            "vijutilwani@gmail.com",
            "cl1457@georgetown.edu",
            "12oberthuynh@gmail.com",
            "mchisholm94@gmail.com",
            "lsantos@mba2022.hbs.edu",
            "adam.w.harrell@gmail.com",
            "erica2490@gmail.com",
            "m.schneider@berkeley.edu",
            "vargas.jacqueline92@gmail.com",
            "Vthai.ventures@gmail.com",
            "ross.sarahc@gmail.com",
            "rmurphy1@chicagobooth.edu",
            "kelvin.e.sun@gmail.com",
            "aedward3@chicagobooth.edu",
            "matthewbell@chicagobooth.edu",
            "steve.desandis@gmail.com",
            "nickvanhollen@gmail.com",
            "tesoriero.michael1@gmail.com",
            "adekunle265@gmail.com",
            "woodruff.jack@gmail.com",
            "alexmoritz94@gmail.com",
            "Bren_higgins@yahoo.com",
            "ty283@georgetown.edu",
            "crt2131@columbia.edu",
            "drph57@yahoo.com",
            "k.ardiff1@gmail.com",
            "trevor.shorb@gmail.com",
            "sciortino21@gmail.com",
            "colinmcmahon415@gmail.com",
            "charbrown007@gmail.com",
            "wmurri@gmail.com",
            "Kanedcarpenter@gmail.com",
            "brewsterlee3@gmail.com",
            "kevin.r.daley@outlook.com",
            "Scc629@mst.edu",
            "yannickdwatie@yahoo.fr",
            "michaeltdent@gmail.com",
            "wenhuang92@gmail.com",
            "cschweiger091@gmail.com",
            "robert.j.winters@vanderbilt.edu",
            "olaniyex@gmail.com",
            "whitney.millegan@gmail.com",
            "renzo.alexander.hidalgo@gmail.com",
            "jamieulrich@gmail.com",
            "sarahssilv@gmail.com",
            "bmwhite630@gmail.com",
            "evan.hollins91@gmail.com",
            "esantiago@mba2022.hbs.edu",
            "kylemyu@gmail.com",
            "athenapetrides@gmail.com",
            "absparekh@yahoo.com",
            "jlp286@cornell.edu",
            "iam7088@stern.nyu.edu",
            "huston.julian@yale.edu",
            "rob@robgurley.com",
            "sarah.andes@gmail.com",
            "michael.nightingales@gmail.com",
            "ajh21@wharton.upenn.edu",
            "Ryan.Reiger@gmail.com",
            "j.murdoch.miller@gmail.com",
            "carlindacey@gmail.com",
            "jgsehgal@gmail.com",
            "paigemkimball@gmail.com",
            "arteagajosi@gmail.com",
            "richardluna@chicagobooth.edu",
            "joeysickler@gmail.com",
            "remoshfegh@deloitte.com",
            "skapnadak13@gmail.com",
            "amirsz@umich.edu",
            "christophergilcrestlaw@gmail.com",
            "mzoo_127@yahoo.com",
            "elliotferrara@gmail.com",
            "tyler.doehr@gmail.com",
            "dcooke21@gsb.columbia.edu",
            "kescokatie@gmail.com",
            "jordan.alan.carr@gmail.com",
            "camilo.a.cuellar@gmail.com",
            "daven.hines@yale.edu",
            "kyleschoen@gmail.com",
            "ppesek@wharton.upenn.edu",
            "charlotteruthharris@gmail.com",
            "mariasamanthalittle@gmail.com",
            "Jackie@thenry.net",
            "mkrishn0@chicagobooth.edu",
            "mdwyer02@gmail.com",
            "nickweiss1126@gmail.com",
            "christiancaiazzo10@gmail.com",
            "anjali@anjaliwadhwa.com",
            "aws3jp@gmail.com",
            "gperg001@gmail.com",
            "jwdenzler@gmail.com",
            "kara.kreutzberg@gmail.com",
            "ejkushman@gmail.com",
            "Makhavan.kim@gmail.com",
            "dhruv.gajaria@gmail.com",
            "claireking1@yahoo.com",
            "lhan01@outlook.com",
            "kevinshinilpark@gmail.com",
            "cathyan2012@gmail.com",
            "Vaishali.nij2@gmail.com",
            "jonny.m.vu@gmail.com",
            "liz.v.nunez@gmail.com",
            "tahaseen.misbah@gmail.com",
            "nikhilvanmali@hotmail.com",
            "kaemcdonnell@gmail.com",
            "davidalderman9@gmail.com",
            "vivianl@umich.edu",
            "alex.trombetta@berkeley.edu",
            "denasrose@gmail.com",
            "fox.davidc@gmail.com",
            "kercofa.francois@gmail.com",
            "kel57@duke.edu",
            "dennis.m.gallagher.tu21@tuck.dartmouth.edu",
            "rharte@umich.edu",
            "nluna@mba2021.hbs.edu",
            "pnaik@chicagobooth.edu",
            "kristin.kirby@chicagobooth.edu",
            "kastlgarrett@gmail.com",
            "sitarachandra@gmail.com",
            "julia.c.weeks@gmail.com",
            "caigreeff1@gmail.com",
            "egemencihan@hotmail.com",
            "jeff.librot@gmail.com",
            "msmith8780@gmail.com",
            "rossyudkin@gmail.com",
            "dfagbola@mit.edu",
            "theck7@gmail.com",
            "bpjoyce91@gmail.com",
            "shapironathan8@gmail.com",
            "craigth@wharton.upenn.edu",
            "max+cb@leveredge.org",
            "NICKNOVARRO@GMAIL.COM",
            "mannaf@wharton.upenn.edu",
            "kimler1@gmail.com",
            "srazavi@chicagobooth.edu",
            "charlotte.fagan.2021@anderson.ucla.edu",
            "natemamuyac@gmail.com",
            "james.h.vancel@gmail.com",
            "Spencer.Marzouk@gmail.com",
            "rpawaite@gmail.com",
            "mkd4dd@darden.virginia.edu",
            "afattore20@gmail.com",
            "julian03@wharton.upenn.edu",
            "slwang37@gmail.com",
            "wesleycary@utexas.edu",
            "brandon.azus@gmail.com",
            "jamiethornton1@live.co.uk",
            "vasupanicker@gmail.com",
            "le.bryan12@gmail.com",
            "albertyou@gmail.com",
            "davisajohn93@gmail.com",
            "ejswhear@gmail.com",
            "linda+emailtest@leveredge.org",
            "chaz.bauer@chicagobooth.edu",
            "jrsalazar89@gmail.com",
            "jordan.naylor12@gmail.com",
            "WILLJARVE@GMAIL.COM",
            "agrossbart@locusfinancial.com",
            "contact.cyen@gmail.com",
            "justinpfeldman@gmail.com",
            "dngrodsky@gmail.com",
            "esthxrpark@gmail.com",
            "Waynewluan@gmail.com",
            "clarkson.taylor@gmail.com",
            "ma'x+peoplam@leveredge.org",
            "taryn.puran@gmail.com",
            "nicoleehlim@gmail.com",
            "alex_russomagno@berkeley.edu",
            "sanjiyer@stanford.edu",
            "pcappello19@gmail.com",
            "tharari25@gmail.com",
            "vishal.mummigatti@gmail.com",
            "abishaijohananpinto@gmail.com",
            "lgarcia@jd22.law.harvard.edu",
            "nicolesharada@gmail.com",
            "kbellan1@binghamton.edu",
            "sfredericks@outlook.com",
            "farshams@yahoo.com",
            "stbrent@sentara.com",
            "skylarmommy25@yahoo.com",
            "michellecfrea@gmail.com",
            "b._.yebye@hotmail.com",
            "unfairhiphop@gmail.com",
            "ty410@nyu.edu",
            "ariswan26@gmail.com",
            "Caadam4@uky.edu",
            "corbettekonomou@gmail.com",
            "lcdinternational@yahoo.com",
            "shaozhao24@gmail.com",
            "Branden.karnell@gmail.com",
            "shannialon18@gmail.com",
            "bjrusso333@gmail.com",
            "kellysuewatson@gmail.com",
            "cajjames@gmail.com",
            "Slopezcasella@yahoo.com",
            "amriveraquiroz@gmail.com",
            "ezilber@jd22.law.harvard.edu",
            "mcmorris219@gmail.com",
            "fizza_8@hotmail.com",
            "savannahadams17@outlook.com",
            "je348@cornell.edu",
            "randomness_live_it09@hotmail.com",
            "max.w.liechty@gmail.com",
            "soneeg.allahverdian@gmail.com",
            "echo4fitness@hotmail.com",
            "jfasiata@gmail.com",
            "garrett.hayes1@gmail.com",
            "Rebecca.r.harding@gmail.com",
            "pinkham@clemson.edu",
            "ratownsend0610@gmail.com",
            "julia.sanguinett@gmail.com",
            "iris.peppers@gmail.com",
            "hazen.eckert@gmail.com",
            "khjwsc@aol.com",
            "ishy119026@aol.com",
            "farhanmohsin3@gmail.com",
            "beccadoremi@gmail.com",
            "cicarreon8@gmail.com",
            "ablex777@hotmail.com",
            "karligoldenberg2019@u.northwestern.edu",
            "Dianagarcia91@gmail.com",
            "Stephaniegreen729@gmail.com",
            "hhilligoss@jd22.law.harvard.edu",
            "xqc2016@gmail.com",
            "reinrm92@gmail.com",
            "lerna1@aol.com",
            "fanghua.lou@health.slu.edu",
            "e.mehta011@gmail.com",
            "daniellecedwards@gmail.com",
            "chinson95@gmail.com",
            "bmb126@pitt.edu",
            "traanne2@msn.com",
            "aeiland@iu.edu",
            "hana.brannigan@gmail.com",
            "Teamlouis2015@hotmail.com",
            "katie.hempill@gmail.com",
            "tintrup.emily21@gmail.com",
            "Briannguyen@brandeis.edu",
            "glenready@gmail.com",
            "bcski93@gmail.com",
            "richardwsnyder1@gmail.com",
            "andestarr@gmail.com",
            "carina.cione@gmail.com",
            "larahaddad.den@gmail.com",
            "msuresh@bu.edu",
            "samidalmeida@yahoo.fr",
            "anita.hc.tang@gmail.com",
            "taylee1195@icloud.com",
            "caleb.platt@biola.edu",
            "janeytaylor95@gmail.com",
            "Cwileycurtis@gmail.com",
            "truebrit31@aol.com",
            "nandini.srinivasan10@gmail.com",
            "kgover@jd23.law.harvard.edu",
            "michael.j.tischler@gmail.com",
            "bgor216@gmail.com",
            "meganabbott51@gmail.com",
            "jacquelinejhong@gmail.com",
            "mydoggieo@gmail.com",
            "keepmyfaithalways13@gmail.com",
            "mischas54@gmail.com",
            "Bdcheung@asu.edu",
            "Andreaanthonyalvarez@gmail.com",
            "mdwitkin@gmail.com",
            "irchaimark@gmail.com",
            "ccshalon@gmail.com",
            "emilymrogers3@gmail.com",
            "britney.x0@icloud.com",
            "mikerob1014@gmail.com",
            "Mario.iskander@ropers.com",
            "dst75@outlook.com",
            "De19e@my.fsu.edu",
            "dkimm@sas.upenn.edu",
            "Jacobcarabin@gmail.com",
            "espido1001@gmail.com",
            "dbrice200@gmail.com",
            "alexpkramer@gmail.com",
            "TAMMY.OASIS2105@GMAIL.COM",
            "barbarajayda3@gmail.com",
            "sminosa@bu.edu",
            "raina.kor@mnsu.edu",
            "sophia.a.lammers@gmail.com",
            "cm597@lindenwood.edu",
            "ac505@duke.edu",
            "kcorby94@gmail.com",
            "alicking617@yahoo.com",
            "austinbchurchill@gmail.com",
            "jhausauer0324@gmail.com",
            "sammy90@gmail.com",
            "j.esther.lee@hotmail.com",
            "melissaokoro@gmail.com",
            "rgeremew48@gmail.com",
            "pkha09@gmail.com",
            "samuelbritton0020@gmail.com",
            "iveydyson@gmail.com",
            "Samueldphelps@gmail.com",
            "monica.lievsay@gmail.com",
            "Crystalh2@hotmail.com",
            "Serenity31279@gmail.com",
            "Andylutes@gmail.com",
            "dihae.kim@gmail.com",
            "mendez.joshuaphillip@gmail.com",
            "lindsay.forepaugh@gmail.com",
            "nnn668p@gmail.com",
            "cook.jonathan23@outlook.com",
            "garybrown102@gmail.com",
            "mjordanwilt@gmail.com",
            "michaelchoi2023@nlaw.northwestern.edu",
            "evanms@gmail.com",
            "chopkins@charter.net",
            "cmccl65@gmail.com",
            "emilyandreaortiz@gmail.com",
            "Michaelrider0206@gmail.com",
            "mpina@wharton.upenn.edu",
            "sydney.adel@yahoo.com",
            "garykcookjr@gmail.com",
            "jacob.schoenberg@gmail.com",
            "Test55@gmail.com",
            "larsonconnorishii@gmail.com",
            "manzili9@outlook.com",
            "labella5th@gmail.com",
            "alessandria.redley@gmail.com",
            "bodine_smith@yahoo.com",
            "marquiekrpec92@outlook.com",
            "michelle.estefania.cruz@gmail.com",
            "jacqkuz@gmail.com",
            "bryan.d.jackson96@gmail.com",
            "miriamh2324@gmail.com",
            "N640508@AOL.com",
            "pronrg1@yahoo.com",
            "whr10789@gmail.com",
            "heathertrnc@yahoo.com",
            "lwright48@liberty.edu",
            "natasha.yangthito18@stjohns.edu",
            "gennarose90@gmail.com",
            "angel_grln@yahoo.com",
            "karenleung@utexas.edu",
            "hatabrania@gmail.com",
            "wmendoza1455@gmail.com",
            "thejoshj@gmail.com",
            "jochs25@gmail.com",
            "jalvara99@hotmail.com",
            "elsavoie22@gmail.com",
            "caitlynncoop@gmail.com",
            "lorenzojsantos13@gmail.com",
            "Newuser11111@gmail.com",
            "anthony.huynh.work@gmail.com",
            "shubhsharm@yahoo.com",
            "Dawn_benard@yahoo.com",
            "martinsdp3@gmail.com",
            "AntoinetteVFranklin@gmail.com",
            "kate.demase@gmail.com",
            "Venkata.gurrala09@gmail.com",
            "Rougedcapri24@gmail.com",
            "senecawyse@gmail.com",
            "phillip.hah@gmail.com",
            "jessica.zou@yale.edu",
            "AlexNadolny.1@gmail.com",
            "bwigtil@gmail.com",
            "sladethickey@gmail.com",
            "wmurri@gmail.com",
            "hhamidu2012@gmail.com",
            "laurang215@gmail.com",
            "yschoi1014@gmail.com",
            "christin.barrett@lc.cuny.edu",
            "530will@gmail.com",
            "amchas11@gmail.com",
            "sscribner1@antioch.edu",
            "torianneday@gmail.com",
            "asiacross22@gmail.com",
            "kileybmoore@gmail.com",
            "Lindsay.williams728@gmail.com",
            "katzsam@aol.com",
            "Unwritten39@yahoo.com",
            "kris10moreno@gmail.com",
            "ibragim.2@wright.edu",
            "TUCKTYRA@YAHOO.COM",
            "joelwmayo@gmail.com",
            "impink@outlook.com",
            "arbadea@gmail.com",
            "nikhil+test-3@leveredge.org",
            "ns4649@nyu.edu",
            "katydirwin@gmail.com",
            "civrymelvin@gmail.com",
            "jdcrocker121@gmail.com",
            "angie.r.winkler@biola.edu",
            "spring.c.miles@gmail.com",
            "tannerjmitton@gmail.com",
            "dharthakk@gmail.com",
            "despeterson3@gmail.com",
            "morganrewheeler@gmail.com",
            "mollyh716@gmail.com",
            "stephaniesalazarr@gmail.com",
            "Cmaddoxjr@gmail.com",
            "Deehunt1913@gmail.com",
            "alexa.kaitlyn@gmail.com",
            "narygray@gmail.com",
            "samitha2005@gmail.com",
            "max+joingroup@leveredge.org",
            "Victoriahigg@me.com",
            "erickajh59@gmail.com",
            "Bret4514@gmail.com",
            "jenniferbutler3121@yahoo.com",
            "tkrouse@umich.edu",
            "kktsturm@gmail.com",
            "jbeds11452@gmail.com",
            "charlene.bernarte@gmail.com",
            "mbaak@unomaha.edu",
            "rajpatel0599@gmail.com",
            "MjBilitski@gmail.com",
            "dteixeira62@gmail.com",
            "gabc1917@gmail.com",
            "laymichael@outlook.com",
            "danielleborton@yahoo.com",
            "jconcepsion.sanchez@gmail.com",
            "michael.farruggia@yale.edu",
            "kt2726@columbia.edu",
            "arienundomiel@gmail.com",
            "mlibunao02@gmail.com",
            "sthib631@gmail.com",
            "aodhan.hayter+lever-edge@gmail.com",
            "Labowcutt@gmail.com",
            "sm052171@gmail.com",
            "hdrugge6@gmail.com",
            "William.werner10@gmail.com",
            "cadetsantana1991@yahoo.com",
            "chris.fitzgerald@colorado.edu",
            "pleesmith@gmail.com",
            "karpas.j@gmail.com",
            "hamidc95@gmail.com",
            "twalwyn@comcast.net",
            "coppola.maria.e@gmail.com",
            "Kphong415@gmail.com",
            "usaxp1@gmail.com",
            "j.m.sedarous@gmail.com",
            "may.k.barakat@gmail.com",
            "joe.leineke@gmail.com",
            "Nurban@jd21.law.harvard.edu",
            "woodsjay514@gmail.com",
            "reywon0113@gmail.com",
            "cdustinwaters@gmail.com",
            "jtaimani@yahoo.com",
            "lblanco1029@gmail.com",
            "jessicamtzhao@gmail.com",
            "christmas961228@gmail.com",
            "blavongtheu19@students.kgi.edu",
            "regando@my.easternct.edu",
            "Jazabell09@gmail.com",
            "jealvira@gmail.com",
            "eamatusov@gmail.com",
            "tgallagher822@hotmail.com",
            "lyndia.sims@gmail.com",
            "timsykes66@gmail.com",
            "noemi.conder18@gmail.com",
            "michael.schweitzer1@gmail.com",
            "gmurphy794@gmail.com",
            "marisa.kager@gmail.com",
            "Quyanhle24@gmail.com",
            "vernon020@icloud.com",
            "ayo2022@utexas.edu",
            "Michelle.pierrot@gmail.com",
            "ashley2746@gmail.com",
            "awdoug01@gmail.com",
            "hannahklenklen@icloud.com",
            "huelskam@email.arizona.edu",
            "anniezuzu5@comcast.net",
            "Drlreed@gmail.com",
            "javaylon@Gmail.com",
            "Newuser111@gmail.com",
            "angelina2smart@gmail.com",
            "midniteboost@gmail.com",
            "devonlanay@live.com",
            "rbeatty70@gmail.com",
            "samanthacarrillo8787@gmail.com",
            "icomerford2@gmail.com",
            "brad@caffeenstudios.com",
            "stefani992@aol.com",
            "sstevens20@tamu.edu",
            "marleny.deleon@vanderbilt.edu",
            "kmarie_a@outlook.com",
            "leslielisal62@gmail.com",
            "bradenblackwell6@gmail.com",
            "sshak1@outlook.com",
            "alexandramunden@gmail.com",
            "alyson.martin@live.com",
            "ashlee.doyle@yahoo.com",
            "amberr.king8294@gmail.com",
            "KT.GIPSON@GMAIL.COM",
            "ludilyn.cayas@gmail.com",
            "zoekafkes@me.com",
        ];

        $users = User::whereNotIn('email', $alreadySentEmails)
            ->where('created_at', '>=', Carbon::yesterday()->format('Y-m-d'))
            ->whereHas('profile', function ($query) {
                return $query->where('signup_progress', UserProfile::SIGNUP_PROGRESS_COMPLETED);
            })
            ->whereHas('negotiationGroupUsers', function ($query) {
                return $query->whereNotNull('negotiation_group_id')
                    ->whereIn('negotiation_group_id', [8,9]);
            })
            ->get();

        $mailchimpAutomatedCampaigns = [
            8                                                          => 32, //Ng Id 8 should go to mailchimp automated campaign id 32
            9                                                          => 33, //Ng Id 9 should go to mailchimp automated campaign id 33,
            NegotiationGroup::NG_ELIGIBLE_FOR_GBG_HEALTH_INSURANCE     => 34, //Ng Id 22 should go to mailchimp automated campaign id 34,
            NegotiationGroup::NG_NOT_ELIGIBLE_FOR_GBG_HEALTH_INSURANCE => 35, //Ng Id 23 should go to mailchimp automated campaign id 35,
        ];

        $users->each(function ($user) use ($mailchimpAutomatedCampaigns) {
            if (! MarketingEmailUnsubscribe::where('email',$user->email)->whereReason('Unsubscribed via Mailchimp, ' . config('services.mailchimp.customer_list_id'))->exists()) {
                if ($negotiationGroupUser = $user->negotiationGroupUsers()->first()) {
                    $mailchimpAutomatedCampaignId = $mailchimpAutomatedCampaigns[$negotiationGroupUser->negotiation_group_id];

                    if (! MailchimpAutomatedCampaignUser::whereUserId($user->id)->whereMailchimpAutomatedCampaignId($mailchimpAutomatedCampaignId)->exists()) {
                        $this->addUserToMailchimpCampaign($user, $mailchimpAutomatedCampaignId);
                    }
                }
            } else {
                $this->output->comment($user->email . ' is unsubscribed');
            }
        });

        $internationalUsers = User::whereNotIn('email', $alreadySentEmails)
            ->where('created_at', '>=', Carbon::yesterday()->format('Y-m-d'))
            ->whereHas('profile', function ($query) {
                return $query->where('signup_progress', UserProfile::SIGNUP_PROGRESS_COMPLETED);
            })
            ->whereHas('negotiationGroupUsers', function ($query) {
                return $query->whereNotNull('negotiation_group_id')
                    ->whereIn('negotiation_group_id', [NegotiationGroup::NG_ELIGIBLE_FOR_GBG_HEALTH_INSURANCE,NegotiationGroup::NG_NOT_ELIGIBLE_FOR_GBG_HEALTH_INSURANCE]);
            })
            ->get();

        $internationalUsers->each(function ($user) use ($mailchimpAutomatedCampaigns) {
            if (! MarketingEmailUnsubscribe::where('email',$user->email)->whereReason('Unsubscribed via Mailchimp, ' . config('services.mailchimp.customer_list_id'))->exists()) {
                if ($user->negotiationGroupUsers->count() === 1) {
                    if ($negotiationGroupUser = $user->negotiationGroupUsers()->first()) {
                        $mailchimpAutomatedCampaignId = $mailchimpAutomatedCampaigns[$negotiationGroupUser->negotiation_group_id];
                        if (! MailchimpAutomatedCampaignUser::whereUserId($user->id)->whereMailchimpAutomatedCampaignId($mailchimpAutomatedCampaignId)->exists()) {
                            $this->addUserToMailchimpCampaign($user, $mailchimpAutomatedCampaignId);
                        }
                    }
                }
            } else {
                $this->output->comment($user->email . ' is unsubscribed');
            }
        });
    }

    private function addUserToMailchimpCampaign($user, $mailchimpAutomatedCampaignId)
    {
        $mailchimpAutomatedCampaignUser                                  = new MailchimpAutomatedCampaignUser();
        $mailchimpAutomatedCampaignUser->user_id                         = $user->id;
        $mailchimpAutomatedCampaignUser->mailchimp_automated_campaign_id = $mailchimpAutomatedCampaignId;
        $mailchimpAutomatedCampaignUser->send_date                       = Carbon::today();
        $mailchimpAutomatedCampaignUser->status                          = MailchimpAutomatedCampaignUser::STATUS_PRE_DISPATCHING;
        $mailchimpAutomatedCampaignUser->save();

        $mailchimpAutomatedCampaignUser->send();
    }
}
