<?php

use App\University;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UniversitiesTableSeeder extends Seeder
{
    public function run()
    {
        $universities = [
            'Massachusetts Institute of Technology',
            'Harvard University',
            'Stanford University',
            'University of California Berkeley',
            'University of Michigan',
            'University of Washington',
            'Cornell University',
            'Purdue University',
            'University of WisconsinMadison',
            'Columbia University in the City of New York',
            'University of California Los Angeles',
            'The University of Texas at Austin',
            'Penn State University',
            'University of Illinois at UrbanaChampaign',
            'University of Minnesota',
            'New York University',
            'University of Pennsylvania',
            'University of Southern California',
            'Carnegie Mellon University',
            'Princeton University',
            'University of California Irvine',
            'University of California San Diego',
            'Yale University',
            'Arizona State University',
            'University of Chicago',
            'University of Colorado Boulder',
            'University of North Carolina at Chapel Hill',
            'Michigan State University',
            'University of California Davis',
            'University of Florida',
            'University of Maryland',
            'Duke University',
            'Rutgers The State University of New Jersey',
            'Boston University',
            'The University of Arizona',
            'Johns Hopkins University',
            'Northwestern University',
            'University of Virginia',
            'Georgia Institute of Technology',
            'Texas AM University',
            'The University of Utah',
            'The Ohio State University',
            'North Carolina State University',
            'University of Pittsburgh',
            'Virginia Polytechnic Institute and State University',
            'University of California Santa Barbara',
            'Washington University in St Louis',
            'Iowa State University of Science and Technology',
            'Tufts University',
            'Georgia State University',
            'Indiana University Bloomington',
            'Oregon State University',
            'University of Massachusetts Amherst',
            'California Institute of Technology',
            'University of Iowa',
            'University of Georgia',
            'Brigham Young University',
            'Florida State University',
            'University of NebraskaLincoln',
            'University of Houston',
            'University of California Santa Cruz',
            'Colorado State University',
            'University of Oregon',
            'Georgetown University',
            'University of Delaware',
            'George Mason University',
            'University of South Florida',
            'University of Central Florida',
            'Vanderbilt University',
            'Brown University',
            'Washington State University',
            'George Washington University',
            'University at Buffalo State University of New York',
            'University of Rochester',
            'University of Notre Dame',
            'Rice University',
            'Dartmouth College',
            'University of Connecticut',
            'University of Kansas',
            'University of California San Francisco',
            'Emory University',
            'University of Illinois at Chicago',
            'University of California Riverside',
            'Temple University',
            'Rochester Institute of Technology',
            'University of Kentucky',
            'San Diego State University',
            'University of Missouri',
            'University of Cincinnati',
            'The University of Tennessee Knoxville',
            'University of Miami',
            'University of South Carolina',
            'University of North Texas',
            'Virginia Commonwealth University',
            'The University of Oklahoma',
            'University of New Mexico',
            'Drexel University',
            'Rensselaer Polytechnic Institute',
            'Northeastern University',
            'San Jos State University',
            'Boston College',
            'University of Vermont',
            'Louisiana State University',
            'Portland State University',
            'Florida International University',
            'The University of Texas at Dallas',
            'Case Western Reserve University',
            'California State University Fullerton',
            'California State University Northridge',
            'Kent State University',
            'San Francisco State University',
            'Clemson University',
            'University of New Hampshire',
            'Oklahoma State University',
            'Wayne State University',
            'The University of Alabama',
            'Fordham University',
            'The University of Tennessee at Martin',
            'Stony Brook University',
            'California Polytechnic State University San Luis Obispo',
            'Auburn University',
            'Loyola University Chicago',
            'Liberty University',
            'Michigan Technological University',
            'DePaul University',
            'American University',
            'Syracuse University',
            'West Virginia University',
            'Utah State University',
            'Texas Tech University',
            'Tulane University',
            'University of Maryland Baltimore County',
            'Western Michigan University',
            'Southern Methodist University',
            'Montana State University',
            'University of Arkansas',
            'The University of Texas at Arlington',
            'University of WisconsinMilwaukee',
            'University of Denver',
            'Northern Arizona University',
            'Baylor University',
            'University at Albany State University of New York',
            'Lamar University',
            'Ohio University',
            'University of Alabama at Birmingham',
            'James Madison University',
            'College of William  Mary',
            'California State University Long Beach',
            'Kansas State University',
            'University of Rhode Island',
            'Santa Clara University',
            'Brandeis University',
            'University of Idaho',
            'Northern Illinois University',
            'Grand Canyon University',
            'Florida Atlantic University',
            'Worcester Polytechnic Institute',
            'Indiana University  Purdue University Indianapolis',
            'Old Dominion University',
            'The New School',
            'Illinois Institute of Technology',
            'Mississippi State University',
            'University of North Carolina at Charlotte',
            'Southern New Hampshire University',
            'Binghamton University State University of New York',
            'University of Maryland University College',
            'Saint Louis University',
            'University of Nevada Las Vegas',
            'Texas State University',
            'University of Colorado Denver',
            'University of Nevada Reno',
            'New Mexico State University',
            'Wake Forest University',
            'California State University Sacramento',
            'California State Polytechnic University Pomona',
            'Lehigh University',
            'University of MissouriKansas City',
            'Swarthmore College',
            'Marquette University',
            'East Carolina University',
            'Carleton College',
            'Kennesaw State University',
            'Grand Valley State University',
            'University of Louisville',
            'Bowling Green State University',
            'University of Maryland Baltimore',
            'Nova Southeastern University',
            'Middlebury College',
            'Western Washington University',
            'University of Wyoming',
            'New Jersey Institute of Technology',
            'California State University Chico',
            'Appalachian State University',
            'Towson University',
            'Pace University',
            'University of Richmond',
            'Oregon Health  Science University',
            'University of San Francisco',
            'Miami University',
            'University of Mississippi',
            'Berklee College of Music',
            'Boise State University',
            'The University of Texas at San Antonio',
            'University of Massachusetts Lowell',
            'University of Dayton',
            'Villanova University',
            'EmbryRiddle Aeronautical University',
            'University of North Dakota',
            'University of Akron',
            'Ball State University',
            'Southern Illinois University Carbondale',
            'Brigham Young UniversityIdaho',
            'University of Alaska Fairbanks',
            'Central Michigan University',
            'University of Toledo',
            'The University of Texas MD Anderson Cancer Center',
            'The University of Memphis',
            'North Dakota State University',
            'University of San Diego',
            'Bucknell University',
            'Smith College',
            'Loyola Marymount University',
            'Wesleyan University',
            'University of Massachusetts Boston',
            'Calvin College',
            'The University of Maine',
            'Wright State University',
            'University of North Carolina at Greensboro',
            'Mount Holyoke College',
            'Pepperdine University',
            'Creighton University',
            'The University of Texas at El Paso',
            'University of Northern Iowa',
            'Williams College',
            'Illinois State University',
            'California State University Los Angeles',
            'Missouri University of Science and Technology',
            'California State University Fresno',
            'Western Kentucky University',
            'Chapman University',
            'Rowan University',
            'Yeshiva University',
            'Sonoma State University',
            'The University of Montana',
            'Clark University',
            'Harvey Mudd College',
            'Cleveland State University',
            'University of North Carolina Wilmington',
            'Colby College',
            'Oakland University',
            'Middle Tennessee State University',
            'Thomas Jefferson University',
            'Baylor College of Medicine',
            'Hofstra University',
            'Savannah College of Art and Design',
            'United States Air Force Academy',
            'Eastern Michigan University',
            'Seton Hall University',
            'Gonzaga University',
            'University of Nebraska at Omaha',
            'University of North Florida',
            'Humboldt State University',
            'University of MissouriSt Louis',
            'Marist College',
            'Amherst College',
            'Colorado School of Mines',
            'Florida Institute of Technology',
            'University of Southern Mississippi',
            'Missouri State University',
            'Vassar College',
            'Ithaca College',
            'Central Washington University',
            'Kenyon College',
            'Bryn Mawr College',
            'United States Military Academy',
            'University of Massachusetts Medical School',
            'University of Texas Southwestern Medical Center',
            'Wellesley College',
            'Oberlin College',
            'College of Charleston',
            'Wichita State University',
            'Medical University of South Carolina',
            'United States Naval Academy',
            'Southern Illinois University Edwardsville',
            'Idaho State University',
            'Montclair State University',
            'Texas Christian University',
            'Sam Houston State University',
            'East Tennessee State University',
            'California State University Dominguez Hills',
            'St Johns University',
            'Metropolitan State University of Denver',
            'Washington and Lee University',
            'Eastern Kentucky University',
            'Minnesota State University Mankato',
            'Rasmussen College',
            'University of California Merced',
            'The Evergreen State College',
            'Marshall University',
            'University of Colorado Colorado Springs',
            'Quinnipiac University',
            'Elon University',
            'California State University San Bernardino',
            'Babson College',
            'Biola University',
            'School of Visual Arts',
            'University of WisconsinEau Claire',
            'Howard University',
            'New Mexico Institute of Mining and Technology',
            'Bowdoin College',
            'University of Massachusetts Dartmouth',
            'Central Connecticut State University',
            'Bard College',
            'University of WisconsinStevens Point',
            'Weber State University',
            'Stevens Institute of Technology',
            'West Chester University of Pennsylvania',
            'St Olaf College',
            'The University of Alabama in Huntsville',
            'The Catholic University of America',
            'The University of Texas Health Science Center at San Antonio',
            'Georgia Southern University',
            'Purdue University Global',
            'Seattle University',
            'The University of Tulsa',
            'Indiana State University',
            'Radford University',
            'Icahn School of Medicine at Mount Sinai',
            'Earlham College',
            'Utah Valley University',
            'California State University San Marcos',
            'State University of New York at Oswego',
            'Indiana University of Pennsylvania',
            'Buffalo State College',
            'Reed College',
            'Duquesne University',
            'Ferris State University',
            'St Cloud State University',
            'College of Saint BenedictSaint Johns University',
            'University of WisconsinGreen Bay',
            'Grinnell College',
            'Webster University',
            'University of Baltimore',
            'The University of Texas Medical Branch at Galveston',
            'Lock Haven University',
            'Furman University',
            'The Rockefeller University',
            'Haverford College',
            'Augusta University',
            'Pomona College',
            'Columbia College Chicago',
            'Lewis  Clark College',
            'Bentley University',
            'Eastern Illinois University',
            'The University of Texas Health Science Center at Houston',
            'Dickinson College',
            'Fashion Institute of Technology',
            'Stetson University',
            'Colgate University',
            'Western Illinois University',
            'Valencia College',
            'Medical College of Wisconsin',
            'Clarkson University',
            'Florida Gulf Coast University',
            'University of Arkansas at Little Rock',
            'Simmons University',
            'University of West Florida',
            'Suffolk University',
            'DeVry University',
            'Bates College',
            'University of Nebraska Medical Center',
            'Northern Michigan University',
            'Eastern Washington University',
            'The College of New Jersey',
            'Pratt Institute',
            'Stephen F Austin State University',
            'University of WisconsinWhitewater',
            'Hobart and William Smith Colleges',
            'Davidson College',
            'Rhode Island School of Design',
            'Purdue University Fort Wayne',
            'Butler University',
            'University of Louisiana at Lafayette',
            'Trinity College',
            'Bradley University',
            'University of Northern Colorado',
            'University of South Dakota',
            'University of WisconsinStout',
            'University of Texas Rio Grande Valley',
            'University of Hartford',
            'Loyola University Maryland',
            'Loma Linda University',
            'Macalester College',
            'California State University Stanislaus',
            'Whitman College',
            'Trinity University',
            'Hamilton College',
            'California State University East Bay',
            'Arkansas State University',
            'Northern Kentucky University',
            'Gallaudet University',
            'University of WisconsinLa Crosse',
            'Long Island University',
            'Shippensburg University of Pennsylvania',
            'University of the Pacific',
            'University of West Georgia',
            'Louisiana Tech University',
            'Colorado College',
            'Academy of Art University',
            'State University of New York at New Paltz',
            'Wheaton College',
            'Drew University',
            'Emerson College',
            'Concordia University Oregon',
            'Union College',
            'Kean University',
            'Azusa Pacific University',
            'University of WisconsinOshkosh',
            'Gettysburg College',
            'Connecticut College',
            'Skidmore College',
            'Andrews University',
            'University of Central Arkansas',
            'Monmouth University',
            'Regent University',
            'Fairleigh Dickinson University',
            'Hanover College',
            'Lafayette College',
            'Hult International Business School',
            'Tennessee Tech University',
            'Western Oregon University',
            'University of Evansville',
            'Johnson and Wales University',
            'The Juilliard School',
            'Adelphi University',
            'Bridgewater State University',
            'The University of Tennessee at Chattanooga',
            'California Institute of the Arts',
            'Fort Hays State University',
            'Valparaiso University',
            'Barnard College',
            'University of New Orleans',
            'University of Illinois at Springfield',
            'Truman State University',
            'University of South Alabama',
            'Pacific University',
            'Hillsdale College',
            'Miami Dade College',
            'Champlain College',
            'Loyola University New Orleans',
            'University of New England',
            'Hampshire College',
            'New York Institute of Technology',
            'Regis University',
            'Saint Josephs University',
            'College of the Holy Cross',
            'Naval Postgraduate School',
            'University of New Haven',
            'Mercer University',
            'The Cooper Union for the Advancement of Science and Art',
            'Strayer University',
            'SUNY Geneseo',
            'DePauw University',
            'ArtCenter College of Design',
            'Stockton University',
            'RoseHulman Institute of Technology',
            'Texas AM UniversityCorpus Christi',
            'Emporia State University',
            'Rollins College',
            'West Texas AM University',
            'Willamette University',
            'Seattle Pacific University',
            'Texas Tech University Health Sciences Center',
            'Southeast Missouri State University',
            'Sacred Heart University',
            'School of the Art Institute of Chicago',
            'Franklin and Marshall College',
            'Drake University',
            'National University',
            'University of MichiganFlint',
            'Widener University',
            'Valdosta State University',
            'Texas Womans University',
            'Occidental College',
            'SUNY College of Environmental Science and Forestry',
            'SUNY Upstate Medical University',
            'Plymouth State University',
            'University of Detroit Mercy',
            'Western Carolina University',
            'The Culinary Institute of America',
            'Belmont University',
            'Milwaukee School of Engineering',
            'Touro College',
            'University of Hawaii at Manoa',
            'University of North Carolina at Asheville',
            'Samford University',
            'Uniformed Services University of the Health Sciences',
            'University of Puget Sound',
            'Cedarville University',
            'California State University Bakersfield',
            'Hope College',
            'North Carolina Agricultural and Technical State University',
            'University of Central Oklahoma',
            'SUNY College at Oneonta',
            'SUNY Empire State College',
            'Xavier University',
            'St Edwards University',
            'SUNY Cortland',
            'Angelo State University',
            'Bloomsburg University of Pennsylvania',
            'Pitzer College',
            'Youngstown State University',
            'Troy University',
            'Bellevue College',
            'California State University Channel Islands',
            'University of WisconsinPlatteville',
            'The University of Oklahoma Health Sciences Center',
            'William Paterson University',
            'Rider University',
            'Frostburg State University',
            'Southeastern Louisiana University',
            'Northeastern Illinois University',
            'Pacific Lutheran University',
            'Antioch University',
            'South Dakota State University',
            'Rhode Island College',
            'Fairfield University',
            'University of Arkansas for Medical Sciences',
            'Abilene Christian University',
            'Minnesota State University Moorhead',
            'North Carolina Central University',
            'Texas AM UniversityCommerce',
            'Louisiana State University Health Sciences Center',
            'University of Mary Washington',
            'Saint Marys College of California',
            'Broward College',
            'The State University of New York at Potsdam',
            'McDaniel College',
            'Claremont Graduate University',
            'The College of Wooster',
            'Le Moyne College',
            'St Lawrence University',
            'St Petersburg College',
            'Winthrop University',
            'Gordon College',
            'University of Portland',
            'Lawrence University',
            'Ramapo College of New Jersey',
            'Millersville University of Pennsylvania',
            'Claremont McKenna College',
            'Florida Agricultural and Mechanical University',
            'Hamline University',
            'Longwood University',
            'University of Scranton',
            'High Point University',
            'Denison University',
            'University of North Georgia',
            'George Fox University',
            'Beloit College',
            'Colorado Technical University',
            'California State University Monterey Bay',
            'Salem State University',
            'College of Southern Nevada',
            'Maharishi University of Management',
            'Maryville University',
            'University of California Hastings College of the Law',
            'Augsburg College',
            'Murray State University',
            'Roosevelt University',
            'Goucher College',
            'Bluffton University',
            'Sweet Briar College',
            'SUNY Downstate Medical Center',
            'Lesley University',
            'Kutztown University of Pennsylvania',
            'Agnes Scott College',
            'Ashland University',
            'Baker College',
            'Indiana Wesleyan University',
            'Southern Utah University',
            'California College of the Arts',
            'Campbell University',
            'Seton Hill University',
            'Elmhurst College',
            'Gustavus Adolphus College',
            'Rhodes College',
            'The College at Brockport',
            'Austin Peay State University',
            'Kettering University',
            'Salisbury University',
            'Augustana College',
            'University of Southern Indiana',
            'Norwich University',
            'Wabash College',
            'Georgia College and State University',
            'CarsonNewman University',
            'Sewanee The University of the South',
            'Capital University',
            'Bethel University',
            'Saint Michaels College',
            'Chicago State University',
            'University of HoustonClear Lake',
            'University of Bridgeport',
            'St Catherine University',
            'The Citadel The Military College of South Carolina',
            'SUNY Polytechnic Institute',
            'Christopher Newport University',
            'State University of New York College at Plattsburgh',
            'Arcadia University',
            'Harding University',
            'Sarah Lawrence College',
            'The University of Tampa',
            'Pittsburg State University',
            'Roger Williams University',
            'Slippery Rock University of Pennsylvania',
            'Alfred University',
            'Barry University',
            'Southern Connecticut State University',
            'Lewis University',
            'Maryland Institute College of Art',
            'Illinois Wesleyan University',
            'Goshen College',
            'Jacksonville State University',
            'University of Nebraska at Kearney',
            'California Lutheran University',
            'The College of St Scholastica',
            'Berea College',
            'Columbia College',
            'Messiah College',
            'Coastal Carolina University',
            'Texas AM UniversityKingsville',
            'Ohio Northern University',
            'Southern Oregon University',
            'Siena College',
            'National Defense University',
            'Mississippi College',
            'Tarleton State University',
            'Luther College',
            'Bryant University',
            'Tennessee State University',
            'Dakota State University',
            'Winona State University',
            'Canisius College',
            'Bastyr University',
            'Saint Anselm College',
            'Southwestern University',
            'Kalamazoo College',
            'Berry College',
            'Wilkes University',
            'Lawrence Technological University',
            'State University of New York at Fredonia',
            'Oregon Institute of Technology',
            'Harrisburg University of Science and Technology',
            'New Jersey City University',
            'Morgan State University',
            'Eastern New Mexico University',
            'Western Connecticut State University',
            'University of WisconsinRiver Falls',
            'Purchase College State University of New York',
            'Saginaw Valley State University',
            'Albion College',
            'Carthage College',
            'Ohio Wesleyan University',
            'La Salle University',
            'University of Southern Maine',
            'Providence College',
            'The University of Tennessee Health Science Center',
            'Utica College',
            'Western University of Health Sciences',
            'Washburn University',
            'The University of Texas at Tyler',
            'Saint Marys University of Minnesota',
            'Santa Fe College',
            'Fort Lewis College',
            'University of North Carolina at Pembroke',
            'Bellevue University',
            'Dominican University of California',
            'Baldwin Wallace University',
            'Franklin University',
            'St Bonaventure University',
            'Northwest Missouri State University',
            'Pennsylvania College of Technology',
            'University of Central Missouri',
            'AT Still University',
            'Arkansas Tech University',
            'Columbus State University',
            'Wentworth Institute of Technology',
            'Morehead State University',
            'Elizabethtown College',
            'Midwestern University',
            'Marietta College',
            'Olivet Nazarene University',
            'Lipscomb University',
            'Keene State College',
            'University of Louisiana at Monroe',
            'Palm Beach State College',
            'South University',
            'Golden Gate University',
            'Governors State University',
            'California Institute of Integral Studies',
            'Morehouse College',
            'Lake Superior State University',
            'University of North Alabama',
            'Hawaii Pacific University',
            'Texas Southern University',
            'Spelman College',
            'Saint Leo University',
            'University of Redlands',
            'University of La Verne',
            'Eckerd College',
            'The University of Findlay',
            'Seminole State College of Florida',
            'North Central College',
            'Lander University',
            'Farmingdale State College',
            'University of Mississippi Medical Center',
            'Keck Graduate Institute',
            'Drury University',
            'Florida State College at Jacksonville',
            'Benedictine University',
            'Mills College',
            'South Dakota School of Mines and Technology',
            'University of WisconsinParkside',
            'Fresno Pacific University',
            'Knox College',
            'Wofford College',
            'Concordia University Wisconsin',
            'Northwest Nazarene University',
            'University of Indianapolis',
            'Clayton State University',
            'Oklahoma City University',
            'Muhlenberg College',
            'Texas AM International University',
            'Dallas Baptist University',
            'Virginia Military Institute',
            'Penn State College of Medicine',
            'Wilmington University',
            'John Carroll University',
            'Hendrix College',
            'York College of Pennsylvania',
            'Hood College',
            'Northern State University',
            'Westmont College',
            'St John Fisher College',
            'Chatham University',
            'Susquehanna University',
            'Niagara University',
            'Jacksonville University',
            'Colorado Mesa University',
            'North Park University',
            'University of the District of Columbia',
            'Alvernia University',
            'Delaware State University',
            'Clarion University of Pennsylvania',
            'St Norbert College',
            'Northwestern State University of Louisiana',
            'Massachusetts College of Art and Design',
            'Bellarmine University',
            'Northwood University',
            'Ringling College of Art and Design',
            'Argosy University',
            'California Baptist University',
            'Dixie State University',
            'University of Dallas',
            'Eastern Mennonite University',
            'Linfield College',
            'Centre College',
            'Otis College of Art and Design',
            'Assumption College',
            'Naropa University',
            'Northeastern State University',
            'Park University',
            'Roanoke College',
            'Davenport University',
            'Washington College',
            'Ursinus College',
            'St Marys University',
            'Purdue University Northwest',
            'Manhattan College',
            'Tuskegee University',
            'Prairie View AM University',
            'University of HoustonDowntown',
            'Hampton University',
            'Walsh University',
            'Rush University',
            'Westminster College',
            'Robert Morris University',
            'Bennington College',
            'Lindenwood University',
            'Aurora University',
            'The College of Saint Rose',
            'Concordia University St Paul',
            'Bob Jones University',
            'Eastern Virginia Medical School',
            'Merrimack College',
            'Stonehill College',
            'The University of the Arts',
            'Southern Adventist University',
            'Juniata College',
            'Augustana University',
            'Saint Ambrose University',
            'SIT Graduate Institute',
            'National Louis University',
            'Lebanon Valley College',
            'Wittenberg University',
            'Alliant International University',
            'University of WisconsinSuperior',
            'Edinboro University of Pennsylvania',
            'Lake Forest College',
            'Albany Medical College',
            'Kentucky State University',
            'St Thomas University',
            'Colorado Christian University',
            'Brooklyn Law School',
            'Cornell College',
            'University of the Incarnate Word',
            'Grove City College',
            'Montana Tech',
            'Hiram College',
            'St Marys College of Maryland',
            'Xavier University of Louisiana',
            'University of the Ozarks',
            'St Johns College',
            'Iona College',
            'New York Law School',
            'Franklin W Olin College of Engineering',
            'Shenandoah University',
            'Lynchburg College',
            'Jackson State University',
            'Worcester State University',
            'Dominican University',
            'Lehman College CUNY',
            'Allegheny College',
            'Seattle Central College',
            'Otterbein University',
            'Mercyhurst University',
            'Austin College',
            'Concordia College',
            'Flagler College',
            'Christian Brothers University',
            'Brigham Young UniversityHawaii',
            'McNeese State University',
            'The John Marshall Law School',
            'Taylor University',
            'The Sage Colleges',
            'Marymount University',
            'Wheeling Jesuit University',
            'Minneapolis College of Art and Design',
            'Fayetteville State University',
            'Indiana University Northwest',
            'Oklahoma Christian University',
            'Auburn University at Montgomery',
            'East Stroudsburg University',
            'Vermont Law School',
            'Concordia University Irvine',
            'Oral Roberts University',
            'DYouville College',
            'Point Park University',
            'Whittier College',
            'Springfield College',
            'Point Loma Nazarene University',
            'Lincoln Memorial University',
            'Western State Colorado University',
            'Bemidji State University',
            'LewisClark State College',
            'Union University',
            'Kings College',
            'Western New England University',
            'Cornerstone University',
            'Southern Nazarene University',
            'Mercy College',
            'Eastern University',
            'Eastern Connecticut State University',
            'Scripps College',
            'Edgewood College',
            'Simpson College',
            'Trinity International University',
            'University of St Francis',
            'California State University Maritime Academy',
            'DeSales University',
            'Hartwick College',
            'Clark Atlanta University',
            'Queens University of Charlotte',
            'San Francisco Art Institute',
            'Muskingum University',
            'Alma College',
            'Wheaton College Massachusetts',
            'Wartburg College',
            'LeTourneau University',
            'Guilford College',
            'Manhattanville College',
            'University of Maryland Eastern Shore',
            'Eastern Oregon University',
            'Hunter College CUNY',
            'WinstonSalem State University',
            'Berkeley College',
            'Saint Xavier University',
            'Nazareth College',
            'College for Creative Studies',
            'Saint Marys College',
            'New College of Florida',
            'La Sierra University',
            'Alabama AM University',
            'Daytona State College',
            'Brenau University',
            'University of Northwestern  St Paul',
            'Louisiana State University in Shreveport',
            'MCPHS University',
            'Regis College',
            'University of North Texas Health Science Center',
            'Vanguard University of Southern California',
            'Brandman University',
            'Saint Martins University',
            'Spring Arbor University',
            'Florida Southern College',
            'New England Conservatory',
            'Coe College',
            'University of Mary HardinBaylor',
            'United States Merchant Marine Academy',
            'Walla Walla University',
            'New York Medical College',
            'Salve Regina University',
            'Endicott College',
            'University of the Cumberlands',
            'Indiana University Southeast',
            'Manhattan School of Music',
            'Millikin University',
            'Concordia University Chicago',
            'Husson University',
            'Moody Bible Institute',
            'Alfred State College',
            'Houston Baptist University',
            'Morningside College',
            'Rogers State University',
            'Dordt College',
            'Lynn University',
            'Montana State University Billings',
            'John Brown University',
            'Georgetown College',
            'Daemen College',
            'Adams State University',
            'ECPI University',
            'Indiana University South Bend',
            'Alabama State University',
            'Carroll College',
            'Stevenson University',
            'Lycoming College',
            'GardnerWebb University',
            'Bowie State University',
            'Southeastern University',
            'The University of Texas of the Permian Basin',
            'Mississippi University for Women',
            'University of MichiganDearborn',
            'Gannon University',
            'New England College',
            'Oglethorpe University',
            'Norfolk State University',
            'Carroll University',
            'HampdenSydney College',
            'University of North Carolina School of the Arts',
            'Southern University and AM College',
            'Moravian College',
            'Missouri Western State University',
            'University of Maine at Augusta',
            'Life University',
            'City University of Seattle',
            'Marian University',
            'Samuel Merritt University',
            'Virginia State University',
            'Westminster College Pennsylvania',
            'Pennsylvania Academy of the Fine Arts',
            'Aquinas College',
            'Rosalind Franklin University of Medicine and Science',
            'Framingham State University',
            'Vincennes University',
            'University of South CarolinaUpstate',
            'Southwest Minnesota State University',
            'Marywood University',
            'Nicholls State University',
            'Western New Mexico University',
            'Boston Architectural College',
            'Morrisville State College',
            'Bridgewater College',
            'Mount St Marys University',
            'Warren Wilson College',
            'Ouachita Baptist University',
            'Mount Saint Mary College',
            'Hollins University',
            'Palm Beach Atlantic University',
            'Whitworth University',
            'Midwestern State University',
            'Prescott College',
            'Cameron University',
            'Alverno College',
            'Alcorn State University',
            'Spring Hill College',
            'University of Hawaii at Hilo',
            'Shepherd University',
            'Francis Marion University',
            'Delta State University',
            'Emmanuel College',
            'Washington  Jefferson College',
            'Misericordia University',
            'College of the Atlantic',
            'Pacific Union College',
            'Southern Arkansas University',
            'Heidelberg University',
            'New England Institute of Technology',
            'North Carolina Wesleyan College',
            'Curry College',
            'Mitchell Hamline School of Law',
            'University of West Alabama',
            'Trinity Washington University',
            'Southern California Institute of Architecture',
            'Charleston Southern University',
            'St Augustines University',
            'Upper Iowa University',
            'Evangel University',
            'Middle Georgia State University',
            'Delaware Valley University',
            'Manchester University',
            'Southwestern College',
            'Sterling College',
            'Black Hills State University',
            'Nebraska Wesleyan University',
            'Chadron State College',
            'Northern Vermont University',
            'Montreat College',
            'Gwynedd Mercy University',
            'Elizabeth City State University',
            'Doane University',
            'Greenville University',
            'Centenary College of Louisiana',
            'Concordia University Texas',
            'Anderson University Indiana',
            'South Texas College of Law',
            'Morehouse School of Medicine',
            'Fitchburg State University',
            'University of the Sciences in Philadelphia',
            'Henderson State University',
            'The American College of Financial Services',
            'Baker University',
            'Metropolitan State University',
            'McKendree University',
            'Saint Vincent College',
            'University of St Augustine for Health Sciences',
            'Graceland University',
            'Curtis Institute of Music',
            'Central College',
            'New Mexico Highlands University',
            'Buena Vista University',
            'Lincoln University',
            'Mount St Joseph University',
            'Dominican College',
            'Wagner College',
            'Missouri Southern State University',
            'Colorado State UniversityPueblo',
            'Columbus College of Art and Design',
            'Geneva College',
            'Transylvania University',
            'The College of New Rochelle',
            'Chamberlain University',
            'Green Mountain College',
            'Ripon College',
            'Ottawa University',
            'Southwestern Law School',
            'SUNY Canton',
            'Clarke University',
            'Wayne State College',
            'Fisk University',
            'Elmira College',
            'Campbellsville University',
            'Grace College',
            'Keiser University',
            'Rivier University',
            'Viterbo University',
            'South Texas College',
            'Texas AM University at Galveston',
            'Notre Dame of Maryland University',
            'Georgian Court University',
            'Molloy College',
            'Asbury University',
            'University of HoustonVictoria',
            'University of Montevallo',
            'Herzing University',
            'HardinSimmons University',
            'Northwestern College',
            'South Carolina State University',
            'Lakeland College',
            'Des Moines University',
            'Presbyterian College',
            'West Virginia State University',
            'Wisconsin Lutheran College',
            'Mary Baldwin University',
            'Concordia University Nebraska',
            'Lasell College',
            'SUNY Delhi',
            'Quincy University',
            'University of Mount Union',
            'BirminghamSouthern College',
            'John F Kennedy University',
            'Meredith College',
            'Roberts Wesleyan College',
            'Cornish College of the Arts',
            'University of St Thomas',
            'Lee University',
            'University of Mary',
            'St Louis College of Pharmacy',
            'California University of Pennsylvania',
            'King University',
            'Minot State University',
            'SUNY Maritime College',
            'State College of FloridaManateeSarasota',
            'University of South CarolinaAiken',
            'University of Arkansas  Fort Smith',
            'Cedar Crest College',
            'National University of Health Sciences',
            'University of Dubuque',
            'MGH Institute of Health Professions',
            'East Central University',
            'National American University',
            'Rockhurst University',
            'Pacific Northwest College of Art',
            'Athens State University',
            'New England Law  Boston',
            'Friends University',
            'Saint Peters University',
            'Bard College at Simons Rock',
            'Mount Mercy University',
            'Kansas City University of Medicine and Biosciences',
            'Bloomfield College',
            'Southwestern Oklahoma State University',
            'Northwest University',
            'Soka University of America',
            'American International College',
            'Georgia Southwestern State University',
            'The Masters University',
            'College of the Ozarks',
            'Georgia Gwinnett College',
            'Southeastern Oklahoma State University',
            'Southwestern Adventist University',
            'Belmont Abbey College',
            'Albany State University',
            'Chaminade University of Honolulu',
            'Massachusetts College of Liberal Arts',
            'Loras College',
            'Bank Street College of Education',
            'BethuneCookman University',
            'Pfeiffer University',
            'Marlboro College',
            'Great Basin College',
            'Briar Cliff University',
            'Polk State College',
            'Fairmont State University',
            'Houghton College',
            'Thomas College',
            'Immaculata University',
            'University of Advancing Technology',
            'Unity College',
            'Cardinal Stritch University',
            'The Chicago School of Professional Psychology',
            'Concordia CollegeNew York',
            'Monroe College',
            'Concord University',
            'Malone University',
            'Lyon College',
            'Missouri Baptist University',
            'Bethel CollegeIndiana',
            'Saint Francis University',
            'Oklahoma Baptist University',
            'Sullivan University',
            'Bethel College',
            'Faulkner University',
            'Shawnee State University',
            'Adrian College',
            'Dalton State College',
            'Neumann University',
            'Grambling State University',
            'William Carey University',
            'Fielding Graduate University',
            'Huntingdon College',
            'Cambridge College',
            'University of Sioux Falls',
            'Cabrini University',
            'University of Charleston',
            'Converse College',
            'West Coast UniversityLos Angeles',
            'Bay Path University',
            'San Francisco Conservatory of Music',
            'Caldwell University',
            'Central Penn College',
            'Benedictine College',
            'Newman University',
            'Baruch College CUNY',
            'Brooklyn College',
            'Holy Names University',
            'SUNY College at Old Westbury',
            'Savannah State University',
            'Emory  Henry College',
            'Northland College',
            'Mansfield University of Pennsylvania',
            'Notre Dame de Namur University',
            'University of Arkansas at Monticello',
            'Lincoln University Missouri',
            'Fontbonne University',
            'Averett University',
            'Becker College',
            'Rocky Mountain College of Art and Design',
            'Johnson C Smith University',
            'Millsaps College',
            'Capitol Technology University',
            'The Graduate Center CUNY',
            'ColbySawyer College',
            'Wesley College',
            'Woodbury University',
            'Our Lady of the Lake University',
            'Saint Josephs College of Maine',
            'Ave Maria University',
            'Trevecca Nazarene University',
            'Wayland Baptist University',
            'Maine College of Art',
            'Spalding University',
            'Indiana Institute of Technology',
            'Nyack College',
            'Goddard College',
            'Cleveland Institute of Music',
            'Post University',
            'Sul Ross State University',
            'Oakwood University',
            'Kendall College',
            'Shorter University',
            'Belhaven University',
            'Cleveland Institute of Art',
            'Rocky Mountain College',
            'Marygrove College',
            'Massachusetts Maritime Academy',
            'Trinity Christian College',
            'Dean College',
            'Huntington University',
            'Lancaster Bible College',
            'Columbia International University',
            'Western Nevada College',
            'Franklin Pierce University',
            'Logan University',
            'LenoirRhyne University',
            'Charles R Drew University of Medicine and Science',
            'United States Coast Guard Academy',
            'College of Central Florida',
            'Adler University',
            'Stephens College',
            'College of Saint Elizabeth',
            'Trine University',
            'Langston University',
            'Chestnut Hill College',
            'Texas Wesleyan University',
            'Thomas Edison State University',
            'Wingate University',
            'Ferrum College',
            'Columbia Basin College',
            'Franciscan University of Steubenville',
            'Dillard University',
            'NewSchool of Architecture and Design',
            'Tusculum College',
            'Holy Family University',
            'Methodist University',
            'SUNY Cobleskill',
            'Salem College',
            'Alaska Pacific University',
            'Wells College',
            'Maryville College',
            'Coppin State University',
            'Eastern Nazarene College',
            'Cogswell Polytechnical College',
            'Mount Vernon Nazarene University',
            'Pine Manor College',
            'Marylhurst University',
            'Bennett College',
            'Grand View University',
            'Bryan College',
            'Texas Lutheran University',
            'Rosemont College',
            'Tougaloo College',
            'Paul Smiths College',
            'Dakota Wesleyan University',
            'Felician University',
            'Texas AM UniversityTexarkana',
            'La Roche University',
            'Gulf Coast State College',
            'Piedmont College',
            'Medaille College',
            'Robert Morris University Illinois',
            'Moore College of Art and Design',
            'Madonna University',
            'Reinhardt University',
            'Tabor College',
            'St Francis College',
            'Southwestern Assemblies of God University',
            'Snow College',
            'RandolphMacon College',
            'Keuka College',
            'Saint MaryoftheWoods College',
            'Walsh College',
            'Kansas City Art Institute',
            'Thomas Aquinas College',
            'Fort Valley State University',
            'Vermont Technical College',
            'East Georgia State College',
            'Albright College',
            'Mars Hill University',
            'Rockford University',
            'Central State University',
            'MidAmerica Nazarene University',
            'McMurry University',
            'FreedHardeman University',
            'Northwestern Health Sciences University',
            'Wilmington College',
            'Hodges University',
            'Thomas More College',
            'Waldorf University',
            'Illinois College',
            'Bryant and Stratton College',
            'Lindsey Wilson College',
            'Tiffin University',
            'LeesMcRae College',
            'Wilson College',
            'Howard Payne University',
            'Warner Pacific College',
            'Carlow University',
            'The University of Virginias College at Wise',
            'Sierra Nevada College',
            'Mayville State University',
            'Ohio Dominican University',
            'Milligan College',
            'Midway University',
            'Hastings College',
            'Columbia CollegeHollywood',
            'East Texas Baptist University',
            'Waynesburg University',
            'LIM College',
            'Lubbock Christian University',
            'Landmark College',
            'Crown College',
            'Abraham Baldwin Agricultural College',
            'Covenant College',
            'Claflin University',
            'St Josephs College',
            'Notre Dame College',
            'Castleton University',
            'Indian River State College',
            'Southwest Baptist University',
            'Nichols College',
            'Heritage University',
            'Mount Mary University',
            'West Virginia Wesleyan College',
            'College of Our Lady of the Elms',
            'American Jewish University',
            'Lake Washington Institute of Technology',
            'Marymount Manhattan College',
            'North Greenville University',
            'Anna Maria College',
            'Limestone College',
            'William James College',
            'Randolph College',
            'Rochester College',
            'Louisiana College',
            'Meharry Medical College',
            'Cazenovia College',
            'Midland College',
            'Oklahoma Wesleyan University',
            'Franklin College',
            'Paine College',
            'Milwaukee Institute of Art  Design',
            'Albany Law School',
            'Dunwoody College of Technology',
            'William Jessup University',
            'Maine Maritime Academy',
            'Hope International University',
            'University of Northwestern Ohio',
            'California Western School of Law',
            'Maryland University of Integrative Health',
            'Siena Heights University',
            'Anderson University',
            'Mississippi Valley State University',
            'United States Sports Academy',
            'Northwest Florida State College',
            'Florida SouthWestern State College',
            'The Institute of World Politics',
            'Corban University',
            'Brevard College',
            'Mount Aloysius College',
            'Brescia University',
            'Pacifica Graduate Institute',
            'Virginia Union University',
            'The College of Idaho',
            'Pensacola State College',
            'Granite State College',
            'Goodwin College',
            'Cheyney University of Pennsylvania',
            'Valley City State University',
            'Nebraska Methodist College',
            'William Woods University',
            'Southern Wesleyan University',
            'University of Pikeville',
            'Avila University',
            'Judson University',
            'Bismarck State College',
            'Albertus Magnus College',
            'Newberry College',
            'West Liberty University',
            'Centralia College',
            'Kansas Wesleyan University',
            'Peru State College',
            'University of Mobile',
            'College of Mount Saint Vincent',
            'Bethany Lutheran College',
            'Northeast Ohio Medical University',
            'Catawba College',
            'Olivet College',
            'Cumberland University',
            'North Central University',
            'Thomas Jefferson School of Law',
            'Defiance College',
            'Keystone College',
            'Albany College of Pharmacy and Health Sciences',
            'University of Arkansas at Pine Bluff',
            'Montana State UniversityNorthern',
            'Brown Mackie College',
            'William Penn University',
            'McPherson College',
            'Benjamin Franklin Institute of Technology',
            'University of Jamestown',
            'Lourdes University',
            'Coker College',
            'Eureka College',
            'Thiel College',
            'The City College of New York',
            'SUNY College of Optometry',
            'Finlandia University',
            'South College',
            'Multnomah University',
            'Southern University at New Orleans',
            'LaGrange College',
            'The University of Texas Health Science Center at Tyler',
            'University of Rio Grande',
            'Missouri Valley College',
            'Wesleyan College',
            'Virginia Wesleyan University',
            'Shaw University',
            'Piedmont International University',
            'Air Force Institute of Technology',
            'Brazosport College',
            'Union College Nebraska',
            'University of Saint Joseph',
            'College of Saint Mary',
            'University of South CarolinaBeaufort',
            'Schiller International University',
            'Ohio Christian University',
            'Kentucky Wesleyan College',
            'Cranbrook Academy of Art',
            'Edward Waters College',
            'Urbana University',
            'Bluefield College',
            'Northwestern Oklahoma State University',
            'St Thomas Aquinas College',
            'Parker University',
            'Mount Marty College',
            'Florida Memorial University',
            'Union College Kentucky',
            'Concordia University Ann Arbor',
            'Monmouth College',
            'University of Maine at Fort Kent',
            'Erskine College',
            'Oklahoma Panhandle State University',
            'Central Methodist University',
            'Principia College',
            'HustonTillotson University',
            'Maranatha Baptist University',
            'Amberton University',
            'Clarkson College',
            'West Virginia University at Parkersburg',
            'John Jay College of Criminal Justice',
            'Alderson Broaddus University',
            'University of Saint Francis',
            'Newbury College',
            'Martin Luther College',
            'MacMurray College',
            'Fisher College',
            'Salus University',
            'Toccoa Falls College',
            'CulverStockton College',
            'Bethany College',
            'Louisiana State University of Alexandria',
            'Young Harris College',
            'Bethany College Kansas',
            'William Jewell College',
            'Florida National University',
            'Alice Lloyd College',
            'Arkansas Baptist College',
            'Cairn University',
            'Bay State College',
            'Gordon State College',
            'West Virginia School of Osteopathic Medicine',
            'Blackburn College',
            'Westminster College Missouri',
            'Hilbert College',
            'Calumet College of St Joseph',
            'Hebrew College',
            'Marian University Wisconsin',
            'Nazarene Bible College',
            'Johnson University',
            'Dickinson State University',
            'Louisiana State University Health Sciences CenterShreveport',
            'York College',
            'HannibalLaGrange University',
            'Beacon College',
            'William Peace University',
            'Barton College',
            'Schreiner University',
            'Holy Cross College',
            'Voorhees College',
            'Boston Graduate School of Psychoanalysis',
            'University of Saint Mary',
            'Roseman University of Health Sciences',
            'New England College of Optometry',
            'Southern College of Optometry',
            'Saint Johns River State College',
            'West Virginia University Institute of Technology',
            'Southern Vermont College',
            'Chipola College',
            'Art Academy of Cincinnati',
            'Vaughn College of Aeronautics and Technology',
            'Mitchell College',
            'University of Mount Olive',
            'Wiley College',
            'Centenary University',
            'Central Christian College of Kansas',
            'Oakland City University',
            'Point University',
            'Simpson University',
            'University of Alaska Anchorage',
            'Menlo College',
            'Queens College City University of New York',
            'Cleveland UniversityKansas City',
            'Metropolitan College of New York',
            'University of Valley Forge',
            'Southern Virginia University',
            'Palo Alto University',
            'University of Maine at Presque Isle',
            'GoldeyBeacom College',
            'Wilberforce University',
            'Saybrook University',
            'Judson College',
            'Ursuline College',
            'Jefferson College of Health Sciences',
            'MidAmerica Christian University',
            'Marshall B Ketchum University',
            'Bluefield State College',
            'Memphis College of Art',
            'Indiana University East',
            'University of Science and Arts of Oklahoma',
            'Faith Baptist Bible College and Theological Seminary',
            'Adler Graduate School',
            'Emmaus Bible College',
            'University of Providence',
            'Central Baptist College',
            'LeMoyneOwen College',
            'Emmanuel College Georgia',
            'Montserrat College of Art',
            'Peirce College',
            'Silver Lake College of the Holy Family',
            'Touro University California',
            'Warner University',
            'Mount Ida College',
            'Glenville State College',
            'College of Coastal Georgia',
            'Cincinnati Christian University',
            'San Diego Christian College',
            'Lincoln Christian University',
            'Columbia College South Carolina',
            'Rocky Vista University',
            'Thomas University',
            'Sterling College Vermont',
            'Lane College',
            'Jarvis Christian College',
            'AdventHealth University',
            'Lake Erie College',
            'Criswell College',
            'Livingstone College',
            'York College City University of New York',
            'Morris College',
            'The Kings College',
            'New York School of Interior Design',
            'Miles College',
            'Appalachian College of Pharmacy',
            'Ozark Christian College',
            'Manhattan Christian College',
            'Texas College',
            'HarrisStowe State University',
            'Union Institute  University',
            'Clarks Summit University',
            'New York College of Podiatric Medicine',
            'Western State College of Law at Argosy University',
            'Bethel University Tennessee',
            'Thomas More College of Liberal Arts',
            'Lincoln University California',
            'BarnesJewish College Goldfarb School of Nursing',
            'Blue Mountain College',
            'Cottey College',
            'College of St Joseph',
            'Midland University',
            'Florida College',
            'Allen University',
            'Ohio Valley University',
            'Pardee RAND Graduate School',
            'Holy Apostles College and Seminary',
            'University of HawaiiWest Oahu',
            'Humphreys University',
            'Mount Saint Marys University',
            'Aquinas College Tennessee',
            'Villa Maria College',
            'Central Christian College of the Bible',
            'Pennsylvania College of Art and Design',
            'Grace University',
            'Kentucky Christian University',
            'Mount Carmel College of Nursing',
            'Northern New Mexico College',
            'Grace Christian University',
            'The School of Architecture at Taliesin',
            'Southern University Law Center',
            'Appalachian Bible College',
            'Trocaire College',
            'Barclay College',
            'Indiana University Kokomo',
            'Davis  Elkins College',
            'Benedict College',
            'Presentation College',
            'Washington Adventist University',
            'Truett McConnell University',
            'Martin Methodist College',
            'Atlanta Metropolitan State College',
            'Rust College',
            'Dallas Christian College',
            'Kettering College',
            'University of Western States',
            'Dominican School of Philosophy  Theology',
            'University of the West',
            'Lincoln College',
            'Paul Quinn College',
            'Oregon College of Art and Craft',
            'Bryn Athyn College',
            'Massachusetts School of Law',
            'VanderCook College of Music',
            'Relay Graduate School of Education',
            'New York Academy of Art',
            'Greensboro College',
            'Bacone College',
            'The University of Montana Western',
            'University of the Southwest',
            'Talladega College',
            'Arizona Christian University',
            'Watkins College of Art Design  Film',
            'Webber International University',
            'Mercy College of Ohio',
            'St Andrews University',
            'The Baptist College of Florida',
            'Baptist Memorial College of Health Sciences',
            'Oak Hills Christian College',
            'Salem International University',
            'Calvary University',
            'Northwest Christian University',
            'Life Pacific College',
            'Iowa Wesleyan University',
            'Illinois College of Optometry',
            'Vermont College of Fine Arts',
            'Conway School of Landscape Design',
            'Kuyper College',
            'Lake Forest Graduate School of Management',
            'Welch College',
            'Neumont University',
            'University of Maine at Machias',
            'Alaska Bible College',
            'Marymount California University',
            'Stillman College',
            'Allen College',
            'Chowan University',
            'Gratz College',
            'Martin University',
            'Mercy College of Health Sciences',
            'Webb Institute',
            'Philander Smith College',
            'Trinity College of Florida',
            'University of the Potomac',
            'University of Holy Cross',
            'Pacific Oaks College',
            'Davis College',
            'Santa Fe University of Art and Design',
            'Franciscan Missionaries of Our Lady University',
            'Maria College',
            'Nevada State College',
            'Laguna College of Art and Design',
            'BrewtonParker College',
            'New York City College of Technology CUNY',
            'Westfield State University',
            'Cleary University',
            'Catholic Theological Union',
            'Cox College',
            'Lincoln College of New England',
            'Gods Bible School and College',
            'South Georgia State College',
            'Everglades University',
            'Florida Gateway College',
            'Midstate College',
            'Donnelly College',
            'The Wright Institute',
            'The College of Westchester',
            'Five Towns College',
            'Sofia University',
            'Tennessee Wesleyan University',
            'Boricua College',
            'Phillips Graduate University',
            'St Gregorys University',
            'Patten University',
            'Pontifical Faculty of the Immaculate Conception',
            'Labour College',
            'BlessingRieman College of Nursing',
            'Crossroads College',
            'Trinity Bible College',
            'Southwestern College Santa Fe',
            'EastWest University',
            'United States University',
            'University of Alaska Southeast',
            'Beulah Heights University',
            'John Paul the Great Catholic University',
            'Pennsylvania College of Health Sciences',
            'MidAtlantic Christian University',
            'Boise Bible College',
            'Nebraska Christian College',
            'Middle Tennessee School of Anesthesia',
            'College of Staten Island',
            'Clear Creek Baptist Bible College',
            'Great Lakes Christian College',
            'Lakeview College of Nursing',
            'College of Biblical Studies',
            'The Kings University',
            'Columbia College of Nursing',
            'Briarcliffe College',
            'Concordia College Alabama',
            'Jamestown Business College',
            'Southwestern Christian University',
            'Resurrection University',
            'Baptist University of the Americas',
            'Wade College',
            'San Joaquin College of Law',
            'Arlington Baptist University',
            'Saint Augustine College',
            'Plaza College',
            'Saint Lukes College of Health Sciences',
            'Heritage Christian University',
            'Northpoint Bible College',
            'Crowleys Ridge College',
            'Pillar College',
            'Trinity College of Nursing  Health Sciences',
            'New Hope Christian College',
            'The University of West Los Angeles',
            'Bellin College',
            'St Louis Christian College',
            'Wisconsin School of Professional Psychology',
            'Dharma Realm Buddhist University',
            'Rocky Mountain University of Health Professions',
            'Baptist Bible College',
            'American Baptist College',
            'TriState Bible College',
            'Research College of Nursing',
            'Bryan College of Health Sciences',
            'Crossroads Bible College',
            'Methodist College',
            'Ecclesia College',
            'Denver College of Nursing',
            'John Wesley University',
            'Michigan School of Psychology',
            'Richmont Graduate University',
            'Southwest University of Visual Arts',
            'The National Graduate School of Quality Management',
            'Good Samaritan College of Nursing and Health Science',
            'Southeastern Baptist College',
            'Medgar Evers College',
            'University of Maine at Farmington',
            'WON Institute of Graduate Studies',
            'Bethesda University',
            'Helene Fuld College of Nursing',
            'Williams Baptist University',
            'Providence Christian College',
            'Northeast Catholic College',
            'Indiana University Fort Wayne',
            'CUNY School of Law',
            'Cabarrus College of Health Sciences',
            'Saint Anthony College of Nursing',
            'Geisinger Commonwealth School of Medicine',
            'Irell and Manella Graduate School of Biological Sciences',
            'American Film Institute Conservatory',
            'Antioch University Santa Barbara',
            'The Art Institute of Pittsburgh',
            'Antioch University Los Angeles',
            'Mayo Medical School',
            'Antioch University New England',
            'Saint Francis Medical Center College of Nursing',
            'Antioch University Seattle',
            'Ohio UniversityChillicothe',
            'Ohio University Southern',
            'Frontier Nursing University',
            'Iowa State University',
            'St Louis University',
            'Stony Brook University  SUNY',
            'University at Buffalo SUNY',
            'University of Puerto Rico',
            'Virginia Tech',
            'Arizona School of Dentistry and Oral Health  AT Still University',
            'University of Colorado Anschutz Medical Campus',
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        University::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        foreach ($universities as $university) {
            University::create([
                'name' => $university,
            ]);
        }
    }
}
