/*
 Navicat MySQL Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50731
 Source Host           : localhost:3306
 Source Schema         : leveredge

 Target Server Type    : MySQL
 Target Server Version : 50731
 File Encoding         : 65001

 Date: 29/01/2021 22:27:26
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for negotiation_groups
-- ----------------------------
DROP TABLE IF EXISTS `negotiation_groups`;
CREATE TABLE `negotiation_groups` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `academic_year_id` bigint(20) unsigned NOT NULL,
  `name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `priority` int(11) NOT NULL,
  `deal_confidence` int(11) NOT NULL COMMENT 'An integer from 0 - 100, indicating the percentage',
  `progress_stage` tinyint(4) NOT NULL DEFAULT '2',
  `progress_descriptions` text COLLATE utf8mb4_unicode_ci,
  `progress_titles` text COLLATE utf8mb4_unicode_ci,
  `display_count_based_on` tinyint(4) NOT NULL DEFAULT '1',
  `dashboard_update` text COLLATE utf8mb4_unicode_ci,
  `display_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `redirect_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `dashboard_button_cta` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hide_dashboard_button` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `academic_year_foreign` (`academic_year_id`),
  CONSTRAINT `academic_year_foreign` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of negotiation_groups
-- ----------------------------
BEGIN;
INSERT INTO `negotiation_groups` VALUES (1, 1, 'Refinance International', 'refinance-international', 1, 0, 1, '[\"You have joined the negotiation group\",\"Hit 1,000 members in the negotiation group\",\"Juno negotiates with lenders\"]', '[\"\",\"\",\"\"]', 2, '<div><strong>Thanks for joining the negotiation group!</strong><br>Once we hit 1,000 members we will try to negotiate a refinancing option for you. Click below to go to our campaign page and share the initiative with your friends!</div>', 'Refinance student loan negotiation group', '/member/international-refi/post-auth', '2020-02-07 05:59:24', '2020-11-10 00:31:04', NULL, NULL, 0);
INSERT INTO `negotiation_groups` VALUES (2, 1, 'Refinance Domestic', 'refinance-domestic', 99, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until June 5th\",\"By end of July\"]', 1, '<div><strong>All of our deals are now live! </strong>Fill out the quick questions below to see what we recommend for your situation!</div>', 'Refinance student loan negotiation group', NULL, '2020-02-07 05:59:24', '2020-09-25 22:03:33', NULL, 'See the deals', 0);
INSERT INTO `negotiation_groups` VALUES (3, 2, 'International 19-20', 'international-19-20', 1, 0, 2, NULL, NULL, 1, NULL, NULL, NULL, '2020-02-07 05:59:24', '2020-05-01 04:26:51', '2020-05-01 04:26:51', NULL, 0);
INSERT INTO `negotiation_groups` VALUES (4, 2, 'Wharton 19-20', 'wharton-19-20', 2, 0, 2, NULL, NULL, 1, NULL, NULL, NULL, '2020-02-07 05:59:24', '2020-05-01 04:26:45', '2020-05-01 04:26:45', NULL, 0);
INSERT INTO `negotiation_groups` VALUES (5, 2, 'Laurel Road 19-20', 'laurel-road-19-20', 3, 0, 2, NULL, NULL, 1, NULL, NULL, NULL, '2020-02-07 05:59:24', '2020-05-01 04:26:43', '2020-05-01 04:26:43', NULL, 0);
INSERT INTO `negotiation_groups` VALUES (6, 2, 'Other Domestic 19-20', 'other-domestic-19-20', 4, 0, 2, NULL, NULL, 1, NULL, NULL, NULL, '2020-02-07 05:59:24', '2020-05-01 04:26:40', '2020-05-01 04:26:40', NULL, 0);
INSERT INTO `negotiation_groups` VALUES (7, 3, 'General Group 20-21', 'general-group-20-21', 99, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until May 15th\",\"By June 15th\"]', 1, '<div><strong>Oops! Please make sure your profile is up to date.</strong></div><div>If you\'re still seeing this message, <a href=\"https://joinjuno.com/contact\">contact us</a> so we can sort this out for you and get you access to the deals.</div>', 'Academic Year 2020-21 student loan negotiation group', NULL, '2020-02-07 05:59:24', '2020-09-25 22:16:06', NULL, NULL, 1);
INSERT INTO `negotiation_groups` VALUES (8, 3, 'US Persons at CB Eligible Programs 20-21', 'us-persons-at-cb-eligible-programs-20-21', 10, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until May 15th\",\"By June 15th\"]', 1, '<div><strong>We\'re ready to share the deals we negotiated!<br></strong>Check out the deal(s) we recommend for you by clicking below.</div>', 'Academic Year 2020-21 student loan negotiation group', NULL, '2020-06-10 05:12:19', '2020-09-25 22:02:59', NULL, 'View deal(s)', 0);
INSERT INTO `negotiation_groups` VALUES (9, 3, 'US Persons at Non-CB Eligible Grad Programs 20-21', 'us-persons-at-non-cb-eligible-grad-programs-20-21', 11, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until May 15th\",\"By June 15th\"]', 1, '<div><strong>We\'re ready to share the deals we negotiated!<br></strong>Check out the deal(s) we recommend for you by clicking below.</div>', 'Academic Year 2020-21 student loan negotiation group', NULL, '2020-06-10 05:12:19', '2020-09-25 22:02:56', NULL, 'View deal(s)', 0);
INSERT INTO `negotiation_groups` VALUES (10, 3, 'US Persons at Undergrad Programs 20-21', 'us-persons-at-undergrad-programs-20-21', 12, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until May 15th\",\"By June 15th\"]', 1, '<div><strong>We\'re ready to share the deals we negotiated!<br></strong>Check out the deal we recommend for you by clicking below.</div><div><br></div>', 'Academic Year 2020-21 student loan negotiation group', '/member/negotiation-group/10/earnest-undergraduate-deal', '2020-06-10 05:12:19', '2020-09-25 22:03:02', NULL, 'View deal', 0);
INSERT INTO `negotiation_groups` VALUES (11, 3, 'International with US Co-signer 20-21', 'international-with-us-cosigner-20-21', 13, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until May 15th\",\"By June 15th\"]', 1, '<div><strong>If you do not have an SSN, </strong>our partners are unfortunately not able to lend to you, but Nomad Credit can help. Nomad Credit is a <strong>free service</strong> with deep knowledge in the international student loan space, here to help our members be aware of all the options available and help you navigate the loan application process as someone with a U.S. cosigner. <a href=\"https://www.nomadcredit.com/student-loans/?referral_source=leveredge\"><strong>Click here to start the process with Nomad.</strong></a><strong><br><br>If you do have an SSN, </strong>our deals are ready to be accessed! Click below to be taken to the deal(s) we recommend for you.&nbsp;</div>', 'Academic Year 2020-21 student loan negotiation group', NULL, '2020-06-10 05:12:19', '2020-09-25 22:03:04', NULL, NULL, 0);
INSERT INTO `negotiation_groups` VALUES (12, 3, 'International at Discover Schools 20-21', 'international-without-cosigner-at-discover-schools-20-21', 14, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has partnered with Nomad Credit\"]', '[\"Now and ongoing\",\"Up until May 15th\",\"June\"]', 1, '<div><strong>We\'ve partnered with Nomad Credit</strong><br><br>Nomad Credit is a <strong>free service</strong> with deep knowledge in the international student loan space, here to help our members be aware of all the options available by connecting you to one of their top loan counselors exclusively dedicated to Juno members. They will also help you navigate the loan application process. <a href=\"https://www.nomadcredit.com/student-loans/?referral_source=leveredge\"><strong>Click here to start the process with Nomad.</strong></a></div>', 'Academic Year 2020-21 student loan negotiation group', NULL, '2020-06-10 05:12:19', '2020-09-25 22:20:40', NULL, NULL, 1);
INSERT INTO `negotiation_groups` VALUES (13, 3, 'Internationals at Non-Discover Programs 20-21', 'international-at-non-discover-programs-20-21', 15, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has partnered with Nomad Credit\"]', '[\"Now and ongoing\",\"Up until May 15th\",\"June\"]', 1, '<div><strong>We\'ve partnered with Nomad Credit</strong><br><br></div><div>Nomad Credit is a <strong>free service</strong> with deep knowledge in the international student loan space, here to help our members be aware of all the options available by connecting you to one of their top loan counselors exclusively dedicated to Juno members. They can also help you navigate the loan application process. Please keep in mind we’ve learned that Nomad is most uniquely helpful to<strong> </strong>international students from India due to Nomad’s partnerships with local banks there. <a href=\"https://www.nomadcredit.com/student-loans/?referral_source=leveredge\"><strong>Click here to start the process with Nomad.</strong></a></div><div><br></div>', 'Academic Year 2020-21 student loan negotiation group', NULL, '2020-06-10 05:12:19', '2020-09-25 22:21:15', NULL, NULL, 1);
INSERT INTO `negotiation_groups` VALUES (14, 1, 'Refinance Medical In FR Cities', 'refinance-medical-in-fr-cities', 1, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until June 5th\",\"By August 14th\"]', 1, '<div><strong>The deals are ready! </strong>You have two great options, click below to see them!</div>', 'Refinance student loan negotiation group', '/member/negotiation-group/14/first-republic-and-laurel-road', '2020-07-03 01:00:00', '2020-09-25 22:01:45', NULL, 'See the deals', 0);
INSERT INTO `negotiation_groups` VALUES (15, 1, 'Refinance Medical Outside FR Cities', 'refinance-medical-outside-fr-cities', 2, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until June 5th\",\"By August 14th\"]', 1, '<div><strong>The deal is ready!&nbsp;</strong>Click below to see the deal and check your rates.</div>', 'Refinance student loan negotiation group', '/member/negotiation-group/15/laurel-road-deal', '2020-07-03 01:00:00', '2020-09-25 22:01:49', NULL, 'See the deal', 0);
INSERT INTO `negotiation_groups` VALUES (16, 1, 'Refinance Non Medical In FR Cities', 'refinance-non-medical-in-fr-cities', 3, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until June 5th\",\"By August 21\"]', 1, '<div><strong>Your deal is ready! </strong>Click below to check it out.</div>', 'Refinance student loan negotiation group', '/member/negotiation-group/16/first-republic-refinance-deal', '2020-07-03 01:00:00', '2020-09-25 22:01:51', NULL, 'View deal', 0);
INSERT INTO `negotiation_groups` VALUES (17, 1, 'Refinance Non Medical Outside FR Cities', 'refinance-non-medical-outside-fr-cities', 4, 0, 4, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"Now and ongoing\",\"Up until June 5th\",\"By July 15th\"]', 1, '<div><strong>We have two refinancing deals for you! </strong>Click below to check them out.</div>', 'Refinance student loan negotiation group', NULL, '2020-07-03 01:00:00', '2020-09-25 22:02:53', NULL, 'View deals', 0);
INSERT INTO `negotiation_groups` VALUES (18, 4, 'Eligible for GBG', 'eligible-for-gbg', 1, 0, 4, '[\"You have joined the group\",\"Juno negotiates with partners\",\"Juno has a deal ready for you\"]', '[\"\",\"\",\"\"]', 1, '<div><strong>You\'re eligible for our health insurance deal!</strong> Click below to be taken to the insurance provider\'s portal.</div>', 'International Student Health Insurance negotiation group', '/member/negotiation-group/18/gbg-health-insurance-deal', '2020-08-19 00:16:15', '2020-09-25 22:01:47', NULL, 'View deal', 0);
INSERT INTO `negotiation_groups` VALUES (19, 4, 'Not Eligible for GBG', 'not-eligible-for-gbg', 1, 0, 2, '[\"You have joined the negotiation group\",\"Juno negotiates with partners\",\"Juno has a deal ready for you\"]', '[\"\",\"\",\"\"]', 1, '<div><strong>Unfortunately, you are not eligible for our health insurance deal at this time.&nbsp;</strong>The list of eligible universities is expanding by the day, but we want you to be covered in the meantime. If you are still interested in waiving your university’s plan, there are other independent providers such as <a href=\"https://www.psiservice.com/\">PSI</a> and <a href=\"http://isoa.org/\">ISO</a> that you can check out.&nbsp;</div>', 'International Student Health Insurance negotiation group', '/member/dashboard', '2020-08-19 00:16:22', '2020-09-25 22:01:48', NULL, NULL, 1);
INSERT INTO `negotiation_groups` VALUES (20, 5, 'General Auto Refinance', 'general-auto-refinance', 99, 0, 2, '[\"Hit 1,000 members in the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"\",\"\",\"\"]', 1, '<div><strong>Update 1/14/20:&nbsp;</strong>We’ve successfully negotiated deals with major auto refinancing providers, but after doing some testing we are not yet comfortable releasing them to the whole group. We want to represent everyone’s interests and get you the best deals on the market, so we are continuing to negotiate with other providers to identify more solutions for our members.&nbsp;<br>Thank you once again for sticking with us and for your patience in the meantime.&nbsp;</div>', 'Auto Loan Refinancing Group', '/loans/auto-refinance/post-auth', '2020-10-22 17:44:34', '2021-01-14 20:13:47', NULL, 'Go to Campaign', 0);
INSERT INTO `negotiation_groups` VALUES (21, 6, 'General Bar Prep Negotiation Group', 'bar-prep', 99, 0, 1, '[\"Hit 1,000 members in the negotiation group\",\"Juno negotiates with bar prep companies\",\"Juno has a deal ready for you\"]', '[\"\",\"\",\"\"]', 1, '<div><strong>We\'re on our way to 1000 members!</strong> Stay up to date on our campaign to save you money on bar prep.</div>', 'Bar Prep Negotiation Group', '/test-prep/bar-prep/success', '2020-10-22 17:44:34', '2021-01-14 11:41:08', '2021-01-14 11:41:08', 'Go to Campaign', 0);
INSERT INTO `negotiation_groups` VALUES (22, 7, 'Domestic Group 2021-22', 'domestic-group-21-22', 99, 0, 2, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"\",\"\",\"\"]', 1, '<div><strong>Thank you for joining the negotiation group!<br></strong>Click below to go to our campaign page and share the initiative with your friends.</div>', 'Academic Year 2021-22 student loan negotiation group', '/member/academic-year-21-22/post-auth', '2020-11-06 22:16:09', '2020-12-08 22:35:44', NULL, 'Go to Campaign', 0);
INSERT INTO `negotiation_groups` VALUES (23, 7, 'International Group 2021-22', 'international-group-21-22', 99, 0, 2, '[\"You have joined the negotiation group\",\"Juno negotiates with lenders\",\"Juno has a deal ready for you\"]', '[\"\",\"\",\"\"]', 1, '<div><strong>Thank you for joining the negotiation group!<br></strong>Click below to go to our campaign page and share the initiative with your friends.</div>', 'Academic Year 2021-22 student loan negotiation group', '/member/international-academic-year-21-22/post-auth', '2020-11-06 22:16:09', '2020-12-04 00:45:43', NULL, 'Go to Campaign', 0);
INSERT INTO `negotiation_groups` VALUES (24, 8, 'College Test Prep', 'college-test-prep', 99, 0, 1, '[\"Hit 1,000 members in the negotiation group\",\"Juno negotiates with test prep companies\",\"Juno has a deal ready for you\"]', '[\"\",\"\",\"\"]', 1, '<div><strong>We\'re on our way to 1,000 members! </strong>Go to our campaign page to share this with your friends so we can save everyone money on SAT/ACT prep.</div>', 'College Test Prep', '/member/test-prep/college-test-prep/post-auth', '2020-12-02 20:16:28', '2020-12-04 01:17:42', NULL, 'Go to Campaign', 0);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
