/*
 Navicat MySQL Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50732
 Source Host           : localhost:3306
 Source Schema         : leveredge

 Target Server Type    : MySQL
 Target Server Version : 50732
 File Encoding         : 65001

 Date: 16/02/2021 21:19:21
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for questions
-- ----------------------------
DROP TABLE IF EXISTS `questions`;
CREATE TABLE `questions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `question_page_id` bigint(20) unsigned NOT NULL,
  `sort_order` int(10) unsigned NOT NULL DEFAULT '99',
  `template` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `helper_text` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tooltip` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `placeholder` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `field_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `question_option` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `skip_policy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visibility_policy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `validation_rules` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `persist_response` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `questions_question_page_id_foreign` (`question_page_id`),
  CONSTRAINT `questions_question_page_id_foreign` FOREIGN KEY (`question_page_id`) REFERENCES `question_pages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=175 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of questions
-- ----------------------------
BEGIN;
INSERT INTO `questions` VALUES (1, 1, 1, NULL, 'card-radio', 'What kind of loan are you looking for?', NULL, NULL, NULL, 'loan_type', 'App\\QuestionOptions\\UndergraduateGraduate', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (2, 2, 1, NULL, 'list-radio', 'When do you need the loan?', NULL, NULL, NULL, 'academic_year_id', 'App\\QuestionOptions\\AcademicYears', NULL, NULL, NULL, 'App\\PersistResponse\\PersistInQuestionResponderOnly', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (3, 3, 1, NULL, 'dropdown', 'Are you a student or a parent?', NULL, NULL, 'Select your role', 'role', 'App\\QuestionOptions\\StudentParent', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (4, 3, 2, NULL, 'text', 'Your First Name', NULL, NULL, 'First Name', 'first_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (5, 3, 3, NULL, 'text', 'Your Last Name', NULL, NULL, 'Last Name', 'last_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (6, 3, 4, NULL, 'searchable-dropdown', 'Your Citizenship Status', NULL, 'Some lenders only lend to US Citizens or US Permanent Residents. Therefore, we ask for this information to determine who we can negotiate with to get you the best deal.', 'Select your citizenship status', 'immigration_status', 'App\\QuestionOptions\\CitizenshipStatus', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (7, 3, 5, NULL, 'dropdown', 'Country of Citizenship', NULL, NULL, 'Select your country of citizenship', 'country_of_citizenship_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfCitizenshipIsInternational', 'required_if:immigration_status,International', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (8, 3, 6, NULL, 'dropdown', 'Country of Residence', NULL, NULL, 'Select your country of residence', 'country_of_residence_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfCitizenshipIsInternational', 'required_if:immigration_status,International', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (9, 3, 7, NULL, 'text', 'Your Phone Number (Optional)', NULL, NULL, 'Phone Number', 'phone_number', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (10, 3, 8, NULL, 'dropdown', 'How did you hear about us?', NULL, NULL, 'Select one of the options', 'heard_from_option_id', 'App\\QuestionOptions\\HeardFromOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (11, 4, 1, NULL, 'searchable-dropdown', 'University', NULL, NULL, 'Select your university', 'university_id', 'App\\QuestionOptions\\University', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (12, 4, 2, NULL, 'searchable-dropdown', 'Degree', NULL, NULL, 'Select your degree', 'degree_id', 'App\\QuestionOptions\\UndergraduateDegree', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (13, 4, 3, 'version-1', 'number', 'Graduation Year', NULL, NULL, 'Graduation Year', 'graduation_year', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (14, 5, 1, 'version-1', 'searchable-dropdown', 'University', NULL, NULL, 'Select your University', 'grad_university_id', 'App\\QuestionOptions\\University', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (15, 5, 2, NULL, 'dropdown', 'Degree', NULL, NULL, 'Select your Degree', 'grad_degree_id', 'App\\QuestionOptions\\GraduateDegree', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (16, 5, 3, 'version-1', 'number', 'Graduation Year', NULL, NULL, 'Graduation Year', 'grad_graduation_year', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (17, 6, 1, NULL, 'dropdown', 'Your Credit Score', NULL, NULL, 'Select your credit score', 'credit_score', 'App\\QuestionOptions\\CreditScore', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (18, 6, 2, 'version-1', 'number', 'Your Annual Income (USD)', 'Most students enter $0 and many members with $0 get the lowest rates offered.', 'How much will you earn in the next 12 months?', 'Annual Income', 'annual_income', NULL, NULL, NULL, 'numeric', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (19, 6, 3, NULL, 'dropdown', 'Do you have a co-signer?', NULL, 'A co-signer is a person who is obligated to pay back the loan just as you, the borrower, are obligated to pay. A co-signer could be your spouse, a parent, or a friend.', 'Select your Co-signer Status', 'cosigner_status', 'App\\QuestionOptions\\YesNoMaybe', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (20, 6, 4, NULL, 'searchable-dropdown', 'Co-signer\'s Citizenship Status', NULL, 'Some lenders only lend to US Citizens or US Permanent Residents. Therefore, we ask for this information to determine who we can negotiate with to get you the best deal.', 'Select your co-signer\'s citizenship status', 'cosigner_immigration_status', 'App\\QuestionOptions\\CitizenshipStatus', NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'required_if:cosigner_status,Yes', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (21, 6, 5, NULL, 'dropdown', 'Co-signer\'s Credit Score', NULL, NULL, 'Select your co-signer\'s credit score', 'cosigner_credit_score', 'App\\QuestionOptions\\CreditScore', NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'required_if:cosigner_status,Yes', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (22, 6, 6, 'version-1', 'number', 'Co-signer\'s Annual Income (USD)', NULL, 'How much will your co-signer earn in the next 12 months?', 'Annual Income', 'cosigner_annual_income', NULL, NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'required_if:cosigner_status,Yes', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:09:01', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (23, 7, 1, NULL, 'text', 'Your First Name', NULL, NULL, 'First Name', 'first_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (24, 7, 2, NULL, 'text', 'Your Last Name', NULL, NULL, 'Last Name', 'last_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (25, 7, 3, NULL, 'searchable-dropdown', 'Your Citizenship Status', NULL, 'Some lenders only lend to US Citizens or US Permanent Residents. Therefore, we ask for this information to determine who we can negotiate with to get you the best deal.', 'Select your citizenship status', 'immigration_status', 'App\\QuestionOptions\\CitizenshipStatus', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (26, 7, 4, NULL, 'dropdown', 'Country of Citizenship', NULL, NULL, 'Select your country of citizenship', 'country_of_citizenship_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfCitizenshipIsInternational', 'required_if:immigration_status,International', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (27, 7, 5, NULL, 'dropdown', 'Country of Residence', NULL, NULL, 'Select your country of residence', 'country_of_residence_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfCitizenshipIsInternational', 'required_if:immigration_status,International', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (28, 7, 6, NULL, 'text', 'Your Phone Number (Optional)', NULL, NULL, 'Phone Number', 'phone_number', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (29, 7, 7, NULL, 'dropdown', 'How did you hear about us?', NULL, NULL, 'Select one of the options', 'heard_from_option_id', 'App\\QuestionOptions\\HeardFromOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (30, 8, 1, NULL, 'dropdown', 'Your Credit Score', NULL, NULL, 'Select your credit score', 'credit_score', 'App\\QuestionOptions\\CreditScore', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (31, 8, 2, 'version-1', 'number', 'Your Annual Income (USD)', 'Most students enter $0 and many members with $0 get the lowest rates offered.', 'How much will you earn in the next 12 months?', 'Annual Income', 'annual_income', NULL, NULL, NULL, 'numeric|min:0', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 16:18:12', NULL);
INSERT INTO `questions` VALUES (32, 8, 3, NULL, 'dropdown', 'Do you have a co-signer?', NULL, 'A co-signer is a person who is obligated to pay back the loan just as you, the borrower, are obligated to pay. A co-signer could be your spouse, a parent, or a friend.', 'Select your Co-signer Status', 'cosigner_status', 'App\\QuestionOptions\\YesNoMaybe', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (33, 8, 4, NULL, 'searchable-dropdown', 'Co-signer\'s Citizenship Status', NULL, 'Some lenders only lend to US Citizens or US Permanent Residents. Therefore, we ask for this information to determine who we can negotiate with to get you the best deal.', 'Select your co-signer\'s citizenship status', 'cosigner_immigration_status', 'App\\QuestionOptions\\CitizenshipStatus', NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'required_if:cosigner_status,Yes', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (34, 8, 5, NULL, 'dropdown', 'Co-signer\'s Credit Score', NULL, NULL, 'Select your co-signer\'s credit score', 'cosigner_credit_score', 'App\\QuestionOptions\\CreditScore', NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'required_if:cosigner_status,Yes', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (35, 8, 6, 'version-1', 'number', 'Co-signer\'s Annual Income (USD)', NULL, 'How much will your co-signer earn in the next 12 months?', 'Annual Income', 'cosigner_annual_income', NULL, NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'nullable|numeric', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 16:24:05', NULL);
INSERT INTO `questions` VALUES (36, 9, 1, NULL, 'dropdown', 'What kind of loans are you looking to refinance?', NULL, NULL, 'Select one of the options', 'refinance_loan_type', 'App\\QuestionOptions\\ExistingStudentLoanTypeOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (37, 9, 2, NULL, 'dropdown', 'Are you currently employed?', NULL, NULL, 'Select one of the options', 'is_currently_employed', 'App\\QuestionOptions\\YesNoBoolean', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (38, 9, 3, NULL, 'dropdown', 'Do you have an offer letter with a start date?', NULL, NULL, 'Select one of the options', 'have_job_start_date', 'App\\QuestionOptions\\YesNoBoolean', NULL, 'App\\VisibilityPolicies\\IfCurrentlyEmployedIsNo', 'required_if:is_currently_employed,0', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (39, 9, 4, NULL, 'date', 'What is your start date?', NULL, NULL, NULL, 'job_start_date', NULL, NULL, 'App\\VisibilityPolicies\\IfHasJobStartDateYes', 'required_if:have_job_start_date,1', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-24 00:09:01', '2020-11-24 00:09:01', NULL);
INSERT INTO `questions` VALUES (40, 10, 1, 'version-1', 'text', 'First Name', NULL, NULL, NULL, 'first_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:42:35', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (41, 10, 2, NULL, 'text', 'Last Name', NULL, NULL, NULL, 'last_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:44:42', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (43, 10, 6, 'version-1', 'dropdown', 'Credit Score', NULL, NULL, NULL, 'credit_score', 'App\\QuestionOptions\\DetailedCreditScore', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:53:55', '2021-02-11 00:56:33', '2021-02-11 00:56:33');
INSERT INTO `questions` VALUES (44, 10, 7, 'version-1', 'number', 'Payoff Amount', NULL, 'How much you\'ll need to completely pay off your debt', NULL, 'payoff_amount', NULL, NULL, NULL, 'numeric', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 00:55:57', '2021-02-11 00:57:27', '2021-02-11 00:57:27');
INSERT INTO `questions` VALUES (53, 11, 10, 'version-1', 'text', 'What\'s your current interest rate?', 'a rough estimate is great!', NULL, 'Enter a numerical value without the %, ie 4.5', 'original_loan_interest_rate', NULL, NULL, NULL, 'required|numeric', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 01:46:29', '2021-02-11 00:57:35', NULL);
INSERT INTO `questions` VALUES (54, 12, 1, NULL, 'dropdown', 'What is your employment status?', NULL, NULL, NULL, 'employment_status', 'App\\QuestionOptions\\EmploymentStatus', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 01:48:06', '2021-02-11 00:50:19', '2021-02-11 00:50:19');
INSERT INTO `questions` VALUES (55, 12, 2, 'version-1', 'number', 'If you\'re employed, how many years have you worked there?', NULL, NULL, NULL, 'employment_length_in_years', NULL, NULL, NULL, 'nullable|numeric', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 01:50:51', '2021-02-11 00:50:16', '2021-02-11 00:50:16');
INSERT INTO `questions` VALUES (56, 12, 4, NULL, 'number', 'What is your yearly pre-tax income?', NULL, NULL, NULL, 'yearly_pre_tax_income', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 01:51:52', '2021-02-11 00:56:20', NULL);
INSERT INTO `questions` VALUES (57, 12, 4, NULL, 'number', 'What is your monthly housing payment? (Rent/Mortgage payment)', NULL, NULL, NULL, 'housing_payment', NULL, NULL, NULL, 'nullable', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 01:52:35', '2021-02-11 00:50:30', '2021-02-11 00:50:30');
INSERT INTO `questions` VALUES (58, 13, 1, 'version-1', 'number', 'What is your zip code?', NULL, NULL, 'Example: 90210', 'zip_code', NULL, NULL, NULL, 'numeric', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 01:54:13', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (59, 13, 2, NULL, 'dropdown', 'Residence Ownership', NULL, NULL, NULL, 'residence_ownership', 'App\\QuestionOptions\\ResidenceOwnership', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 01:55:07', '2021-02-11 00:50:53', '2021-02-11 00:50:53');
INSERT INTO `questions` VALUES (60, 13, 3, NULL, 'number', 'How many years have you stayed there?', NULL, NULL, NULL, 'stay_duration', NULL, NULL, NULL, 'numeric', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 01:55:48', '2021-02-11 00:50:51', '2021-02-11 00:50:51');
INSERT INTO `questions` VALUES (61, 15, 1, 'version-1', 'card-radio', 'International Health Insurance', NULL, NULL, NULL, 'loan_type', 'App\\QuestionOptions\\UndergraduateGraduate', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-24 23:41:32', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (63, 14, 1, 'version-1', 'dropdown', 'Select your role', NULL, NULL, NULL, 'role', 'App\\QuestionOptions\\StudentParent', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 00:48:41', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (64, 14, 2, 'version-1', 'text', 'Your First Name', NULL, NULL, 'First Name', 'first_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 01:15:55', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (65, 14, 3, 'version-1', 'text', 'Your Last Name', NULL, NULL, 'Last Name', 'last_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 01:16:33', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (66, 14, 4, 'version-1', 'dropdown', 'Your Citizenship Status', NULL, 'Some lenders only lend to US Citizens or US Permanent Residents. Therefore, we ask for this information to determine who we can negotiate with to get you the best deal.', 'Selec your citizenship status', 'immigration_status', 'App\\QuestionOptions\\CitizenshipStatus', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 01:17:55', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (67, 14, 5, 'version-1', 'text', 'Your Phone Number (Optional)', NULL, 'We do not share your phone number with any third party. We only use your phone number to directly get in touch with you.', 'Phone Number', 'phone_number', NULL, NULL, NULL, 'nullable', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 01:18:59', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (68, 14, 8, 'version-1', 'dropdown', 'How did you hear about us?', NULL, NULL, 'Select one of the options', 'heard_from_option_id', 'App\\QuestionOptions\\HeardFromOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 01:20:15', '2021-02-03 23:30:11', NULL);
INSERT INTO `questions` VALUES (69, 14, 6, 'version-1', 'searchable-dropdown', 'Country of Citizenship', NULL, NULL, 'Select your country of citizenship', 'country_of_citizenship_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfCitizenshipIsInternational', 'required_if:immigration_status,International', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 01:22:52', '2021-02-03 23:29:43', NULL);
INSERT INTO `questions` VALUES (70, 14, 7, 'version-1', 'searchable-dropdown', 'Country of Residence', NULL, NULL, 'Select your country of residence', 'country_of_residence_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfCitizenshipIsInternational', 'required_if:immigration_status,International', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 01:31:27', '2021-02-03 23:30:07', NULL);
INSERT INTO `questions` VALUES (71, 17, 1, 'version-1', 'searchable-dropdown', 'University', NULL, NULL, 'Select your University', 'university_id', 'App\\QuestionOptions\\University', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 02:28:30', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (72, 17, 2, 'version-1', 'searchable-dropdown', 'Degree', NULL, NULL, 'Select your Degree', 'degree_id', 'App\\QuestionOptions\\UndergraduateDegree', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 02:33:04', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (73, 17, 3, 'version-1', 'number', 'Graduation Year', NULL, NULL, 'Graduation Year', 'graduation_year', NULL, NULL, NULL, 'required|numeric', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 02:33:53', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (79, 19, 1, 'version-1', 'searchable-dropdown', 'University', NULL, NULL, 'Select your University', 'grad_university_id', 'App\\QuestionOptions\\University', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 16:48:10', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (80, 19, 2, 'version-1', 'searchable-dropdown', 'Degree', NULL, NULL, 'Select your Degree', 'grad_degree_id', 'App\\QuestionOptions\\GraduateDegree', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 16:48:55', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (81, 19, 3, 'version-1', 'number', 'Graduation Year', NULL, NULL, 'Graduation Year', 'grad_graduation_year', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-11-25 16:49:30', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (82, 20, 1, 'version-1', 'text', 'Your First Name', NULL, NULL, 'First Name', 'first_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModel', '2020-11-26 01:41:38', '2020-11-26 01:41:38', NULL);
INSERT INTO `questions` VALUES (83, 20, 2, 'version-1', 'text', 'Your Last Name', NULL, NULL, 'Last Name', 'last_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModel', '2020-11-26 01:47:51', '2020-11-26 01:47:51', NULL);
INSERT INTO `questions` VALUES (84, 20, 3, 'version-1', 'searchable-dropdown', 'University', NULL, NULL, 'Select your University', 'university_id', 'App\\QuestionOptions\\University', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 01:48:27', '2020-11-26 01:48:27', NULL);
INSERT INTO `questions` VALUES (85, 20, 4, 'version-1', 'number', 'Graduation Year', NULL, NULL, 'Graduation Year', 'graduation_year', NULL, NULL, NULL, 'required|numeric', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 01:49:39', '2020-11-26 01:49:39', NULL);
INSERT INTO `questions` VALUES (86, 21, 1, 'version-1', 'searchable-dropdown', 'Which state are you planning to take the bar in?', NULL, NULL, 'Which state are you planning to take the bar in?', 'bar_prep_location', 'App\\QuestionOptions\\StateOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 02:11:17', '2020-11-26 02:11:17', NULL);
INSERT INTO `questions` VALUES (87, 21, 2, 'version-1', 'dropdown', 'When do you plan to take the bar exam?', NULL, NULL, 'When do you plan to take the bar exam?', 'bar_prep_deadline', 'App\\QuestionOptions\\BarPrepExams', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 02:12:18', '2020-11-26 02:12:18', NULL);
INSERT INTO `questions` VALUES (88, 22, 1, 'version-1', 'dropdown', 'How are you paying for your bar prep?', NULL, NULL, 'How are you paying for your bar prep?', 'bar_prep_payment_info', 'App\\QuestionOptions\\BarPrepPayingOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 02:15:08', '2020-11-26 02:15:08', NULL);
INSERT INTO `questions` VALUES (89, 22, 2, 'version-1', 'text', 'What is the name of your employer?', NULL, NULL, 'Name of your employer', 'bar_prep_payment_employer_name', NULL, NULL, 'App\\VisibilityPolicies\\IfBarPrepPaymentInfoIsStipendOrDirectBill', 'required_if:bar_prep_payment_info,Employer stipend|required_if:bar_prep_payment_info,Employer direct bill', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 02:53:03', '2020-11-26 02:56:06', NULL);
INSERT INTO `questions` VALUES (90, 22, 3, 'version-1', 'text', 'How are you paying for your bar prep? (other)', NULL, NULL, 'Describe', 'bar_prep_payment_info', NULL, NULL, 'App\\VisibilityPolicies\\IfBarPrepPaymentInfoOther', 'required_if:bar_prep_payment_info,Other', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 02:54:23', '2020-11-26 12:15:09', NULL);
INSERT INTO `questions` VALUES (91, 22, 4, 'version-1', 'dropdown', 'Have you already signed up for a bar prep course?', NULL, NULL, 'Have you already signed up for a bar prep course?', 'bar_prep_sign_up', 'App\\QuestionOptions\\BarPrepSignedOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 02:57:47', '2020-11-26 02:57:47', NULL);
INSERT INTO `questions` VALUES (92, 22, 5, 'version-1', 'number', 'How much was your deposit?', NULL, NULL, 'Deposit amount', 'bar_prep_deposit_amount', NULL, NULL, 'App\\VisibilityPolicies\\IfSignedBarPrepCourseIsYes', 'nullable|required_unless:bar_prep_sign_up,No', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 03:00:13', '2020-12-04 12:28:20', NULL);
INSERT INTO `questions` VALUES (93, 22, 6, 'version-1', 'dropdown', 'What bar prep course did you choose?', NULL, NULL, 'Course Name', 'bar_prep_course', 'App\\QuestionOptions\\BarPrepPreferredCompanyOptions', NULL, 'App\\VisibilityPolicies\\IfSignedBarPrepCourseIsYes', 'nullable|required_unless:bar_prep_sign_up,No', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 03:07:20', '2020-12-04 12:28:12', NULL);
INSERT INTO `questions` VALUES (94, 23, 1, 'version-1', 'dropdown', 'What are you looking for most in a bar prep course?', NULL, NULL, 'What are you looking for most in a bar prep course?', 'bar_prep_priority', 'App\\QuestionOptions\\BarPrepPriorityOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 03:10:54', '2020-11-26 03:10:54', NULL);
INSERT INTO `questions` VALUES (95, 23, 2, 'version-1', 'text', 'What are you looking for most in a bar prep course? (other)', NULL, NULL, 'Describe', 'bar_prep_priority', NULL, NULL, 'App\\VisibilityPolicies\\IfBarPrepPriorityOptionIsOther', 'required_if:bar_prep_priority,Other', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 03:18:56', '2020-11-26 12:21:26', NULL);
INSERT INTO `questions` VALUES (96, 23, 3, 'version-1', 'dropdown', 'Do you have a preference for a certain bar prep company?', NULL, NULL, 'Do you have a preference for a certain bar prep company?', 'bar_prep_company_preference', 'App\\QuestionOptions\\YesNo', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 03:21:31', '2020-11-26 03:21:31', NULL);
INSERT INTO `questions` VALUES (97, 23, 4, 'version-1', 'dropdown', 'Preferred Company', NULL, NULL, 'Select one of the options', 'bar_prep_preferred_company', 'App\\QuestionOptions\\BarPrepPreferredCompanyOptions', NULL, 'App\\VisibilityPolicies\\IfBarPrepPreferenceIsYes', 'required_if:bar_prep_company_preference,Yes', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-11-26 03:22:47', '2020-11-26 03:22:47', NULL);
INSERT INTO `questions` VALUES (98, 10, 3, 'version-1', 'text', 'Phone Number (Optional)', NULL, NULL, NULL, 'phone_number', NULL, NULL, NULL, 'nullable|phone:auto,us', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 00:55:55', '2021-02-12 22:18:51', NULL);
INSERT INTO `questions` VALUES (99, 24, 1, NULL, 'text', 'Your First Name', NULL, NULL, 'First Name', 'first_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (100, 24, 2, NULL, 'text', 'Your Last Name', NULL, NULL, 'Last Name', 'last_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (101, 24, 3, NULL, 'searchable-dropdown', 'Your Citizenship Status', NULL, 'Some lenders only lend to US Citizens or US Permanent Residents. Therefore, we ask for this information to determine who we can negotiate with to get you the best deal.', 'Select your citizenship status', 'immigration_status', 'App\\QuestionOptions\\CitizenshipStatus', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (102, 24, 4, NULL, 'dropdown', 'Country of Citizenship', NULL, NULL, 'Select your country of citizenship', 'country_of_citizenship_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfCitizenshipIsInternational', 'required_if:immigration_status,International', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (103, 24, 5, NULL, 'dropdown', 'Country of Residence', NULL, NULL, 'Select your country of residence', 'country_of_residence_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfCitizenshipIsInternational', 'required_if:immigration_status,International', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (104, 24, 6, NULL, 'text', 'Your Phone Number (Optional)', NULL, NULL, 'Phone Number', 'phone_number', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (105, 24, 7, NULL, 'dropdown', 'How did you hear about us?', NULL, NULL, 'Select one of the options', 'heard_from_option_id', 'App\\QuestionOptions\\HeardFromOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (106, 25, 1, NULL, 'dropdown', 'Your Credit Score', NULL, NULL, 'Select your credit score', 'credit_score', 'App\\QuestionOptions\\CreditScore', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (107, 25, 2, 'version-1', 'number', 'Your Annual Income (USD)', NULL, 'How much will you earn in the next 12 months?', 'Annual Income', 'annual_income', NULL, NULL, NULL, 'numeric|min:0', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (108, 25, 3, NULL, 'dropdown', 'Do you have a co-signer?', NULL, 'A co-signer is a person who is obligated to pay back the loan just as you, the borrower, are obligated to pay. A co-signer could be your spouse, a parent, or a friend.', 'Select your Co-signer Status', 'cosigner_status', 'App\\QuestionOptions\\YesNoMaybe', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (109, 25, 4, NULL, 'searchable-dropdown', 'Co-signer\'s Citizenship Status', NULL, 'Some lenders only lend to US Citizens or US Permanent Residents. Therefore, we ask for this information to determine who we can negotiate with to get you the best deal.', 'Select your co-signer\'s citizenship status', 'cosigner_immigration_status', 'App\\QuestionOptions\\CitizenshipStatus', NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'required_if:cosigner_status,Yes', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (110, 25, 5, NULL, 'dropdown', 'Co-signer\'s Credit Score', NULL, NULL, 'Select your co-signer\'s credit score', 'cosigner_credit_score', 'App\\QuestionOptions\\CreditScore', NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'required_if:cosigner_status,Yes', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (111, 25, 6, 'version-1', 'number', 'Co-signer\'s Annual Income (USD)', NULL, 'How much will your co-signer earn in the next 12 months?', 'Annual Income', 'cosigner_annual_income', NULL, NULL, 'App\\VisibilityPolicies\\IfCosignerStatusIsYes', 'nullable|numeric', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (112, 26, 1, 'version-1', 'dropdown', 'What kind of loans are you looking to refinance?', NULL, NULL, 'Select one of the options', 'refinance_loan_type', 'App\\QuestionOptions\\ExistingStudentLoanTypeOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 19:47:51', '2020-12-03 02:58:17', '2020-12-03 02:58:17');
INSERT INTO `questions` VALUES (113, 26, 2, 'version-1', 'dropdown', 'Are you currently employed?', NULL, NULL, 'Select one of the options', 'is_currently_employed', 'App\\QuestionOptions\\YesNoBoolean', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (114, 26, 3, 'version-1', 'dropdown', 'Do you have an offer letter with a start date?', NULL, NULL, 'Select one of the options', 'have_job_start_date', 'App\\QuestionOptions\\YesNoBoolean', NULL, 'App\\VisibilityPolicies\\IfCurrentlyEmployedIsNo', 'required_if:is_currently_employed,0', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (115, 26, 4, 'version-1', 'date', 'What is your start date?', NULL, NULL, NULL, 'job_start_date', NULL, NULL, 'App\\VisibilityPolicies\\IfHasJobStartDateYes', 'required_if:have_job_start_date,1|date_format:Y-m-d|nullable', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 19:47:51', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (116, 24, 8, 'version-1', 'dropdown', 'Did you go to graduate school?', NULL, NULL, NULL, 'went_to_graduate_school', 'App\\QuestionOptions\\YesNo', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 21:39:13', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (117, 27, 1, NULL, 'searchable-dropdown', 'Where did you get your undergraduate degree?', NULL, NULL, NULL, 'university_id', 'App\\QuestionOptions\\University', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 21:49:16', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (118, 27, 2, NULL, 'searchable-dropdown', 'What was your undergraduate major?', NULL, NULL, NULL, 'degree_id', 'App\\QuestionOptions\\UndergraduateDegree', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 21:50:32', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (119, 27, 3, 'version-1', 'searchable-dropdown', 'Where is your university located?', NULL, NULL, NULL, 'university_country_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfUniversityIsOther', NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 21:52:25', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (120, 27, 4, 'version-1', 'month-and-year-with-input', 'What was your undergraduate graduation?', NULL, NULL, NULL, 'undergraduate_month_year', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 21:53:33', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (121, 28, 1, NULL, 'searchable-dropdown', 'Where did you get your undergraduate degree?', NULL, NULL, NULL, 'university_id', 'App\\QuestionOptions\\University', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:04:36', '2020-12-01 22:04:36', NULL);
INSERT INTO `questions` VALUES (122, 28, 2, NULL, 'searchable-dropdown', 'What was your undergraduate major?', NULL, NULL, NULL, 'degree_id', 'App\\QuestionOptions\\UndergraduateDegree', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:04:36', '2020-12-01 22:04:36', NULL);
INSERT INTO `questions` VALUES (123, 28, 3, NULL, 'searchable-dropdown', 'Where is your university located?', NULL, NULL, NULL, 'university_country_id', 'App\\QuestionOptions\\Country', NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:04:36', '2020-12-01 22:04:36', NULL);
INSERT INTO `questions` VALUES (124, 28, 4, 'version-1', 'month-and-year-with-input', 'What was your undergraduate graduation?', NULL, NULL, NULL, 'undergraduate_month_year', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:04:36', '2020-12-21 23:47:24', NULL);
INSERT INTO `questions` VALUES (125, 29, 1, 'version-1', 'searchable-dropdown', 'Where did you get your graduate degree?', NULL, NULL, NULL, 'grad_university_id', 'App\\QuestionOptions\\University', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:14:16', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (126, 29, 2, 'version-1', 'searchable-dropdown', 'What was your graduate major?', NULL, NULL, NULL, 'grad_degree_id', 'App\\QuestionOptions\\GraduateDegree', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:14:16', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (127, 29, 3, 'version-1', 'searchable-dropdown', 'Where is your university located?', NULL, NULL, NULL, 'university_country_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfUniversityIsOther', 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:14:16', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (128, 29, 4, 'version-1', 'month-and-year-with-input', 'When was your graduate graduation?', NULL, NULL, 'YYYY-MM', 'graduate_month_year', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:14:16', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (129, 26, 5, 'version-1', 'number', 'What\'s your expected annual compensation?', NULL, 'Base Salary + Guaranteed bonus. Even if you don’t have an offer right now, enter what you expect to earn after graduation.', NULL, 'expected_annual_compensation', NULL, NULL, 'App\\VisibilityPolicies\\IfCurrentlyEmployedIsNo', NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:20:18', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (130, 26, 6, 'version-1', 'number', 'What is your total annual compensation?', NULL, 'Base Salary + Guaranteed bonus', NULL, 'total_annual_compensation', NULL, NULL, 'App\\VisibilityPolicies\\IfUnemployedAndWithoutOffer', NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:21:31', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (131, 26, 7, 'version-1', 'text', 'What\'s the name of your employer?', NULL, NULL, NULL, 'employer_name', NULL, NULL, 'App\\VisibilityPolicies\\IfUnemployedAndWithoutOffer', NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:22:03', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (132, 26, 8, 'version-1', 'searchable-dropdown', 'Employment Location', NULL, NULL, 'Select a country', 'employment_country_id', 'App\\QuestionOptions\\Country', NULL, 'App\\VisibilityPolicies\\IfUnemployedAndWithoutOffer', NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:24:24', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (133, 26, 9, 'version-1', 'number', 'If you have any other sources of steady income, please enter the yearly aggregate amount', NULL, NULL, NULL, 'other_yearly_income', NULL, NULL, NULL, 'nullable', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:25:07', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (134, 25, 7, NULL, 'number', 'How much money are you looking to refinance (in USD)?', NULL, NULL, NULL, 'refinance_amount', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:26:43', '2020-12-01 22:33:38', '2020-12-01 22:33:38');
INSERT INTO `questions` VALUES (135, 25, 8, NULL, 'text', 'Name of the lender', NULL, NULL, NULL, 'lender_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:27:14', '2020-12-01 22:33:40', '2020-12-01 22:33:40');
INSERT INTO `questions` VALUES (136, 25, 9, NULL, 'text', 'Currency of the loan', NULL, NULL, NULL, 'currency', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:27:49', '2020-12-01 22:33:42', '2020-12-01 22:33:42');
INSERT INTO `questions` VALUES (137, 30, 1, NULL, 'text', 'Currency of the loan', NULL, NULL, NULL, 'currency', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:32:56', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (138, 30, 2, NULL, 'text', 'Name of the lender', NULL, NULL, NULL, 'lender_name', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:33:13', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (139, 30, 3, NULL, 'number', 'How much money are you looking to refinance (in USD)?', NULL, NULL, NULL, 'refinance_amount', NULL, NULL, NULL, NULL, 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:33:30', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (140, 30, 4, 'version-1', 'number', 'What is your interest rate / APR?', NULL, 'We use this information to ensure we are securing rates that will save most people in the group money.', NULL, 'current_interest_rate', NULL, NULL, NULL, 'nullable|numeric|between:0,99.99', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:51:11', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (141, 30, 5, 'version-1', 'dropdown', 'Is the interest rate fixed or variable?', NULL, NULL, NULL, 'interest_rate_type', 'App\\QuestionOptions\\FixedVariableNotSure', NULL, NULL, 'nullable', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:53:48', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (142, 30, 6, 'version-1', 'dropdown', 'Is your loan collateralized?', NULL, 'For example, is your house supporting the loan?', NULL, 'collateralized_loan', 'App\\QuestionOptions\\YesNo', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-01 22:54:38', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (143, 30, 7, NULL, 'dropdown', 'Do you have a SSN?', NULL, NULL, NULL, 'have_ssn', 'App\\QuestionOptions\\YesNo', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:59:07', '2020-12-03 18:23:18', '2020-12-03 18:23:18');
INSERT INTO `questions` VALUES (144, 30, 8, NULL, 'dropdown', 'What\'s your credit score?', NULL, NULL, NULL, 'credit_score', 'App\\QuestionOptions\\CreditScore', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 22:59:59', '2020-12-03 18:23:21', '2020-12-03 18:23:21');
INSERT INTO `questions` VALUES (145, 30, 9, NULL, 'searchable-dropdown', 'What is your visa type?', NULL, NULL, NULL, 'visa_id', 'App\\QuestionOptions\\Visa', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-01 23:01:43', '2020-12-03 18:23:24', '2020-12-03 18:23:24');
INSERT INTO `questions` VALUES (146, 31, 1, 'version-1', 'text', 'Your First Name', NULL, NULL, 'First Name', 'first_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModel', '2020-12-02 19:42:47', '2020-12-02 19:42:47', NULL);
INSERT INTO `questions` VALUES (147, 31, 2, 'version-1', 'text', 'Your Last Name', NULL, NULL, 'Last Name', 'last_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModel', '2020-12-02 19:42:47', '2020-12-02 19:42:47', NULL);
INSERT INTO `questions` VALUES (148, 31, 3, 'version-1', 'searchable-dropdown', 'University', NULL, NULL, 'Select your University', 'university_id', 'App\\QuestionOptions\\University', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-02 19:42:47', '2020-12-02 19:44:55', '2020-12-02 19:44:55');
INSERT INTO `questions` VALUES (149, 31, 4, 'version-1', 'number', 'Graduation Year', NULL, NULL, 'Graduation Year', 'graduation_year', NULL, NULL, NULL, 'required|numeric', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-02 19:42:47', '2020-12-02 19:45:00', '2020-12-02 19:45:00');
INSERT INTO `questions` VALUES (150, 31, 3, NULL, 'number', 'What year will you graduate high school?', NULL, NULL, NULL, 'high_school_graduation_year', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-02 19:46:54', '2020-12-02 19:46:54', NULL);
INSERT INTO `questions` VALUES (151, 31, 4, 'version-1', 'dropdown', 'What test(s) are you looking to prepare for?', NULL, NULL, NULL, 'college_test_preference', 'App\\QuestionOptions\\CollegeTestPreference', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModel', '2020-12-02 19:48:00', '2020-12-02 19:56:53', NULL);
INSERT INTO `questions` VALUES (152, 32, 1, NULL, 'dropdown', 'What kind of loans are you looking to refinance?', NULL, NULL, 'Select one of the options', 'refinance_loan_type', 'App\\QuestionOptions\\ExistingStudentLoanTypeOptions', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-03 02:54:55', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (153, 32, 2, NULL, 'dropdown', 'Are you currently employed?', NULL, NULL, 'Select one of the options', 'is_currently_employed', 'App\\QuestionOptions\\YesNoBoolean', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-03 02:54:55', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (154, 32, 3, NULL, 'dropdown', 'Do you have an offer letter with a start date?', NULL, NULL, 'Select one of the options', 'have_job_start_date', 'App\\QuestionOptions\\YesNoBoolean', NULL, 'App\\VisibilityPolicies\\IfCurrentlyEmployedIsNo', 'required_if:is_currently_employed,0', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-03 02:54:55', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (155, 32, 4, 'version-1', 'date', 'What is your start date?', NULL, NULL, 'YYYY-MM-DD', 'job_start_date', NULL, NULL, 'App\\VisibilityPolicies\\IfHasJobStartDateYes', 'required_if:have_job_start_date,1|date_format:Y-m-d|nullable', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-03 02:54:55', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (156, 33, 1, NULL, 'searchable-dropdown', 'What is your visa type?', NULL, NULL, NULL, 'visa_id', 'App\\QuestionOptions\\Visa', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-03 18:22:37', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (157, 33, 2, NULL, 'dropdown', 'What\'s your credit score?', NULL, NULL, NULL, 'credit_score', 'App\\QuestionOptions\\CreditScore', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-03 18:22:37', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (158, 33, 3, NULL, 'dropdown', 'Do you have a SSN?', NULL, NULL, NULL, 'have_ssn', 'App\\QuestionOptions\\YesNo', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-03 18:22:37', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (159, 34, 1, 'version-1', 'text', 'Your First Name', NULL, NULL, 'First Name', 'first_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-12 02:05:44', '2020-12-17 01:00:56', NULL);
INSERT INTO `questions` VALUES (160, 34, 2, 'version-1', 'text', 'Your Last Name', NULL, NULL, 'Last Name', 'last_name', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-12 02:05:44', '2020-12-17 01:01:07', NULL);
INSERT INTO `questions` VALUES (161, 34, 4, 'version-1', 'number', 'What year will you graduate high school?', NULL, NULL, 'High School Graduation Year', 'high_school_graduation_year', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-12 02:05:44', '2020-12-17 01:01:23', NULL);
INSERT INTO `questions` VALUES (162, 34, 5, 'version-1', 'dropdown', 'What test(s) are you looking to prepare for?', NULL, NULL, NULL, 'college_test_preference', 'App\\QuestionOptions\\CollegeTestPreference', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserProfileModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-12 02:05:44', '2020-12-17 01:01:36', NULL);
INSERT INTO `questions` VALUES (163, 34, 3, 'version-1', 'text', 'Email', NULL, NULL, 'Email Address', 'email', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2020-12-12 02:08:51', '2020-12-17 01:01:15', NULL);
INSERT INTO `questions` VALUES (164, 10, 5, 'version-1', 'number', 'Vehicle Year', NULL, NULL, NULL, 'vehicle_year', NULL, NULL, NULL, 'required|numeric|min:1990|max:2022', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2021-01-21 16:24:21', '2021-02-11 00:57:24', '2021-02-11 00:57:24');
INSERT INTO `questions` VALUES (165, 11, 11, NULL, 'message', 'Heads up: Since your current rate is below 7%, our lending partners may not be able to provide you with a substantially lower rate.', NULL, NULL, NULL, 'last_name', NULL, NULL, 'App\\VisibilityPolicies\\IfOriginalLoanInterestRateIsLessThan7', NULL, 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2021-01-27 02:05:05', '2021-02-11 00:57:35', NULL);
INSERT INTO `questions` VALUES (166, 3, 9, 'version-1', 'text', 'Email', NULL, NULL, NULL, 'email', NULL, 'App\\SkipPolicies\\IfSignedIn', NULL, 'required|email|unique:users', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2021-02-03 18:27:04', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (167, 24, 9, 'version-1', 'text', 'Email', NULL, NULL, NULL, 'email', NULL, 'App\\SkipPolicies\\IfSignedIn', NULL, 'required|email|unique:users', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2021-02-03 18:27:04', '2021-02-03 18:27:04', NULL);
INSERT INTO `questions` VALUES (168, 14, 9, 'version-1', 'text', 'Email', NULL, NULL, NULL, 'email', NULL, 'App\\SkipPolicies\\IfSignedIn', NULL, 'required|email|unique:users', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2021-02-03 18:27:04', '2021-02-03 23:30:11', NULL);
INSERT INTO `questions` VALUES (169, 10, 8, 'version-1', 'text', 'Email', NULL, NULL, 'Email', 'email', NULL, 'App\\SkipPolicies\\IfSignedIn', NULL, 'required|email|unique:users', 'App\\PersistResponse\\PersistOnUserModelOrQuestionResponderIfUserIsNotLoggedIn', '2021-02-03 18:33:20', '2021-02-03 18:33:20', NULL);
INSERT INTO `questions` VALUES (170, 12, 5, 'version-1', 'number', 'What is your zip code?', NULL, NULL, 'Example: 90210', 'zip_code', NULL, NULL, NULL, 'required|numeric', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2021-02-11 00:51:34', '2021-02-11 01:00:53', NULL);
INSERT INTO `questions` VALUES (171, 12, 3, 'version-1', 'dropdown', 'Credit Score', NULL, NULL, NULL, 'credit_score', 'App\\QuestionOptions\\DetailedCreditScore', NULL, NULL, 'required', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2021-02-11 00:56:12', '2021-02-11 00:56:20', NULL);
INSERT INTO `questions` VALUES (172, 11, 9, 'version-1', 'number', 'Vehicle Year', NULL, NULL, NULL, 'vehicle_year', NULL, NULL, NULL, 'required|numeric|min:1990|max:2022', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2021-02-11 00:57:09', '2021-02-11 00:57:35', NULL);
INSERT INTO `questions` VALUES (173, 11, 8, 'version-1', 'number', 'Payoff Amount', NULL, 'How much you\'ll need to completely pay off your debt', NULL, 'payoff_amount', NULL, NULL, NULL, 'required|numeric', 'App\\PersistResponse\\PersistOnAutoRefinanceApplicationOrQuestionResponderIfUserIsNotLoggedIn', '2021-02-11 00:57:09', '2021-02-11 01:00:47', NULL);
INSERT INTO `questions` VALUES (174, 6, 7, 'version-1', 'number', 'Loan Amount', NULL, NULL, NULL, 'loan_amount', NULL, NULL, NULL, 'required', 'App\\PersistResponse\\PersistInQuestionResponderOnly', '2021-02-16 16:22:07', '2021-02-16 16:22:07', NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
